### ISSUE TITLE
podman chdir to current working directory: Permission denied

### ISSUE THREAD

**Issue by sbourlon** [containers/podman#10491]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

podman chdir to the current working directory then segfault when running `podman secret ls`

**Steps to reproduce the issue:**

```bash
#!/usr/bin/env bash
set -o nounset
set -o errexit
set -o xtrace

TESTUSER=testuser
DIR="/tmp/bugdemo"

rm -rf "$DIR"
mkdir -p "$DIR"
cd "$DIR"
chmod -R 700 .
ls -al
if id "$TESTUSER"; then
  sudo userdel --remove "$TESTUSER"
fi
sudo useradd --create-home "$TESTUSER"
sudo --user "$TESTUSER" -- podman secret ls
sudo --user "testuser" -- podman ps
# Run the podman command from the TESTUSER shell
# including loading the shell configuration
sudo --login --user "$TESTUSER" -- podman secret ls
```

**Describe the results you received:**

```bash
% ./bug.sh 
+ TESTUSER=testuser
+ DIR=/tmp/bugdemo
+ rm -rf /tmp/bugdemo
+ mkdir -p /tmp/bugdemo
+ cd /tmp/bugdemo
+ chmod -R 700 .
+ ls -al
total 0
drwx------  2 user user   40 May 27 15:26 .
drwxrwxrwt 49 root   root   1240 May 27 15:26 ..
+ id testuser
uid=1003(testuser) gid=1004(testuser) groups=1004(testuser)
+ sudo userdel --remove testuser
userdel: testuser mail spool (/var/spool/mail/testuser) not found
+ sudo useradd --create-home testuser
+ sudo --user testuser -- podman secret ls
WARN[0000] The cgroupv2 manager is set to systemd but there is no systemd user session available 
WARN[0000] For using systemd, you may need to login using an user session 
WARN[0000] Alternatively, you can enable lingering with: `loginctl enable-linger 1003` (possibly as root) 
WARN[0000] Falling back to --cgroup-manager=cgroupfs    
cannot chdir to /tmp/bugdemo: Permission denied
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x108 pc=0x563f2e0d8536]

goroutine 1 [running]:
github.com/containers/podman/v3/libpod.(*Runtime).GetSecretsStorageDir(0xc0002a36c0, 0x11, 0x8f0000c00005ec00)
        libpod/runtime.go:911 +0x36
github.com/containers/podman/v3/pkg/domain/infra/abi.(*ContainerEngine).SecretList(0xc0000103a8, 0x563f2ea886f8, 0xc0000440c0, 0xc000531d30, 0x563f2d66d5ca, 0xc0000c9200, 0xc000531d08, 0x12)
        pkg/domain/infra/abi/secrets.go:74 +0x48
github.com/containers/podman/v3/cmd/podman/secrets.ls(0x563f2f475860, 0x563f2f539568, 0x0, 0x0, 0x0, 0x0)
        cmd/podman/secrets/list.go:54 +0x64
github.com/spf13/cobra.(*Command).execute(0x563f2f475860, 0xc00003c1a0, 0x0, 0x0, 0x563f2f475860, 0xc00003c1a0)
        vendor/github.com/spf13/cobra/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0x563f2f47aae0, 0xc0000440c0, 0x563f2e80d100, 0x563f2f539568)
        vendor/github.com/spf13/cobra/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        vendor/github.com/spf13/cobra/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        vendor/github.com/spf13/cobra/command.go:890
main.Execute()
        cmd/podman/root.go:90 +0xe9
main.main()
        cmd/podman/main.go:37 +0x94
```

**Describe the results you expected:**

```bash
% ./bug.sh 
+ TESTUSER=testuser
+ DIR=/tmp/bugdemo
+ rm -rf /tmp/bugdemo
+ mkdir -p /tmp/bugdemo
+ cd /tmp/bugdemo
+ chmod -R 700 .
+ ls -al
total 0
drwx------  2 user user   40 May 27 15:26 .
drwxrwxrwt 49 root   root   1240 May 27 15:26 ..
+ id testuser
uid=1003(testuser) gid=1004(testuser) groups=1004(testuser)
+ sudo userdel --remove testuser
userdel: testuser mail spool (/var/spool/mail/testuser) not found
+ sudo useradd --create-home testuser
+ sudo --user testuser -- podman secret ls
WARN[0000] The cgroupv2 manager is set to systemd but there is no systemd user session available 
WARN[0000] For using systemd, you may need to login using an user session 
WARN[0000] Alternatively, you can enable lingering with: `loginctl enable-linger 1003` (possibly as root) 
WARN[0000] Falling back to --cgroup-manager=cgroupfs    
ID                         NAME                        DRIVER      CREATED     UPDATED     
ad6a9108679cbd2ee2e33af46  config-1621874689524274331  file        3 days ago  3 days ago  
bd24289e61f07be38595ad4bb  config-1621876398904080592  file        3 days ago  3 days ago
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.1.2
API Version:  3.1.2
Go Version:   go1.16.4
Git Commit:   51b8ddbc22cf5b10dd76dd9243924aa66ad7db39
Built:        Sat May 22 14:22:34 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.20.1
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: /usr/bin/conmon is owned by conmon 1:2.0.28-1
    path: /usr/bin/conmon
    version: 'conmon version 2.0.28, commit: 6b18f7e0f2e4cd7f7b016b88141e82210d370008'
  cpus: 4
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  hostname: smoasb
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
  kernel: 5.12.6-arch1-1
  linkmode: dynamic
  memFree: 4733493248
  memTotal: 16706097152
  ociRuntime:
    name: crun
    package: /usr/bin/crun is owned by crun 0.19.1-1
    path: /usr/bin/crun
    version: |-
      crun version 0.19.1
      commit: 1535fedf0b83fb898d449f9680000f729ba719f5
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: /usr/bin/slirp4netns is owned by slirp4netns 1.1.10-1
    version: |-
      slirp4netns version 1.1.10
      commit: baa2bc5ff12fe6db646c1f4f3f966526c0eba5a0
      libslirp: 4.5.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 0
  swapTotal: 0
  uptime: 67h 27m 43.88s (Approximately 2.79 days)
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  configFile: /home/user/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 0
    stopped: 2
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/user/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 8
  runRoot: /run/user/1000/containers
  volumePath: /home/user/.local/share/containers/storage/volumes
version:
  APIVersion: 3.1.2
  Built: 1621718554
  BuiltTime: Sat May 22 14:22:34 2021
  GitCommit: 51b8ddbc22cf5b10dd76dd9243924aa66ad7db39
  GoVersion: go1.16.4
  OsArch: linux/amd64
  Version: 3.1.2
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
% pacman -Qi podman
Name            : podman
Version         : 3.1.2-2
Description     : Tool and library for running OCI-based containers in pods
Architecture    : x86_64
URL             : https://github.com/containers/libpod
Licenses        : Apache
Groups          : None
Provides        : None
Depends On      : cni-plugins  conmon  containers-common  device-mapper  iptables  libseccomp  runc  slirp4netns  libsystemd  fuse-overlayfs  libgpgme.so=11-64
Optional Deps   : podman-docker: for Docker-compatible CLI
                  btrfs-progs: support btrfs backend devices [installed]
                  catatonit: --init flag support
                  crun: support for unified cgroupsv2 [installed]
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 72.52 MiB
Packager        : Morten Linderud <foxboron@archlinux.org>
Build Date      : Sat 22 May 2021 02:22:34 PM PDT
Install Date    : Mon 24 May 2021 10:03:11 AM PDT
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

laptop and google cloud

google cloud getting the following error using podman 3.2.0:
```
Version:      3.2.0-dev
API Version:  3.2.0-dev
Go Version:   go1.15.10
Git Commit:   e81457dc8e6632f4e9c7a4d240c9a73e8d509bb3-dirty
Built:        Tue Jan  1 00:00:00 1980
OS/Arch:      linux/amd64
```
```
user@instance:~$ ./bug.sh 
+ TESTUSER=testuser
+ DIR=/tmp/bugdemo
+ rm -rf /tmp/bugdemo
+ mkdir -p /tmp/bugdemo
+ cd /tmp/bugdemo
+ chmod -R 700 .
+ ls -al
total 8
drwx------  2 user user 4096 May 27 22:32 .
drwxrwxrwt 20 root         root         4096 May 27 22:32 ..
+ id testuser
id: ‘testuser’: no such user
+ sudo useradd --create-home testuser
+ sudo --user testuser -- podman secret ls
cannot chdir to /tmp/bugdemo: Permission denied
Error: chown /home/testuser/.local/share/containers/storage/overlay/l: operation not permitted
```

**Comment by zhangguanzhang** [comment]
use the latest code:
```
[root@Centos8 ~]# ./test.sh 
++ TESTUSER=testuser
++ DIR=/tmp/bugdemo
++ rm -rf /tmp/bugdemo
++ mkdir -p /tmp/bugdemo
++ cd /tmp/bugdemo
++ chmod -R 700 .
++ ls -al
total 0
drwx------  2 root root   6 May 28 09:39 .
drwxrwxrwt 11 root root 177 May 28 09:39 ..
++ id testuser
uid=1000(testuser) gid=1000(testuser) groups=1000(testuser)
++ sudo userdel --remove testuser
++ sudo useradd --create-home testuser
++ sudo --user testuser -- podman secret ls
cannot chdir to /tmp/bugdemo: Permission denied
Error: chown /home/testuser/.local/share/containers/storage/overlay/l: operation not permitted
```

**Comment by sbourlon** [comment]
I removed the segfault from the title if that part is solved in latest.

**Comment by rhatdan** [comment]
It looks like podman secret ls is trying to chdir to CWD, and since you set this up with permissions the testuser is not able to access, it is failing.

**Comment by rhatdan** [comment]
If you chown 755 /tmp/bugdemo, does it work?

**Comment by sbourlon** [comment]
@rhatdan yes, it would certainly work but everyone would have access to `/tmp/bugdemo`. Maybe podman should not chdir to CWD?

**Comment by rhatdan** [comment]
That is the default behaviour, Why not change the CWD so it is not /tmp/bugdemo?

**Comment by sbourlon** [comment]
As a workaround, I chdir to /tmp before calling podman. If accessing the CWD is useful to podman, then that's not a bug and I am happy to close that ticket.

**Comment by rhatdan** [comment]
You could also just chown the directory to 411 and then all tools could search to the Working directory, but would not be able to list or read any of the content in the directory.
