### ISSUE TITLE
Podman 3.2.0 crash in cgroups.getAvailableControllers

### ISSUE THREAD

**Issue by ocofon** [containers/podman#10666]
/kind bug

**Description**

podman in version 3.2.0 is crashing on "run" and "info" when a controller is in /proc/cgroups but is not mounted in cgroupRoot

**Steps to reproduce the issue:**

```
> podman run -it ubuntu bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xbd6528]

goroutine 1 [running]:
github.com/containers/podman/v3/pkg/cgroups.getAvailableControllers(0xc00037e780, 0xc000869200, 0x0, 0x15, 0xc0005fd500, 0x15, 0x1)
        pkg/cgroups/cgroups.go:171 +0x668
github.com/containers/podman/v3/pkg/cgroups.New(0xc0005fd500, 0x15, 0xc000450df0, 0xc0005fd500, 0x15, 0xc000000300)
        pkg/cgroups/cgroups.go:377 +0xfa
...
```

```
[pid 25251] newfstatat(AT_FDCWD, "/sys/fs/cgroup/cpuset", {st_mode=S_IFDIR|0755, st_size=60, ...}, 0) = 0
[pid 25251] newfstatat(AT_FDCWD, "/sys/fs/cgroup/cpu", {st_mode=S_IFDIR|0755, st_size=60, ...}, 0) = 0
[pid 25251] newfstatat(AT_FDCWD, "/sys/fs/cgroup/cpuacct", 0xc0004581d8, 0) = -1 ENOENT (No such file or directory)
[pid 25251] --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x18} ---
```

https://github.com/containers/podman/blob/d1cb5d14e94534d5065e20178b6bd435097920e9/pkg/cgroups/cgroups.go#L169-L172

After changing line 170 to:
```
if err == nil {
```
the commands are working again.

**Output of `podman version`:**

```
Version:      3.2.0
API Version:  3.2.0
Go Version:   go1.16.2
Built:        Fri Jun 11 10:20:51 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xbd6528]
```

**Comment by rhatdan** [comment]
Please open a PR to fix.

**Comment by flouthoc** [comment]
@ocofon You can skip the entire flow when file is not mounted on CgroupRoot. Please let me know if you are picking this up.
