### ISSUE TITLE
Podman socket does not create docker.sock for rootless Docker Compose

### ISSUE THREAD

**Issue by djnotes** [containers/podman#10770]
Most of the time I work with root-less Podman and my projects work fine. For a while I have been using [Podman-Compose](https://github.com/containers/podman-compose), but recently switched to Docker Compose backed by Podman.  
In order for Docker Compose to work with rootless Podman, I have to manually symlink `/run/user/1002/podman/podman.sock` to `/var/run/docker.sock`. 
First, I enable podman socket (non-root). Then start it and then symlink it to /var/run/docker.sock:  
```
systemctl --user enable podman.socket
systemctl --user start podman.socket
sudo ln -s /run/user/1002/podman/podman.sock /var/run/docker.sock
```

After this I can run docker-compose root-less no problem! But, after restarting the system, I still see /var/run/docker.sock is not a symlink from /run/user/1002/podman.sock:  

>ls -la /var/run/docker.sock
>lrwxrwxrwx. 1 root root 23 Jun 24 05:37 /var/run/docker.sock -> /run/podman/podman.sock

I find this cumbersome. Is it possible to make `systemctl --user` automatically create the correct user-level (non-root) symlink so that docker-compose can work with it?  

Not sure this is a bug report or a feature request. I'd suppose the latter, though. 

**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

/kind feature

**Description**

**Output of `podman version`:**

```
3.2.0
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.21.0
  cgroupControllers: []
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.29-1.el8.3.4.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: '
  cpus: 4
  distribution:
    distribution: fedora
    version: "34"
  eventLogger: journald
  hostname: codezombie
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1002
      size: 1
    - container_id: 1
      host_id: 231072
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1002
      size: 1
    - container_id: 1
      host_id: 231072
      size: 65536
  kernel: 5.12.10-300.fc34.x86_64
  linkmode: dynamic
  memFree: 10707591168
  memTotal: 16671223808
  ociRuntime:
    name: crun
    package: crun-0.20.1-1.fc34.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.20.1
      commit: 0d42f1109fd73548f44b01b3e84d04a279e99d2e
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1002/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.9-1.fc34.x86_64
    version: |-
      slirp4netns version 1.1.8+dev
      commit: 6dc0186e020232ae1a6fcc1f7afbc3ea02fd3876
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 16965951488
  swapTotal: 16965951488
  uptime: 25m 54.14s
registries:
  127.0.0.1:
    Blocked: false
    Insecure: true
    Location: 127.0.0.1
    MirrorByDigestOnly: false
    Mirrors: []
    Prefix: 127.0.0.1
  172.30.0.0/16:
    Blocked: false
    Insecure: true
    Location: 172.30.0.0/16
    MirrorByDigestOnly: false
    Mirrors: []
    Prefix: 172.30.0.0/16
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - quay.io
store:
  configFile: /home/mehdi/.config/containers/storage.conf
  containerStore:
    number: 11
    paused: 0
    running: 0
    stopped: 11
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.5.0-1.fc34.x86_64
      Version: |-
        fusermount3 version: 3.10.3
        fuse-overlayfs: version 1.5
        FUSE library version 3.10.3
        using FUSE kernel interface version 7.31
  graphRoot: /home/mehdi/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 49
  runRoot: /run/user/1002/containers
  volumePath: /home/mehdi/.local/share/containers/storage/volumes
version:
  APIVersion: 3.2.0
  Built: 1623248656
  BuiltTime: Wed Jun  9 10:24:16 2021
  GitCommit: ""
  GoVersion: go1.16.3
  OsArch: linux/amd64
  Version: 3.2.0

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.2.0-5.fc34.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

No

**Comment by Luap99** [comment]
I would say this up to the user to configure this. If you install `podman-docker` a symlink from `/run/docker.sock` to `/run/podman/podman.sock` is created. How should this work when several users activate the socket? You can only symlink to one destination. Also normal users should never get access to `/run/docker.sock`.

If you want your docker tools to talk to the rootless podman socket just set the `DOCKER_HOST` envar, e.g. `DOCKER_HOST=unix:///run/user/1002/podman/podman.sock`

**Comment by mheon** [comment]
I think `docker-compose` may also use the rootless Docker socket at `$XDG_RUNTIME_DIR/docker.sock` which we ought to be able to create ourselves. Needs further testing.

**Comment by Luap99** [comment]
No they don't. Docker always uses `/run/docker.sock` even when you are rootless. They do this because they allow access to the socket for normal users when you are part of the docker group. Even for the docker rootless cli you have to set ´DOCKER_HOST`, see https://docs.docker.com/engine/security/rootless/#client

**Comment by mheon** [comment]
It looks like they do support this but only via contexts, which means explicit configuration of Docker is still required.

I do wonder if the context is writing a config file somewhere we can mock to set the default socket path.

**Comment by DevDorrejo** [comment]
hello, what is the temporal solution for this?, like @Luap99 said, i was trying to find the config file to use $XDG_RUNTIME_DIR/podman/docker.sock, but not look and can't use podman.

**Comment by mheon** [comment]
Does setting the `DOCKER_HOST` environment variable to the path of the Podman socket not work?

**Comment by DevDorrejo** [comment]
> Does setting the `DOCKER_HOST` environment variable to the path of the Podman socket not work?

the normal user not have access to this folder.

that's why when rootles /var/run/docker.sock not work, because the link is broken, at the same time (i think) docker-compose wont work, because i run and python give me erro logs with permission denied.

docker-compose up
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.8/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.8/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.8/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.8/http/client.py", line 1007, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.8/http/client.py", line 947, in send
    self.connect()
  File "/usr/lib/python3.8/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.8/site-packages/urllib3/packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.8/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.8/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.8/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.8/http/client.py", line 1007, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.8/http/client.py", line 947, in send
    self.connect()
  File "/usr/lib/python3.8/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/usr/lib/python3.8/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/usr/lib/python3.8/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.28.5', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3.8/site-packages/compose/cli/main.py", line 80, in main
    command_func()
  File "/usr/lib/python3.8/site-packages/compose/cli/main.py", line 189, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib/python3.8/site-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
  File "/usr/lib/python3.8/site-packages/compose/cli/command.py", line 152, in get_project
    client = get_client(
  File "/usr/lib/python3.8/site-packages/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
  File "/usr/lib/python3.8/site-packages/compose/cli/docker_client.py", line 170, in docker_client
    client = APIClient(use_ssh_client=not use_paramiko_ssh, **kwargs)
  File "/usr/lib/python3.8/site-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/lib/python3.8/site-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
```

**Comment by mheon** [comment]
I'm asking whether setting the `DOCKER_HOST` environment variable to point to the *rootless* Podman socket works?

**Comment by DevDorrejo** [comment]
> I'm asking whether setting the `DOCKER_HOST` environment variable to point to the _rootless_ Podman socket works?

no, no work.

**Comment by mheon** [comment]
What did you set `DOCKER_HOST` to?

**Comment by DevDorrejo** [comment]
**All this from the rootless user point view**

export DOCKER_HOST=/var/run/podman/podman.sock (Permission denied)
export DOCKER_HOST=/var/run/docker.sock
![image](https://user-images.githubusercontent.com/7697566/125315817-7c055d00-e305-11eb-87b4-42942f89dcbd.png)


export DOCKER_HOST=/run/docker.sock 
export DOCKER_HOST=/run/podman/podman.sock (Permission denied)
![image](https://user-images.githubusercontent.com/7697566/125315616-4eb8af00-e305-11eb-8b6c-b6ea9fc9819c.png)

export DOCKER_HOST=/run/user/20000/podman/podman.sock
ln -s /run/user/20000/podman/podman.sock /run/user/20000/docker.sock
export DOCKER_HOST=/run/user/20000/docker.sock

**Comment by mheon** [comment]
You need to prefix with `unix://` to indicate this is a path to a Unix socket. I would expect `DOCKER_HOST=unix:///run/user/$UID/podman/podman.sock` to work (with $UID replaced with the UID of the user)

**Comment by DevDorrejo** [comment]
> You need to prefix with `unix://` to indicate this is a path to a Unix socket. I would expect `DOCKER_HOST=unix:///run/user/$UID/podman/podman.sock` to work (with $UID replaced with the UID of the user)

This work, i am new on this.

Thanks @mheon

**Comment by DevDorrejo** [comment]
but podman, have to create this type of env, when enabling or running the systemd podman.socket
