### ISSUE TITLE
fails to build image in docker-compose.yml but podman directly can build the same image.

### ISSUE THREAD

**Issue by tomdavidson** [containers/podman#11052]
/kind bug

**Description**
Podman can build an image from a Dockerfile directly just fine, but when doing so via docker-compose.yml, it fails. This looks like it could be a build issue but since the standalone build works, it might be an issue with the docker-compose compatibility of podman. Perhaps similar to #10671 but in that case the file could not be built directly.

The Dockerfile file:
```Dockerfile
FROM docker.io/hello-world
```
```shell
$ docker build --tag uscm5 .
STEP 1: FROM docker.io/hello-world
STEP 2: COMMIT uscm5
--> d1165f22123
Successfully tagged localhost/uscm5:latest
Successfully tagged docker.io/library/hello-world:latest
d1165f2212346b2bab48cb01c1e39ee8ad1be46b87873d9ca7a4e434980a7726
```

The docker-compose.yml file:
```yaml
services:
  web:
    build: .
    # image: docker.io/hello-world 
   # when pulling the image above rather than building, `docker-compose up` works just fine.
```

```shell
$ docker-compose up
Building web
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 203, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 1186, in up
  File "compose/cli/main.py", line 1182, in up
  File "compose/project.py", line 664, in up
  File "compose/service.py", line 364, in ensure_image_exists
  File "compose/service.py", line 1133, in build
  File "compose/service.py", line 1943, in build
  File "subprocess.py", line 800, in __init__
  File "subprocess.py", line 1551, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'docker': 'docker'
[579202] Failed to execute script docker-compose
```

The env appears to be configured correctly:
```shell
$ docker-compose -v && podman -v && buildah -v && lsb_release -r
docker-compose version 1.29.2, build 5becea4c
podman version 3.2.3
buildah version 1.21.3 (image-spec 1.0.1-dev, runtime-spec 1.0.2-dev)
Release:        21.04


$ printenv | grep -e DOCKER -e COMPOSE
DOCKER_HOST=unix:///run/user/1000/podman/podman.sock
```

**Steps to reproduce the issue:**

1. create the cited Dockerfile and docker-compose.yml file
2. attempt `docker-compose up`
3. confirm podman can build from the Dockerfile directly `podman build .`

**Describe the results you received:**

> FileNotFoundError: [Errno 2] No such file or directory: 'docker': 'docker'
> [579202] Failed to execute script docker-compose
> **Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

This happens every time.

**Output of `podman version`:** 

```
podman version 3.2.3

```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.21.3
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.27, commit: '
  cpus: 4
  distribution:
    distribution: ubuntu
    version: "21.04"
  eventLogger: journald
  hostname: frank-k204
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.11.0-25-generic
  linkmode: dynamic
  memFree: 194260992
  memTotal: 16127098880
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.20.1.5-925d-dirty
      commit: 0d42f1109fd73548f44b01b3e84d04a279e99d2e
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.1.8
      commit: unknown
      libslirp: 4.3.1-git
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 8047554560
  swapTotal: 8053059584
  uptime: 21h 10m 11.22s (Approximately 0.88 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/tom/.config/containers/storage.conf
  containerStore:
    number: 8
    paused: 0
    running: 0
    stopped: 8
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/tom/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 31
  runRoot: /run/user/1000/containers
  volumePath: /home/tom/.local/share/containers/storage/volumes
version:
  APIVersion: 3.2.3
  Built: 0
  BuiltTime: Wed Dec 31 17:00:00 1969
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 3.2.3
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Listing... Done
podman/unknown,now 100:3.2.3-1 amd64 [installed]
podman/unknown 100:3.2.3-1 arm64
podman/unknown 100:3.2.3-1 armhf
podman/unknown 100:3.2.3-1 s390x

```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Local laptop with Ubuntu 21.04.

**Comment by Luap99** [comment]
You need to create a symlink from docker to podman. On some distros you can install the `podman-docker` package which will set this up for you.
Alternatively you can set the envar `COMPOSE_DOCKER_CLI_BUILD=0` https://docs.docker.com/compose/reference/envvars/#compose_docker_cli_build

**Comment by tomdavidson** [comment]
Perfect. Setting `COMPOSE_DOCKER_CLI_BUILD=0` is where its at - thank you @Luap99 

For anyone else, Docker Composes uses the Docker CLI rather than the socket at DOCKER_HOST. Perhaps I wouldnt have noticed if I would have `alias docker=podman` but with `COMPOSE_DOCKER_CLI_BUILD=0` will use the docker client rather than CLI.

**Comment by APCBoston** [comment]
Noting for folks (like me!) coming along a bit later, COMPOSE_DOCKER_CLI_BUILD is now deprecated, but DOCKER_BUILDKIT=0 now solves this problem.
