### ISSUE TITLE
podman build: ln with ESRCH: panic

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#11148]
New one-off flake in [sys podman f34 root host](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5546497786773504/html/sys-podman-fedora-34-root-host.log.html):
```
[+0816s] not ok 177 podman pod create - hashtag AllTheOptions
         # (from function `die' in file test/system/helpers.bash, line 431,
         #  from function `run_podman' in file test/system/helpers.bash, line 221,
         #  in test file test/system/200-pod.bats, line 209)
         #   `run_podman build -t $infra_image - << EOF' failed with status 125
         # # podman rm --all --force
         # # podman ps --all --external --format {{.ID}} {{.Names}}
         # # podman images --all --format {{.Repository}}:{{.Tag}} {{.ID}}
         # quay.io/libpod/testimage:20210610 9f9ec7f2fdef
         # # podman build -t infra_wfdrgxjxb7 -
         # STEP 1/3: FROM quay.io/libpod/testimage:20210610
         # STEP 2/3: RUN ln /home/podman/pause /pause_DGbwAItNT1
         # open state file /proc/160853/stat: No such process
         # open pidfd: No such process
         # panic: runtime error: invalid memory address or nil pointer dereference
         # [signal SIGSEGV: segmentation violation code=0x1 addr=0x2c pc=0x7bf966]
         # 
         # goroutine 1 [running, locked to thread]:
         # github.com/sirupsen/logrus.(*Logger).level(...)
         # 	vendor/github.com/sirupsen/logrus/logger.go:352
         # github.com/sirupsen/logrus.(*Logger).IsLevelEnabled(...)
         # 	vendor/github.com/sirupsen/logrus/logger.go:374
         # github.com/sirupsen/logrus.(*Logger).Logf(0x0, 0x4, 0x1be9d45, 0x24, 0xc0004ff1c0, 0x2, 0x2)
         # 	vendor/github.com/sirupsen/logrus/logger.go:149 +0x26
         # github.com/sirupsen/logrus.(*Logger).Infof(...)
         # 	vendor/github.com/sirupsen/logrus/logger.go:165
         # github.com/containers/buildah.runUsingRuntime.func7(0xc0001f7850, 0xc0000b74a0, 0xc00000c3c0, 0xc0001836b0, 0xd)
         # 	vendor/github.com/containers/buildah/run_linux.go:901 +0x112
         # github.com/containers/buildah.runUsingRuntime(0x1, 0x0, 0x0, 0x0, 0x0, 0xc0001836b0, 0xd, 0xc000147140, 0x1, 0x4, ...)
         # 	vendor/github.com/containers/buildah/run_linux.go:920 +0x1b0e
         # github.com/containers/buildah.runUsingRuntimeMain()
         # 	vendor/github.com/containers/buildah/run_linux.go:1540 +0x317
         # github.com/containers/storage/pkg/reexec.Init(...)
         # 	vendor/github.com/containers/storage/pkg/reexec/reexec.go:26
         # main.main()
         # 	cmd/podman/main.go:31 +0xbc
         # Error: error building at STEP "RUN ln /home/podman/pause /pause_DGbwAItNT1": error while running runtime: exit status 2
         # [ rc=125 (** EXPECTED 0 **) ]
         # #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
         # #| FAIL: exit code is 125; expected 0
         # #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         # # podman pod rm -f -a
         # # podman rm -f -a
         # # podman image list --format {{.ID}} {{.Repository}}
         # 9f9ec7f2fdef quay.io/libpod/testimage
         # # [teardown]
         # # podman pod rm --all --force
         # # podman rm --all --force
```
Filing because there's a stack trace. This issue may need to be transferred to buildah.

**Comment by vrothberg** [comment]
Opened https://github.com/containers/buildah/pull/3431.

The nil deref only happens in a rare error case which may explain why we haven't seen it yet.

**Comment by vrothberg** [comment]
Closing, will be fixed the next time we vendor buildah.
