### ISSUE TITLE
Runtime error in podman info

### ISSUE THREAD

**Issue by eduanb** [containers/podman#11720]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1.
podmain info

**Describe the results you received:**
```
[eduan@fedora ~]$ podman info
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
panic(0x5647eb689360, 0xc000132198)
	/usr/lib/golang/src/runtime/panic.go:1065 +0x565 fp=0xc0005eb2f0 sp=0xc0005eb228 pc=0x5647e9d639e5
runtime.goPanicIndex(0x1, 0x1)
	/usr/lib/golang/src/runtime/panic.go:88 +0xa5 fp=0xc0005eb338 sp=0xc0005eb2f0 pc=0x5647e9d60da5
github.com/containers/podman/pkg/cgroups.getCgroupPathForCurrentProcess(0x0, 0x0, 0x0, 0x0)
	/builddir/build/BUILD/podman-3.3.1/_build/src/github.com/containers/podman/pkg/cgroups/cgroups.go:234 +0x365 fp=0xc0005eb448 sp=0xc0005eb338 pc=0x5647ea5242a5
github.com/containers/podman/pkg/cgroups.getAvailableControllers(0x0, 0x1, 0x0, 0xc0005eb5a0, 0x5647eadf0785, 0x5647eb15320e, 0x22)
	/builddir/build/BUILD/podman-3.3.1/_build/src/github.com/containers/podman/pkg/cgroups/cgroups.go:135 +0x30f fp=0xc0005eb530 sp=0xc0005eb448 pc=0x5647ea52356f
github.com/containers/podman/pkg/cgroups.GetAvailableControllers(0x0, 0x1, 0x0, 0x0, 0x2, 0x5647e9d789b7, 0x8)
	/builddir/build/BUILD/podman-3.3.1/_build/src/github.com/containers/podman/pkg/cgroups/cgroups.go:184 +0x45 fp=0xc0005eb5b0 sp=0xc0005eb530 pc=0x5647ea5239a5
github.com/containers/podman/libpod.(*Runtime).hostInfo(0xc000546e00, 0x5, 0xc00019afc5, 0x5)
	/builddir/build/BUILD/podman-3.3.1/_build/src/github.com/containers/podman/libpod/info.go:105 +0x174 fp=0xc0005eb9f8 sp=0xc0005eb5b0 pc=0x5647ead88114
github.com/containers/podman/libpod.(*Runtime).info(0xc000546e00, 0x0, 0x0, 0x1)
	/builddir/build/BUILD/podman-3.3.1/_build/src/github.com/containers/podman/libpod/info.go:39 +0x16d fp=0xc0005ebc28 sp=0xc0005eb9f8 pc=0x5647ead8796d
github.com/containers/podman/libpod.(*Runtime).Info(...)
	/builddir/build/BUILD/podman-3.3.1/_build/src/github.com/containers/podman/libpod/runtime.go:875
github.com/containers/podman/pkg/domain/infra/abi.(*ContainerEngine).Info(0xc00011c378, 0x5647eb7e7528, 0xc00027f8c0, 0x5647ea3b76aa, 0xc00027dc00, 0xc0005ebd08)
	/builddir/build/BUILD/podman-3.3.1/_build/src/github.com/containers/podman/pkg/domain/infra/abi/system.go:31 +0x34 fp=0xc0005ebc98 sp=0xc0005ebc28 pc=0x5647eaf62894
github.com/containers/podman/cmd/podman/system.info(0x5647ec317be0, 0x5647ec3dc338, 0x0, 0x0, 0x0, 0x0)
	/builddir/build/BUILD/podman-3.3.1/_build/src/github.com/containers/podman/cmd/podman/system/info.go:72 +0x78 fp=0xc0005ebd40 sp=0xc0005ebc98 pc=0x5647eb0ea858
github.com/containers/podman/vendor/github.com/spf13/cobra.(*Command).execute(0x5647ec317be0, 0xc00003c050, 0x0, 0x0, 0x5647ec317be0, 0xc00003c050)
	/builddir/build/BUILD/podman-3.3.1/_build/src/github.com/containers/podman/vendor/github.com/spf13/cobra/command.go:856 +0x472 fp=0xc0005ebe00 sp=0xc0005ebd40 pc=0x5647ea3b6432
github.com/containers/podman/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x5647ec31ab60, 0xc0000400d8, 0x5647eb554400, 0x5647ec3dc338)
	/builddir/build/BUILD/podman-3.3.1/_build/src/github.com/containers/podman/vendor/github.com/spf13/cobra/command.go:974 +0x375 fp=0xc0005ebee0 sp=0xc0005ebe00 pc=0x5647ea3b7055
github.com/containers/podman/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/builddir/build/BUILD/podman-3.3.1/_build/src/github.com/containers/podman/vendor/github.com/spf13/cobra/command.go:902
github.com/containers/podman/vendor/github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/builddir/build/BUILD/podman-3.3.1/_build/src/github.com/containers/podman/vendor/github.com/spf13/cobra/command.go:895
main.Execute()
	/builddir/build/BUILD/podman-3.3.1/_build/src/github.com/containers/podman/cmd/podman/root.go:90 +0xe9 fp=0xc0005ebf48 sp=0xc0005ebee0 pc=0x5647eb1076e9
main.main()
	/builddir/build/BUILD/podman-3.3.1/_build/src/github.com/containers/podman/cmd/podman/main.go:39 +0x94 fp=0xc0005ebf88 sp=0xc0005ebf48 pc=0x5647eb106ff4
runtime.main()
	/usr/lib/golang/src/runtime/proc.go:225 +0x263 fp=0xc0005ebfe0 sp=0xc0005ebf88 pc=0x5647e9d66663
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0005ebfe8 sp=0xc0005ebfe0 pc=0x5647e9d9c721

goroutine 2 [force gc (idle)]:
runtime.gopark(0x5647eb788778, 0x5647ec3a5130, 0x1411, 0x1)
	/usr/lib/golang/src/runtime/proc.go:336 +0xe6 fp=0xc000084fb0 sp=0xc000084f90 pc=0x5647e9d66aa6
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:342
runtime.forcegchelper()
	/usr/lib/golang/src/runtime/proc.go:276 +0xc5 fp=0xc000084fe0 sp=0xc000084fb0 pc=0x5647e9d66905
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000084fe8 sp=0xc000084fe0 pc=0x5647e9d9c721
created by runtime.init.7
	/usr/lib/golang/src/runtime/proc.go:264 +0x37

goroutine 3 [GC sweep wait]:
runtime.gopark(0x5647eb788778, 0x5647ec3a7980, 0x140c, 0x1)
	/usr/lib/golang/src/runtime/proc.go:336 +0xe6 fp=0xc0000857a8 sp=0xc000085788 pc=0x5647e9d66aa6
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:342
runtime.bgsweep(0xc0000ac000)
	/usr/lib/golang/src/runtime/mgcsweep.go:182 +0x145 fp=0xc0000857d8 sp=0xc0000857a8 pc=0x5647e9d51845
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0000857e0 sp=0xc0000857d8 pc=0x5647e9d9c721
created by runtime.gcenable
	/usr/lib/golang/src/runtime/mgc.go:217 +0x5e

goroutine 4 [sleep]:
runtime.gopark(0x5647eb788778, 0x5647ec3a8460, 0x1313, 0x2)
	/usr/lib/golang/src/runtime/proc.go:336 +0xe6 fp=0xc000085f20 sp=0xc000085f00 pc=0x5647e9d66aa6
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:342
runtime.scavengeSleep(0x12907e, 0x1dc28e)
	/usr/lib/golang/src/runtime/mgcscavenge.go:241 +0xc5 fp=0xc000085f78 sp=0xc000085f20 pc=0x5647e9d4f6e5
runtime.bgscavenge(0xc0000ac000)
	/usr/lib/golang/src/runtime/mgcscavenge.go:366 +0x1ed fp=0xc000085fd8 sp=0xc000085f78 pc=0x5647e9d4f90d
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000085fe0 sp=0xc000085fd8 pc=0x5647e9d9c721
created by runtime.gcenable
	/usr/lib/golang/src/runtime/mgc.go:218 +0x85

goroutine 5 [finalizer wait]:
runtime.gopark(0x5647eb788778, 0x5647ec3dc248, 0xc000411410, 0x1)
	/usr/lib/golang/src/runtime/proc.go:336 +0xe6 fp=0xc000084758 sp=0xc000084738 pc=0x5647e9d66aa6
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:342
runtime.runfinq()
	/usr/lib/golang/src/runtime/mfinal.go:175 +0xab fp=0xc0000847e0 sp=0xc000084758 pc=0x5647e9d468ab
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0000847e8 sp=0xc0000847e0 pc=0x5647e9d9c721
created by runtime.createfing
	/usr/lib/golang/src/runtime/mfinal.go:156 +0x66

goroutine 6 [GC worker (idle)]:
runtime.gopark(0x5647eb788610, 0xc000412900, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:336 +0xe6 fp=0xc000086760 sp=0xc000086740 pc=0x5647e9d66aa6
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1911 +0x105 fp=0xc0000867e0 sp=0xc000086760 pc=0x5647e9d4a625
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0000867e8 sp=0xc0000867e0 pc=0x5647e9d9c721
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1835 +0x3a

goroutine 7 [GC worker (idle)]:
runtime.gopark(0x5647eb788610, 0xc000116000, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:336 +0xe6 fp=0xc000086f60 sp=0xc000086f40 pc=0x5647e9d66aa6
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1911 +0x105 fp=0xc000086fe0 sp=0xc000086f60 pc=0x5647e9d4a625
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000086fe8 sp=0xc000086fe0 pc=0x5647e9d9c721
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1835 +0x3a

goroutine 18 [GC worker (idle)]:
runtime.gopark(0x5647eb788610, 0xc000116020, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:336 +0xe6 fp=0xc000080760 sp=0xc000080740 pc=0x5647e9d66aa6
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1911 +0x105 fp=0xc0000807e0 sp=0xc000080760 pc=0x5647e9d4a625
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0000807e8 sp=0xc0000807e0 pc=0x5647e9d9c721
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1835 +0x3a

goroutine 34 [GC worker (idle)]:
runtime.gopark(0x5647eb788610, 0xc00051c000, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:336 +0xe6 fp=0xc000518760 sp=0xc000518740 pc=0x5647e9d66aa6
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1911 +0x105 fp=0xc0005187e0 sp=0xc000518760 pc=0x5647e9d4a625
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0005187e8 sp=0xc0005187e0 pc=0x5647e9d9c721
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1835 +0x3a

goroutine 35 [GC worker (idle)]:
runtime.gopark(0x5647eb788610, 0xc000116040, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:336 +0xe6 fp=0xc000518f60 sp=0xc000518f40 pc=0x5647e9d66aa6
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1911 +0x105 fp=0xc000518fe0 sp=0xc000518f60 pc=0x5647e9d4a625
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000518fe8 sp=0xc000518fe0 pc=0x5647e9d9c721
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1835 +0x3a

goroutine 19 [GC worker (idle)]:
runtime.gopark(0x5647eb788610, 0xc000116060, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:336 +0xe6 fp=0xc000080f60 sp=0xc000080f40 pc=0x5647e9d66aa6
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1911 +0x105 fp=0xc000080fe0 sp=0xc000080f60 pc=0x5647e9d4a625
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000080fe8 sp=0xc000080fe0 pc=0x5647e9d9c721
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1835 +0x3a

goroutine 20 [GC worker (idle)]:
runtime.gopark(0x5647eb788610, 0xc00051c020, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:336 +0xe6 fp=0xc000081760 sp=0xc000081740 pc=0x5647e9d66aa6
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1911 +0x105 fp=0xc0000817e0 sp=0xc000081760 pc=0x5647e9d4a625
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0000817e8 sp=0xc0000817e0 pc=0x5647e9d9c721
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1835 +0x3a

goroutine 8 [GC worker (idle)]:
runtime.gopark(0x5647eb788610, 0xc00051c040, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:336 +0xe6 fp=0xc000087760 sp=0xc000087740 pc=0x5647e9d66aa6
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1911 +0x105 fp=0xc0000877e0 sp=0xc000087760 pc=0x5647e9d4a625
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0000877e8 sp=0xc0000877e0 pc=0x5647e9d9c721
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1835 +0x3a

goroutine 9 [GC worker (idle)]:
runtime.gopark(0x5647eb788610, 0xc000412920, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:336 +0xe6 fp=0xc000087f60 sp=0xc000087f40 pc=0x5647e9d66aa6
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1911 +0x105 fp=0xc000087fe0 sp=0xc000087f60 pc=0x5647e9d4a625
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000087fe8 sp=0xc000087fe0 pc=0x5647e9d9c721
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1835 +0x3a

goroutine 10 [GC worker (idle)]:
runtime.gopark(0x5647eb788610, 0xc000412940, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:336 +0xe6 fp=0xc000514760 sp=0xc000514740 pc=0x5647e9d66aa6
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1911 +0x105 fp=0xc0005147e0 sp=0xc000514760 pc=0x5647e9d4a625
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0005147e8 sp=0xc0005147e0 pc=0x5647e9d9c721
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1835 +0x3a

goroutine 21 [GC worker (idle)]:
runtime.gopark(0x5647eb788610, 0xc000412960, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:336 +0xe6 fp=0xc000081f60 sp=0xc000081f40 pc=0x5647e9d66aa6
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1911 +0x105 fp=0xc000081fe0 sp=0xc000081f60 pc=0x5647e9d4a625
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000081fe8 sp=0xc000081fe0 pc=0x5647e9d9c721
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1835 +0x3a

goroutine 11 [GC worker (idle)]:
runtime.gopark(0x5647eb788610, 0xc000116080, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:336 +0xe6 fp=0xc000514f60 sp=0xc000514f40 pc=0x5647e9d66aa6
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1911 +0x105 fp=0xc000514fe0 sp=0xc000514f60 pc=0x5647e9d4a625
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000514fe8 sp=0xc000514fe0 pc=0x5647e9d9c721
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1835 +0x3a

goroutine 12 [GC worker (idle)]:
runtime.gopark(0x5647eb788610, 0xc000412980, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:336 +0xe6 fp=0xc000515760 sp=0xc000515740 pc=0x5647e9d66aa6
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1911 +0x105 fp=0xc0005157e0 sp=0xc000515760 pc=0x5647e9d4a625
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0005157e8 sp=0xc0005157e0 pc=0x5647e9d9c721
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1835 +0x3a

goroutine 13 [GC worker (idle)]:
runtime.gopark(0x5647eb788610, 0xc00051c060, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:336 +0xe6 fp=0xc000515f60 sp=0xc000515f40 pc=0x5647e9d66aa6
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1911 +0x105 fp=0xc000515fe0 sp=0xc000515f60 pc=0x5647e9d4a625
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000515fe8 sp=0xc000515fe0 pc=0x5647e9d9c721
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1835 +0x3a

goroutine 36 [GC worker (idle)]:
runtime.gopark(0x5647eb788610, 0xc00051c080, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:336 +0xe6 fp=0xc000519760 sp=0xc000519740 pc=0x5647e9d66aa6
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1911 +0x105 fp=0xc0005197e0 sp=0xc000519760 pc=0x5647e9d4a625
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0005197e8 sp=0xc0005197e0 pc=0x5647e9d9c721
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1835 +0x3a

goroutine 37 [GC worker (idle)]:
runtime.gopark(0x5647eb788610, 0xc00051c0a0, 0x1418, 0x0)
	/usr/lib/golang/src/runtime/proc.go:336 +0xe6 fp=0xc000519f60 sp=0xc000519f40 pc=0x5647e9d66aa6
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1911 +0x105 fp=0xc000519fe0 sp=0xc000519f60 pc=0x5647e9d4a625
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000519fe8 sp=0xc000519fe0 pc=0x5647e9d9c721
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1835 +0x3a

goroutine 39 [chan receive]:
runtime.gopark(0x5647eb788570, 0xc0002ac058, 0xc00010170e, 0x2)
	/usr/lib/golang/src/runtime/proc.go:336 +0xe6 fp=0xc00051a6d0 sp=0xc00051a6b0 pc=0x5647e9d66aa6
runtime.chanrecv(0xc0002ac000, 0xc00051a7b0, 0xc0005b0001, 0xc0002ac000)
	/usr/lib/golang/src/runtime/chan.go:576 +0x37a fp=0xc00051a760 sp=0xc00051a6d0 pc=0x5647e9d3307a
runtime.chanrecv2(0xc0002ac000, 0xc00051a7b0, 0x5647ea22d4eb)
	/usr/lib/golang/src/runtime/chan.go:444 +0x2b fp=0xc00051a790 sp=0xc00051a760 pc=0x5647e9d32ceb
github.com/containers/podman/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x5647ec3aa7e0)
	/builddir/build/BUILD/podman-3.3.1/_build/src/github.com/containers/podman/vendor/k8s.io/klog/v2/klog.go:1164 +0x8d fp=0xc00051a7d8 sp=0xc00051a790 pc=0x5647ea9fa16d
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc00051a7e0 sp=0xc00051a7d8 pc=0x5647e9d9c721
created by github.com/containers/podman/vendor/k8s.io/klog/v2.init.0
	/builddir/build/BUILD/podman-3.3.1/_build/src/github.com/containers/podman/vendor/k8s.io/klog/v2/klog.go:418 +0xdf

goroutine 15 [select, locked to thread]:
runtime.gopark(0x5647eb7887c8, 0x0, 0x1809, 0x1)
	/usr/lib/golang/src/runtime/proc.go:336 +0xe6 fp=0xc000083e10 sp=0xc000083df0 pc=0x5647e9d66aa6
runtime.selectgo(0xc000083fa8, 0xc000083fa0, 0x0, 0x0, 0x2, 0x1, 0x1, 0x1)
	/usr/lib/golang/src/runtime/select.go:327 +0xef7 fp=0xc000083f48 sp=0xc000083e10 pc=0x5647e9d77e77
runtime.ensureSigM.func1()
	/usr/lib/golang/src/runtime/signal_unix.go:889 +0x1cd fp=0xc000083fe0 sp=0xc000083f48 pc=0x5647e9d9486d
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000083fe8 sp=0xc000083fe0 pc=0x5647e9d9c721
created by runtime.ensureSigM
	/usr/lib/golang/src/runtime/signal_unix.go:872 +0xd7

goroutine 22 [syscall]:
runtime.notetsleepg(0x5647ec3dcfc0, 0xffffffffffffffff, 0x0)
	/usr/lib/golang/src/runtime/lock_futex.go:235 +0x38 fp=0xc00012bf98 sp=0xc00012bf68 pc=0x5647e9d38f98
os/signal.signal_recv(0x0)
	/usr/lib/golang/src/runtime/sigqueue.go:168 +0xa5 fp=0xc00012bfc0 sp=0xc00012bf98 pc=0x5647e9d98e25
os/signal.loop()
	/usr/lib/golang/src/os/signal/signal_unix.go:23 +0x25 fp=0xc00012bfe0 sp=0xc00012bfc0 pc=0x5647ea4c9345
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc00012bfe8 sp=0xc00012bfe0 pc=0x5647e9d9c721
created by os/signal.Notify.func1.1
	/usr/lib/golang/src/os/signal/signal.go:151 +0x46

goroutine 50 [select]:
runtime.gopark(0x5647eb7887c8, 0x0, 0x1809, 0x1)
	/usr/lib/golang/src/runtime/proc.go:336 +0xe6 fp=0xc000095d80 sp=0xc000095d60 pc=0x5647e9d66aa6
runtime.selectgo(0xc000095fb0, 0xc000127f08, 0x0, 0x0, 0x2, 0x1, 0x0, 0x0)
	/usr/lib/golang/src/runtime/select.go:327 +0xef7 fp=0xc000095eb8 sp=0xc000095d80 pc=0x5647e9d77e77
github.com/containers/podman/libpod/shutdown.Start.func1()
	/builddir/build/BUILD/podman-3.3.1/_build/src/github.com/containers/podman/libpod/shutdown/handler.go:45 +0xab fp=0xc000095fe0 sp=0xc000095eb8 pc=0x5647eacfc88b
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000095fe8 sp=0xc000095fe0 pc=0x5647e9d9c721
created by github.com/containers/podman/libpod/shutdown.Start
	/builddir/build/BUILD/podman-3.3.1/_build/src/github.com/containers/podman/libpod/shutdown/handler.go:44 +0x116

goroutine 66 [sleep]:
runtime.gopark(0x5647eb7887b0, 0xc0000ba050, 0xc000041313, 0x1)
	/usr/lib/golang/src/runtime/proc.go:336 +0xe6 fp=0xc000083610 sp=0xc0000835f0 pc=0x5647e9d66aa6
time.Sleep(0x5f5e100)
	/usr/lib/golang/src/runtime/time.go:193 +0xd8 fp=0xc000083650 sp=0xc000083610 pc=0x5647e9d997d8
github.com/containers/podman/libpod.(*Runtime).libimageEvents.func2(0xc0002ac300, 0x5647eb783c98, 0xc000546e00)
	/builddir/build/BUILD/podman-3.3.1/_build/src/github.com/containers/podman/libpod/runtime.go:744 +0x25f fp=0xc0000837c8 sp=0xc000083650 pc=0x5647eae202df
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0000837d0 sp=0xc0000837c8 pc=0x5647e9d9c721
created by github.com/containers/podman/libpod.(*Runtime).libimageEvents
	/builddir/build/BUILD/podman-3.3.1/_build/src/github.com/containers/podman/libpod/runtime.go:721 +0x99
Aborted (core dumped)

```

**Additional information you deem important (e.g. issue happens only occasionally):**
Fedora release 34
AMD Ryzen 7 4800H with Radeon Graphics

**Output of `podman version`:**

```
Version:      3.3.1
API Version:  3.3.1
Go Version:   go1.16.6
Built:        Mon Aug 30 22:46:36 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
Not working
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.3.1-1.fc34.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical Laptop with Fedora as host

**Comment by Luap99** [comment]
@flouthoc I think you fixed this, right?

**Comment by mheon** [comment]
We did indeed. Fixed upstream, closing.

**Comment by flouthoc** [comment]
Yes this is fixed.
