### ISSUE TITLE
podman containers not allowing creation of new threads - seccomp is missing clone3

### ISSUE THREAD

**Issue by joequant** [containers/podman#11862]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

after some installations podman does not seem to allow for the create of python threads.  Suspect this might be 
a glibc 2.34/seccomp issue

**Steps to reproduce the issue:**
```
(base) [joe@big-apple key4hep-container (master)]$ podman run -ti joequant/cauldron /usr/bin/python
Python 3.9.7 (default, Oct  2 2021, 00:15:21) 
[GCC 11.2.1 20210925] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import threading
>>> 
>>> def printit():
...     print ("Hello, World!")
...     # threading.Timer(1.0, printit).start()
...     #  ^ why you need this? However it works with it too
... 
>>> threading.Timer(1.0, printit).start()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.9/threading.py", line 892, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
>>> 
```

It works with privileged

```
(base) [joe@big-apple key4hep-container (master)]$ podman run --privileged -ti joequant/cauldron /usr/bin/python
Python 3.9.7 (default, Oct  2 2021, 00:15:21) 
[GCC 11.2.1 20210925] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import threading
>>> 
>>> def printit():
...     print ("Hello, World!")
...     # threading.Timer(1.0, printit).start()
...     #  ^ why you need this? However it works with it too
... 
>>> threading.Timer(1.0, printit).start()
>>> 
>>> Hello, World!
```

Also works with older version of gcc10

```
(base) [joe@big-apple key4hep-container (master)]$ podman run -ti python
Python 3.9.7 (default, Sep 28 2021, 18:32:58) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import threading
>>> 
>>> def printit():
...     print ("Hello, World!")
...     # threading.Timer(1.0, printit).start()
...     #  ^ why you need this? However it works with it too
... 
>>> threading.Timer(1.0, printit).start()
>>> Hello, World!
```

**Describe the results you received:**

thread creation fails

**Describe the results you expected:**

thread creation succeeds

**Additional information you deem important (e.g. issue happens only occasionally):**

This is a new issue and appears to have happened once the image got upgraded to gcc 11/glibc 2.34

**Output of `podman version`:**

```
(base) [joe@big-apple key4hep-container (master)]$ podman --version
podman version 3.3.1

```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical

**Comment by joequant** [comment]
found the problem.  my seccomp does not include the clone3 systemcall

**Comment by joequant** [comment]
it appears that clone3 is in the latest common files.
