### ISSUE TITLE
runtime/cgo: pthread_create failed: EAGAIN

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#11950]
Ok, so this isn't something one would do IRL, but I was chasing a different flake and this is what happened:
```console
$ while :;do podman --storage-driver vfs pod create;podman --storage-driver vfs pod start -l; podman --storage-driver vfs stop -a -t 0;podman --storage-driver vfs pod rm -fa;podman --storage-driver vfs rm -fa;done
...works fine for an hour or two...
6ba62f8b2ba5442acd26ab0898af52fc436562d084f43620f8ec51625db5bb79
9b194ddc8f0ec1e000b4a53a0bc13b87c300cced2e636522779e639b8ab1d9b2
9b194ddc8f0ec1e000b4a53a0bc13b87c300cced2e636522779e639b8ab1d9b2
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x7f1208c24783 m=2 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7f1208c24783
stack: frame={sp:0x7f11e1cae6b0, fp:0x0} stack=[0x7f11e14af090,0x7f11e1caec90)
0x00007f11e1cae5b0:  0x0000000000000000  0x0000000000000000
0x00007f11e1cae5b0:  0x0000000000000000  0x0000000000000000
0x00007f11e1cae5c0:  0x0000000000000000  0x0000000000000000
0x00007f11e1cae5d0:  0x0000000000000000  0x00007f1208c31d59
0x00007f11e1cae5e0:  0x0000000000000000  0x0000000000000016
0x00007f11e1cae5f0:  0x0000000000000180  0x0000000000000000
0x00007f11e1cae600:  0x0000000000000170  0x0000000000000000
0x00007f11e1cae610:  0x0000000000000018  0x0000000000000000
0x00007f11e1cae620:  0x0000000000000000  0x0000000000000006
0x00007f11e1cae630:  0x0000003600000018  0x00007f1208ca7351
0x00007f11e1cae640:  0x00007f11d34ac640  0x00007f11e1cae920
0x00007f11e1cae650:  0x00007f11e1cae77e  0x00007f11e1cae77f
0x00007f11e1cae660:  0x00007f11d34ac640  0x00007f1208c22785
0x00007f11e1cae670:  0x00007f11d4000020  0x0000000000000170
0x00007f11e1cae680:  0x00000000003d0f00  0x00007f11d34ac910
0x00007f11e1cae690:  0x00007f11d34ac910  0x00007f11d34ac910
0x00007f11e1cae6a0:  0x0000000000000000  0x00007f1208c24775
0x00007f11e1cae6b0: <0x00000000007ffdc0  0x0000000000000006
0x00007f11e1cae6c0:  0x000055f54285dace  0x00007f1208bd76b6
0x00007f11e1cae6d0:  0x00007f1208d90990  0x00007f1208bc17d3
0x00007f11e1cae6e0:  0x0000000000000020  0x00007f11d34ac640
0x00007f11e1cae6f0:  0x0000000000000000  0x00007f1208c967f4
0x00007f11e1cae700:  0x00007f11d34ac640  0x000000000000000d
0x00007f11e1cae710:  0x000055f54285dac0  0x00007f1208c967f4
0x00007f11e1cae720:  0x000055f5425a8790  0x0000000000000001
0x00007f11e1cae730:  0x00007f1208d8f543  0x0000000000000001
0x00007f11e1cae740:  0x000055f54285dac0  0x00007f1208c1a6dd
0x00007f11e1cae750:  0x0000000000000d68  0x00007f1208d8f4c0
0x00007f11e1cae760:  0x00007f1208d8f543  0x00007f1208d903a0
0x00007f11e1cae770:  0x0000000000000d68  0x00007f1208c19a56
0x00007f11e1cae780:  0x00007f1208d903a0  0x0000000000000001
0x00007f11e1cae790:  0x00007f1208d8f4c0  0x00007f11e1caf640
0x00007f11e1cae7a0:  0x00007f11e1cae9e0  0x000000c000000b60
runtime: unknown pc 0x7f1208c24783
stack: frame={sp:0x7f11e1cae6b0, fp:0x0} stack=[0x7f11e14af090,0x7f11e1caec90)
0x00007f11e1cae5b0:  0x0000000000000000  0x0000000000000000
0x00007f11e1cae5c0:  0x0000000000000000  0x0000000000000000
0x00007f11e1cae5d0:  0x0000000000000000  0x00007f1208c31d59
0x00007f11e1cae5e0:  0x0000000000000000  0x0000000000000016
0x00007f11e1cae5f0:  0x0000000000000180  0x0000000000000000
0x00007f11e1cae600:  0x0000000000000170  0x0000000000000000
0x00007f11e1cae610:  0x0000000000000018  0x0000000000000000
0x00007f11e1cae620:  0x0000000000000000  0x0000000000000006
0x00007f11e1cae630:  0x0000003600000018  0x00007f1208ca7351
0x00007f11e1cae640:  0x00007f11d34ac640  0x00007f11e1cae920
0x00007f11e1cae650:  0x00007f11e1cae77e  0x00007f11e1cae77f
0x00007f11e1cae660:  0x00007f11d34ac640  0x00007f1208c22785
0x00007f11e1cae670:  0x00007f11d4000020  0x0000000000000170
0x00007f11e1cae680:  0x00000000003d0f00  0x00007f11d34ac910
0x00007f11e1cae690:  0x00007f11d34ac910  0x00007f11d34ac910
0x00007f11e1cae6a0:  0x0000000000000000  0x00007f1208c24775
0x00007f11e1cae6b0: <0x00000000007ffdc0  0x0000000000000006
0x00007f11e1cae6c0:  0x000055f54285dace  0x00007f1208bd76b6
0x00007f11e1cae6d0:  0x00007f1208d90990  0x00007f1208bc17d3
0x00007f11e1cae6e0:  0x0000000000000020  0x00007f11d34ac640
0x00007f11e1cae6f0:  0x0000000000000000  0x00007f1208c967f4
0x00007f11e1cae700:  0x00007f11d34ac640  0x000000000000000d
0x00007f11e1cae710:  0x000055f54285dac0  0x00007f1208c967f4
0x00007f11e1cae720:  0x000055f5425a8790  0x0000000000000001
0x00007f11e1cae730:  0x00007f1208d8f543  0x0000000000000001
0x00007f11e1cae740:  0x000055f54285dac0  0x00007f1208c1a6dd
0x00007f11e1cae750:  0x0000000000000d68  0x00007f1208d8f4c0
0x00007f11e1cae760:  0x00007f1208d8f543  0x00007f1208d903a0
0x00007f11e1cae770:  0x0000000000000d68  0x00007f1208c19a56
0x00007f11e1cae780:  0x00007f1208d903a0  0x0000000000000001
0x00007f11e1cae790:  0x00007f1208d8f4c0  0x00007f11e1caf640
0x00007f11e1cae7a0:  0x00007f11e1cae9e0  0x000000c000000b60

goroutine 1 [syscall]:
syscall.Syscall6(0xf7, 0x1, 0x76d27, 0xc0005d4560, 0x1000004, 0x0, 0x0)
        /usr/lib/golang/src/syscall/asm_linux_amd64.s:43 +0x5 fp=0xc0005d4510 sp=0xc0005d4508 pc=0x55f541544c85
os.(*Process).blockUntilWaitable(0xc000315b90)
        /usr/lib/golang/src/os/wait_waitid.go:33 +0x9c fp=0xc0005d4600 sp=0xc0005d4510 pc=0x55f54156ecfc
os.(*Process).wait(0xc000315b90)
        /usr/lib/golang/src/os/exec_unix.go:23 +0x28 fp=0xc0005d4660 sp=0xc0005d4600 pc=0x55f541566f28
os.(*Process).Wait(...)
        /usr/lib/golang/src/os/exec.go:132
os/exec.(*Cmd).Wait(0xc00048e6e0)
        /usr/lib/golang/src/os/exec/exec.go:507 +0x54 fp=0xc0005d46d8 sp=0xc0005d4660 pc=0x55f5417a4ab4
os/exec.(*Cmd).Run(0xc0005ff4a0)
        /usr/lib/golang/src/os/exec/exec.go:341 +0x39 fp=0xc0005d46f8 sp=0xc0005d46d8 pc=0x55f5417a3f19
github.com/containers/podman/vendor/github.com/containernetworking/cni/pkg/invoke.(*RawExec).ExecPlugin(0xc0000736b0, {0x55f542c2abf8, 0xc00003e0b0}, {0xc0005ff4a0, 0x17}, {0xc0005ff4e8, 0x16, 0x18}, {0xc0000c2800, 0x20, ...})
        /builddir/build/BUILD/podman-3.4.0/_build/src/github.com/containers/podman/vendor/github.com/containernetworking/cni/pkg/invoke/raw_exec.go:45 +0x237 fp=0xc0005d4780 sp=0xc0005d46f8 pc=0x55f541b136d7
github.com/containers/podman/vendor/github.com/containernetworking/cni/pkg/invoke.(*DefaultExec).ExecPlugin(0xc0000736a0, {0x55f542c2abf8, 0xc00003e0b0}, {0xc0005ff4a0, 0xc0005ff4a0}, {0xc0005ff4e8, 0x55f543937c60, 0x55f54387e2b0}, {0xc0000c2800, 0x20, ...})
        <autogenerated>:1 +0x76 fp=0xc0005d47e8 sp=0xc0005d4780 pc=0x55f541b13d56
github.com/containers/podman/vendor/github.com/containernetworking/cni/pkg/invoke.GetVersionInfo({0x55f542c2abf8, 0xc00003e0b0}, {0xc0005ff4a0, 0x17}, {0x55f542c06fb8, 0xc0000736a0})
        /builddir/build/BUILD/podman-3.4.0/_build/src/github.com/containers/podman/vendor/github.com/containernetworking/cni/pkg/invoke/exec.go:121 +0x1e3 fp=0xc0005d4918 sp=0xc0005d47e8 pc=0x55f541b12f63
github.com/containers/podman/vendor/github.com/containernetworking/cni/libcni.(*CNIConfig).validatePlugin(0xc000410540, {0x55f542c2abf8, 0xc00003e0b0}, {0xc0001685ba, 0x6}, {0xc000168058, 0x5})
        /builddir/build/BUILD/podman-3.4.0/_build/src/github.com/containers/podman/vendor/github.com/containernetworking/cni/libcni/api.go:639 +0x165 fp=0xc0005d49a8 sp=0xc0005d4918 pc=0x55f541b181a5
github.com/containers/podman/vendor/github.com/containernetworking/cni/libcni.(*CNIConfig).ValidateNetworkList(0xc0001f0240, {0x55f542c2abf8, 0xc00003e0b0}, 0xc00033c720)
        /builddir/build/BUILD/podman-3.4.0/_build/src/github.com/containers/podman/vendor/github.com/containernetworking/cni/libcni/api.go:588 +0x18a fp=0xc0005d4c98 sp=0xc0005d49a8 pc=0x55f541b17aaa
github.com/containers/podman/vendor/github.com/cri-o/ocicni/pkg/ocicni.loadNetworks({0xc0002443a0, 0x1}, 0x0)
        /builddir/build/BUILD/podman-3.4.0/_build/src/github.com/containers/podman/vendor/github.com/cri-o/ocicni/pkg/ocicni/ocicni.go:324 +0x433 fp=0xc0005d4eb8 sp=0xc0005d4c98 pc=0x55f541b2d1b3
github.com/containers/podman/vendor/github.com/cri-o/ocicni/pkg/ocicni.(*cniNetworkPlugin).syncNetworkConfig(0xc00042e900)
        /builddir/build/BUILD/podman-3.4.0/_build/src/github.com/containers/podman/vendor/github.com/cri-o/ocicni/pkg/ocicni/ocicni.go:360 +0x5b fp=0xc0005d4f70 sp=0xc0005d4eb8 pc=0x55f541b2d8bb
github.com/containers/podman/vendor/github.com/cri-o/ocicni/pkg/ocicni.initCNI({0x0, 0x0}, {0x0, 0x0}, {0x55f5425b4179, 0x6}, {0xc0002443a0, 0xc000197080}, 0x0, {0x55f54387e2a0, ...})
        /builddir/build/BUILD/podman-3.4.0/_build/src/github.com/containers/podman/vendor/github.com/cri-o/ocicni/pkg/ocicni/ocicni.go:251 +0x41d fp=0xc0005d4ff8 sp=0xc0005d4f70 pc=0x55f541b2cb1d
github.com/containers/podman/vendor/github.com/cri-o/ocicni/pkg/ocicni.InitCNINoInotify(...)
        /builddir/build/BUILD/podman-3.4.0/_build/src/github.com/containers/podman/vendor/github.com/cri-o/ocicni/pkg/ocicni/ocicni.go:208
github.com/containers/podman/libpod.makeRuntime({0x55f542c2abf8, 0xc00003e088}, 0xc0000c1880)
        /builddir/build/BUILD/podman-3.4.0/_build/src/github.com/containers/podman/libpod/runtime.go:492 +0x14b9 fp=0xc0005d5410 sp=0xc0005d4ff8 pc=0x55f54233be19
github.com/containers/podman/libpod.newRuntimeFromConfig({0x55f542c2abf8, 0xc00003e088}, 0xc000197080, {0xc0000101d8, 0x1, 0x55f5425c4030})
        /builddir/build/BUILD/podman-3.4.0/_build/src/github.com/containers/podman/libpod/runtime.go:221 +0x407 fp=0xc0005d5730 sp=0xc0005d5410 pc=0x55f54233a347
github.com/containers/podman/libpod.NewRuntime({0x55f542c2abf8, 0xc00003e088}, {0xc0000101d8, 0x1, 0x1})
        /builddir/build/BUILD/podman-3.4.0/_build/src/github.com/containers/podman/libpod/runtime.go:168 +0x74 fp=0xc0005d5778 sp=0xc0005d5730 pc=0x55f542339ef4
github.com/containers/podman/pkg/domain/infra.getRuntime({0x55f542c2abf8, 0xc00003e088}, 0xc000492300, 0xc0005d5ac8)
        /builddir/build/BUILD/podman-3.4.0/_build/src/github.com/containers/podman/pkg/domain/infra/runtime_libpod.go:241 +0x166d fp=0xc0005d5aa8 sp=0xc0005d5778 pc=0x55f5424a786d
github.com/containers/podman/pkg/domain/infra.GetRuntime.func1()
        /builddir/build/BUILD/podman-3.4.0/_build/src/github.com/containers/podman/pkg/domain/infra/runtime_libpod.go:79 +0x49 fp=0xc0005d5af8 sp=0xc0005d5aa8 pc=0x55f5424a6189
sync.(*Once).doSlow(0xd80000000000001b, 0x1b)
        /usr/lib/golang/src/sync/once.go:68 +0xd2 fp=0xc0005d5b60 sp=0xc0005d5af8 pc=0x55f5414f75b2
sync.(*Once).Do(...)
        /usr/lib/golang/src/sync/once.go:59
github.com/containers/podman/pkg/domain/infra.GetRuntime({0x55f542c2abf8, 0xc00003e088}, 0xc0004b9410, 0x55f5425b294b)
        /builddir/build/BUILD/podman-3.4.0/_build/src/github.com/containers/podman/pkg/domain/infra/runtime_libpod.go:78 +0x78 fp=0xc0005d5ba8 sp=0xc0005d5b60 pc=0x55f5424a60d8
github.com/containers/podman/pkg/domain/infra.NewLibpodImageRuntime(0x55f5438a40e0, 0xc0005d5c18)
        /builddir/build/BUILD/podman-3.4.0/_build/src/github.com/containers/podman/pkg/domain/infra/runtime_proxy.go:24 +0x34 fp=0xc0005d5be0 sp=0xc0005d5ba8 pc=0x55f5424a9234
github.com/containers/podman/pkg/domain/infra.NewImageEngine(0x55f542600d98)
        /builddir/build/BUILD/podman-3.4.0/_build/src/github.com/containers/podman/pkg/domain/infra/runtime_abi.go:33 +0x4a fp=0xc0005d5c50 sp=0xc0005d5be0 pc=0x55f5424a5a4a
github.com/containers/podman/cmd/podman/registry.NewImageEngine(0x55f5429c1700, {0xc0004b9410, 0x55f5425baeb8, 0xa})
        /builddir/build/BUILD/podman-3.4.0/_build/src/github.com/containers/podman/cmd/podman/registry/registry.go:53 +0x51 fp=0xc0005d5c68 sp=0xc0005d5c50 pc=0x55f5424a99b1
main.persistentPreRunE(0x55f54388e560, {0xc0004b92f0, 0x0, 0x3})
        /builddir/build/BUILD/podman-3.4.0/_build/src/github.com/containers/podman/cmd/podman/root.go:159 +0x4dc fp=0xc0005d5d70 sp=0xc0005d5c68 pc=
main.main()
        /builddir/build/BUILD/podman-3.4.0/_build/src/github.com/containers/podman/cmd/podman/main.go:39 +0x74 fp=0xc0005d5f80 sp=0xc0005d5f50 pc=0x55f5425a34b4
runtime.main()
        /usr/lib/golang/src/runtime/proc.go:255 +0x227 fp=0xc0005d5fe0 sp=0xc0005d5f80 pc=0x55f5414bda27
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0005d5fe8 sp=0xc0005d5fe0 pc=0x55f5414ed2c1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc00005cfb0 sp=0xc00005cf90 pc=0x55f5414bddf6
runtime.goparkunlock(...)
        /usr/lib/golang/src/runtime/proc.go:372
runtime.forcegchelper()
        /usr/lib/golang/src/runtime/proc.go:306 +0xad fp=0xc00005cfe0 sp=0xc00005cfb0 pc=0x55f5414bdc8d
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00005cfe8 sp=0xc00005cfe0 pc=0x55f5414ed2c1
created by runtime.init.8
        /usr/lib/golang/src/runtime/proc.go:294 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc00005d7b0 sp=0xc00005d790 pc=0x55f5414bddf6
runtime.goparkunlock(...)
        /usr/lib/golang/src/runtime/proc.go:372
runtime.bgsweep()
        /usr/lib/golang/src/runtime/mgcsweep.go:182 +0xd8 fp=0xc00005d7e0 sp=0xc00005d7b0 pc=0x55f5414a90b8
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00005d7e8 sp=0xc00005d7e0 pc=0x55f5414ed2c1
created by runtime.gcenable
        /usr/lib/golang/src/runtime/mgc.go:181 +0x55

goroutine 4 [runnable]:
runtime.gopark(0xc00005dfb8, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc00005df80 sp=0xc00005df60 pc=0x55f5414bddf6
runtime.goparkunlock(...)
        /usr/lib/golang/src/runtime/proc.go:372
runtime.bgscavenge()
....
lots and lots and lots more
...
goroutine 29 [runnable]:
os/exec.(*Cmd).Start.func2()
        /usr/lib/golang/src/os/exec/exec.go:448 fp=0xc00005bfe0 sp=0xc00005bfd8 pc=0x55f5d551c860
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00005bfe8 sp=0xc00005bfe0 pc=0x55f5d52652c1
created by os/exec.(*Cmd).Start
        /usr/lib/golang/src/os/exec/exec.go:448 +0x7ef

goroutine 27 [runnable]:
os/exec.(*Cmd).Start·dwrap·1()
        /usr/lib/golang/src/os/exec/exec.go:440 fp=0xc00005f7e0 sp=0xc00005f7d8 pc=0x55f5d551c940
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00005f7e8 sp=0xc00005f7e0 pc=0x55f5d52652c1
created by os/exec.(*Cmd).Start
        /usr/lib/golang/src/os/exec/exec.go:440 +0x80d

goroutine 28 [runnable]:
os/exec.(*Cmd).Start·dwrap·1()
        /usr/lib/golang/src/os/exec/exec.go:440 fp=0xc00005ffe0 sp=0xc00005ffd8 pc=0x55f5d551c940
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00005ffe8 sp=0xc00005ffe0 pc=0x55f5d52652c1
created by os/exec.(*Cmd).Start
        /usr/lib/golang/src/os/exec/exec.go:440 +0x80d

goroutine 26 [runnable]:
os/exec.(*Cmd).Start·dwrap·1()
        /usr/lib/golang/src/os/exec/exec.go:440 fp=0xc00010f7e0 sp=0xc00010f7d8 pc=0x55f5d551c940
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00010f7e8 sp=0xc00010f7e0 pc=0x55f5d52652c1
created by os/exec.(*Cmd).Start
        /usr/lib/golang/src/os/exec/exec.go:440 +0x80d

rax    0x0
rbx    0x7f044ac7e640
rcx    0x7f0471bf3783
rdx    0x6
rdi    0x76d80
rsi    0x76d82
rbp    0x76d82
rsp    0x7f044ac7d6b0
r8     0x7f044ac7d6e0
r9     0x7f0471d194e0
r10    0x8
r11    0x206
r12    0x6
r13    0x7f044ac7d9e0
r14    0xc000000b60
r15    0x7f044adaf30d
rip    0x7f0471bf3783
rflags 0x206
cs     0x33
fs     0x0
gs     0x0

-----

SIGQUIT: quit
PC=0x55f5d52670c1 m=0 sigcode=0

goroutine 0 [idle]:
runtime.futex()
        /usr/lib/golang/src/runtime/sys_linux_amd64.s:519 +0x21 fp=0x7ffcfbb49170 sp=0x7ffcfbb49168 pc=0x55f5d52670c1
runtime.futexsleep(0x6, 0xd76bad80, 0xc00004e000)
        /usr/lib/golang/src/runtime/os_linux.go:44 +0x36 fp=0x7ffcfbb491c0 sp=0x7ffcfbb49170 pc=0x55f5d522f216
runtime.notesleep(0x55f5d76baed0)
        /usr/lib/golang/src/runtime/lock_futex.go:160 +0x87 fp=0x7ffcfbb491f8 sp=0x7ffcfbb491c0 pc=0x55f5d5209d47
runtime.mPark()
        /usr/lib/golang/src/runtime/proc.go:1441 +0x2a fp=0x7ffcfbb49218 sp=0x7ffcfbb491f8 pc=0x55f5d523872a
runtime.stoplockedm()
        /usr/lib/golang/src/runtime/proc.go:2602 +0x65 fp=0x7ffcfbb49268 sp=0x7ffcfbb49218 pc=0x55f5d523a3a5
runtime.schedule()
        /usr/lib/golang/src/runtime/proc.go:3299 +0x3d fp=0x7ffcfbb492b0 sp=0x7ffcfbb49268 pc=0x55f5d523be7d
runtime.park_m(0xc000573040)
        /usr/lib/golang/src/runtime/proc.go:3516 +0x14d fp=0x7ffcfbb492e0 sp=0x7ffcfbb492b0 pc=0x55f5d523c5cd
runtime.mcall()
        /usr/lib/golang/src/runtime/asm_amd64.s:307 +0x45 fp=0x7ffcfbb492f0 sp=0x7ffcfbb492e0 pc=0x55f5d5263005
rax    0xca
rbx    0x0
rcx    0x55f5d52670c3
rdx    0x0
rdi    0x55f5d76baed0
rsi    0x80
rbp    0x7ffcfbb491b0
rsp    0x7ffcfbb49168
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x203000
r13    0x203000
r14    0x55f5d76ba220
r15    0x7f044adc460d
rip    0x55f5d52670c1
rflags 0x286
cs     0x33
fs     0x0
gs     0x0

-----

SIGQUIT: quit
PC=0x55f5d52670c1 m=3 sigcode=0

goroutine 0 [idle]:
runtime.futex()
        /usr/lib/golang/src/runtime/sys_linux_amd64.s:519 +0x21 fp=0x7f044a2dca40 sp=0x7f044a2dca38 pc=0x55f5d52670c1
runtime.futexsleep(0x0, 0x0, 0x7ffcfbbc79ea)
        /usr/lib/golang/src/runtime/os_linux.go:44 +0x36 fp=0x7f044a2dca90 sp=0x7f044a2dca40 pc=0x55f5d522f216
runtime.notesleep(0xc000060950)
        /usr/lib/golang/src/runtime/lock_futex.go:160 +0x87 fp=0x7f044a2dcac8 sp=0x7f044a2dca90 pc=0x55f5d5209d47
runtime.mPark()
        /usr/lib/golang/src/runtime/proc.go:1441 +0x2a fp=0x7f044a2dcae8 sp=0x7f044a2dcac8 pc=0x55f5d523872a
runtime.stopm()
        /usr/lib/golang/src/runtime/proc.go:2408 +0x78 fp=0x7f044a2dcb10 sp=0x7f044a2dcae8 pc=0x55f5d5239c78
runtime.findrunnable()
        /usr/lib/golang/src/runtime/proc.go:2984 +0x865 fp=0x7f044a2dcc00 sp=0x7f044a2dcb10 pc=0x55f5d523b145
runtime.schedule()
        /usr/lib/golang/src/runtime/proc.go:3367 +0x239 fp=0x7f044a2dcc48 sp=0x7f044a2dcc00 pc=0x55f5d523c079
runtime.goexit0(0xc0000aa680)
        /usr/lib/golang/src/runtime/proc.go:3691 +0x225 fp=0x7f044a2dcc80 sp=0x7f044a2dcc48 pc=0x55f5d523cfe5
runtime.mcall()
        /usr/lib/golang/src/runtime/asm_amd64.s:307 +0x45 fp=0x7f044a2dcc90 sp=0x7f044a2dcc80 pc=0x55f5d5263005
rax    0xca
rbx    0x0
rcx    0x55f5d52670c3
rdx    0x0
rdi    0xc000060950
rsi    0x80
rbp    0x7f044a2dca80
rsp    0x7f044a2dca38
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x7f044a2dcaf0
r13    0xffffffffffffffff
r14    0xc000001380
r15    0x0
rip    0x55f5d52670c1
rflags 0x286
cs     0x33
fs     0x0
gs     0x0

-----

SIGQUIT: quit
PC=0x55f5d52670c1 m=4 sigcode=0
....
SIGQUIT: quit
PC=0x55f5d52670c1 m=6 sigcode=0

goroutine 0 [idle]:
runtime.futex()
        /usr/lib/golang/src/runtime/sys_linux_amd64.s:519 +0x21 fp=0x7f043bffeb80 sp=0x7f043bffeb78 pc=0x55f5d52670c1
runtime.futexsleep(0x55f5d525999b, 0xd7295830, 0x55f5d7649f00)
        /usr/lib/golang/src/runtime/os_linux.go:44 +0x36 fp=0x7f043bffebd0 sp=0x7f043bffeb80 pc=0x55f5d522f216
runtime.notesleep(0xc000327d50)
        /usr/lib/golang/src/runtime/lock_futex.go:160 +0x87 fp=0x7f043bffec08 sp=0x7f043bffebd0 pc=0x55f5d5209d47
runtime.mPark()
        /usr/lib/golang/src/runtime/proc.go:1441 +0x2a fp=0x7f043bffec28 sp=0x7f043bffec08 pc=0x55f5d523872a
runtime.stopm()
        /usr/lib/golang/src/runtime/proc.go:2408 +0x78 fp=0x7f043bffec50 sp=0x7f043bffec28 pc=0x55f5d5239c78
runtime.exitsyscall0(0xc000000340)
        /usr/lib/golang/src/runtime/proc.go:4115 +0x156 fp=0x7f043bffec80 sp=0x7f043bffec50 pc=0x55f5d523de36
runtime.mcall()
        /usr/lib/golang/src/runtime/asm_amd64.s:307 +0x45 fp=0x7f043bffec90 sp=0x7f043bffec80 pc=0x55f5d5263005
rax    0xca
rbx    0x0
rcx    0x55f5d52670c3
rdx    0x0
rdi    0xc000327d50
rsi    0x80
rbp    0x7f043bffebc0
rsp    0x7f043bffeb78
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x55f5d523dce0
r13    0x55f5d641af00
r14    0xc0004ac000
r15    0x7f044ada9549
rip    0x55f5d52670c1
rflags 0x286
cs     0x33
fs     0x0
gs     0x0

-----

```
podman-3.4.0-3.fc36.x86_64, crun-1.2-1.fc36.x86_64, conmon-2.0.30-2.fc36.x86_64 on 5.14.0-0.rc5.20210813gitf8e6dfc64f61.46.fc36

Once this happens, podman is forever unusable, it always crashes the same way. Even `podman info`. I rebooted, started the reproducer again, and (an hour or two later) it crashed again.

**Comment by Luap99** [comment]
see https://github.com/golang/go/issues/24484
Can you check if podman is leaking processes?

**Comment by Luap99** [comment]
Well I would assume something is leaking until you reach the max pid limit and than go starts failing.
We could also leak other processes than podman, e.g. conmon or CNI plugins. I think you should check that before we close this.

**Comment by edsantiago** [comment]
OK, it crashed, just about 45 minutes. I was running `ps auxww|wc -l` in a separate window periodically, it always showed 99-102, and still does right now.

**Comment by rhatdan** [comment]
Is this something we are ever going to work on fixing?  Are we seeing this in the real world?

**Comment by rhatdan** [comment]
And the beat goes on.

**Comment by edsantiago** [comment]
Could not reproduce overnight; assuming it was a golang bug that has been fixed.
