### ISSUE TITLE
podman-remote container restore: panic

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#12007]
I have no opinion on whether `podman-remote container restore` should work or not; but I would prefer if it didn't panic:
```console
$ sudo bin/podman-remote run -d --name foo alpine sleep 100;sudo bin/podman-remote container checkpoint foo;sudo bin/podman-remote container restore foo

08d8f7bf3fd831295ed9931a652d7a4a2ed09ce0c37a21e518b162f166febcba
08d8f7bf3fd831295ed9931a652d7a4a2ed09ce0c37a21e518b162f166febcba
panic: reflect: call of reflect.Value.IsNil on zero Value

goroutine 1 [running]:
reflect.Value.IsNil(...)
        /usr/lib/golang/src/reflect/value.go:1086
github.com/containers/podman/v3/pkg/bindings/internal/util.Changed(0x12b0b00, 0xc000330800, 0x13170d4, 0xd, 0x0)
        /home/esm/src/atomic/2018-02.podman/libpod/pkg/bindings/internal/util/util.go:51 +0x1fa
github.com/containers/podman/v3/pkg/bindings/containers.(*RestoreOptions).Changed(...)
        /home/esm/src/atomic/2018-02.podman/libpod/pkg/bindings/containers/types_restore_options.go:12
github.com/containers/podman/v3/pkg/bindings/containers.Restore(0x14cf488, 0xc000696690, 0xc000387480, 0x40, 0xc000330800, 0x0, 0x0, 0x0)
        /home/esm/src/atomic/2018-02.podman/libpod/pkg/bindings/containers/checkpoint.go:52 +0x193
github.com/containers/podman/v3/pkg/domain/infra/tunnel.(*ContainerEngine).ContainerRestore(0xc0002f4450, 0x14cf418, 0xc000036110, 0xc0002f42c0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
        /home/esm/src/atomic/2018-02.podman/libpod/pkg/domain/infra/tunnel/containers.go:365 +0x25b
github.com/containers/podman/v3/cmd/podman/containers.restore(0x1b984e0, 0xc0002f42c0, 0x1, 0x1, 0x0, 0x0)
        /home/esm/src/atomic/2018-02.podman/libpod/cmd/podman/containers/restore.go:131 +0x255
github.com/spf13/cobra.(*Command).execute(0x1b984e0, 0xc0000320f0, 0x1, 0x1, 0x1b984e0, 0xc0000320f0)
        /home/esm/src/atomic/2018-02.podman/libpod/vendor/github.com/spf13/cobra/command.go:856 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0x1bafbe0, 0xc000036110, 0x1182c80, 0x1c60370)
        /home/esm/src/atomic/2018-02.podman/libpod/vendor/github.com/spf13/cobra/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/esm/src/atomic/2018-02.podman/libpod/vendor/github.com/spf13/cobra/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /home/esm/src/atomic/2018-02.podman/libpod/vendor/github.com/spf13/cobra/command.go:895
main.Execute()
        /home/esm/src/atomic/2018-02.podman/libpod/cmd/podman/root.go:91 +0xe7
main.main()
        /home/esm/src/atomic/2018-02.podman/libpod/cmd/podman/main.go:39 +0x92
```

**Comment by vrothberg** [comment]
I wonder how we ended up with checkpoint being supported on remote and having e2e tests for it disabled.

**Comment by vrothberg** [comment]
... continuing now
