### ISSUE TITLE
Rootless containers - /dev/ttyACM0 permission denied

### ISSUE THREAD

**Issue by CameronAM** [containers/podman#12033]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Local serial device /dev/ttyACM0 cannot be accessed from container, despite passing --userns=keep-id and --group-add keep groups.

**Steps to reproduce the issue:**

1. Ensure user part of group with access to the device

2. Run container with
```
[zigbee2mqtt@pi2-zigbee2mqtt ~]$ podman run --userns=keep-id --group-add keep-groups -it -v $(pwd)/data:/app/data:Z -v /run/udev:/run/udev:ro --device=/dev/ttyACM0:/dev/ttyACM0 ubuntu bash
zigbee2mqtt@79e47cba46a0:/$ cat /dev/ttyACM0
cat: /dev/ttyACM0: Permission denied
```

**Describe the results you received:**
Cannot access /dev/ttyACM0 from within the container.
```
cat: /dev/ttyACM0: Permission denied
zigbee2mqtt@79e47cba46a0:/$ id
uid=1001(zigbee2mqtt) gid=1001(zigbee2mqtt) groups=1001(zigbee2mqtt),65534(nogroup)
zigbee2mqtt@79e47cba46a0:/$ ls -lan /dev/
total 0
drwxr-xr-x. 5     0     0    380 Oct 19 12:32 .
dr-xr-xr-x. 1     0     0     39 Oct 19 12:32 ..
crw--w----. 1  1001     5 136, 0 Oct 19 12:34 console
lrwxrwxrwx. 1     0     0     11 Oct 19 12:32 core -> /proc/kcore
lrwxrwxrwx. 1     0     0     13 Oct 19 12:32 fd -> /proc/self/fd
crw-rw-rw-. 1 65534 65534   1, 7 Aug  6 00:00 full
drwxrwxrwt. 2     0     0     40 Oct 19 12:32 mqueue
crw-rw-rw-. 1 65534 65534   1, 3 Aug  6 00:00 null
lrwxrwxrwx. 1     0     0      8 Oct 19 12:32 ptmx -> pts/ptmx
drwxr-xr-x. 2     0     0      0 Oct 19 12:32 pts
crw-rw-rw-. 1 65534 65534   1, 8 Aug  6 00:00 random
drwxrwxrwt. 2     0     0     40 Oct 19 12:32 shm
lrwxrwxrwx. 1     0     0     15 Oct 19 12:32 stderr -> /proc/self/fd/2
lrwxrwxrwx. 1     0     0     15 Oct 19 12:32 stdin -> /proc/self/fd/0
lrwxrwxrwx. 1     0     0     15 Oct 19 12:32 stdout -> /proc/self/fd/1
crw-rw-rw-. 1 65534 65534   5, 0 Oct 19 11:32 tty
crw-rw----. 1 65534 65534 166, 0 Oct 19 12:31 ttyACM0
crw-rw-rw-. 1 65534 65534   1, 9 Aug  6 00:00 urandom
crw-rw-rw-. 1 65534 65534   1, 5 Aug  6 00:00 zero
zigbee2mqtt@79e47cba46a0:/$
```

**Describe the results you expected:**
Process within the container is able to access ttyACM0.

**Additional information you deem important (e.g. issue happens only occasionally):**

Running on fedora 34 on raspberry pi.

The actual container that I'm trying to run is `docker.io/koenkk/zigbee2mqtt:latest`, which fails with:

```
[zigbee2mqtt@pi2-zigbee2mqtt ~]$ podman run --userns=keep-id --group-add keep-groups -it -v $(pwd)/data:/app/data:Z -v /run/udev:/run/udev:ro --device=/dev/ttyACM0 docker.io/koenkk/zigbee2mqtt:latest
Using '/app/data' as data directory
Zigbee2MQTT:info  2021-10-19 12:37:14: Logging to console and directory: '/app/data/log/2021-10-19.12-37-08' filename: log.txt
Zigbee2MQTT:info  2021-10-19 12:37:14: Starting Zigbee2MQTT version 1.21.2 (commit #4492212
)
Zigbee2MQTT:info  2021-10-19 12:37:14: Starting zigbee-herdsman (0.13.149)
CREATED DECONZ ADAPTER
Zigbee2MQTT:error 2021-10-19 12:37:16: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-10-19 12:37:16: Failed to start zigbee
Zigbee2MQTT:error 2021-10-19 12:37:16: Check https://www.zigbee2mqtt.io/information/FAQ.html#help-zigbee2mqtt-fails-to-start for possible solutions
Zigbee2MQTT:error 2021-10-19 12:37:16: Exiting...
Zigbee2MQTT:error 2021-10-19 12:37:16: Error: Error while opening serialport 'Error: Error: Permission denied, cannot open /dev/ttyACM0'
    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/deconz/driver/driver.ts:182:28)
    at SerialPort._error (/app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
[zigbee2mqtt@pi2-zigbee2mqtt ~]$
```

**Output of `podman version`:**

```
[zigbee2mqtt@pi2-zigbee2mqtt ~]$ podman --version
podman version 3.4.0
```

**Output of `podman info --debug`:**

```


aphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/zigbee2mqtt/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 4
  runRoot: /tmp/podman-run-1001/containers
  volumePath: /home/zigbee2mqtt/.local/share/containers/storage/volumes
version:host:
  arch: arm
  buildahVersion: 1.23.1
  cgroupControllers: []
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.30-2.fc34.armv7hl
    path: /usr/bin/conmon
    version: 'conmon version 2.0.30, commit: '
  cpus: 4
  distribution:
    distribution: fedora
    variant: server
    version: "34"
  eventLogger: journald
  hostname: pi2-zigbee2mqtt
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  kernel: 5.14.9-200.fc34.armv7hl
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 391602176
  memTotal: 1002397696
  ociRuntime:
    name: crun
    package: crun-1.2-1.fc34.armv7hl
    path: /usr/bin/crun
    version: |-
      crun version 1.2
      commit: 4f6c8e0583c679bfee6a899c05ac6b916022561b
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1001/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc34.armv7hl
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 999813120
  swapTotal: 1001385984
  uptime: 1h 16m 30.48s (Approximately 0.04 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/zigbee2mqtt/.config/containers/storage.conf
  containerStore:
    number: 38
    paused: 0
    running: 0
    stopped: 38
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/zigbee2mqtt/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 4
  runRoot: /tmp/podman-run-1001/containers
  volumePath: /home/zigbee2mqtt/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.0
  Built: 1633030874
  BuiltTime: Fri Oct  1 05:41:14 2021
  GitCommit: ""
  GoVersion: go1.16.8
  OsArch: linux/arm
  Version: 3.4.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
[zigbee2mqtt@pi2-zigbee2mqtt ~]$ rpm -q podman
podman-3.4.0-1.fc34.armv7hl
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on fedora 34 on a raspberry pi

**Comment by CameronAM** [comment]
The user has access to `/dev/ttyACM0` outside of the container, I have confirmed that the application will start up outside of container without issue.

As stated in my initial post, I _am_ running the command with `--group-add=keep-groups` and `--userns=keep-id`.

Any further ideas?

**Comment by felixn** [comment]
Had the same issue, `--security-opt label=disable` fixed it.
