### ISSUE TITLE
blender keeps running in podman if killing it forcefully

### ISSUE THREAD

**Issue by vans163** [containers/podman#13186]
/kind bug

**Description**

Forcefully killing blender using CTRL+C | +/ inside podman keeps blender running.

![image](https://user-images.githubusercontent.com/3028982/153246249-cf186fbf-4ecf-4b2f-9524-64bbee9c41df.png)

**Steps to reproduce the issue:**

```
podman run --rm --entrypoint bash docker.io/nytimes/blender:3.0-gpu-ubuntu18.04 -c "wget https://raw.githubusercontent.com/zodtv/examples/main/blender/bootstrap.sh && chmod +x bootstrap.sh && ./bootstrap.sh https://gateway.ipfs.io/ipfs/QmYhEsVWdzbCU49XE8F9ybKKAPQHjhfhekoMn4Xvz857rD SIASKY OPTIX 1080 1350 1"

Run a blender image and wait until it gets to the step of rendering using blender.

Ctrl+C | +/ kill blender.
```

**Describe the results you received:**
Blender is running after podman is killed.

**Describe the results you expected:**
All child pids spawned inside podman after it is killed should be killed.

**Additional information you deem important (e.g. issue happens only occasionally):**
Podman crashes with a stacktrace

```
Fra:42 Mem:1216.00M (Peak 1457.22M) | Time:00:13.15 | Remaining:20:18.36 | Mem:355.61M, Peak:563.61M | Scene, View Layer | Rendered 0/4 Tiles, Sample 17/1000
Fra:42 Mem:1216.03M (Peak 1457.22M) | Time:00:25.01 | Remaining:06:20.89 | Mem:355.61M, Peak:563.61M | Scene, View Layer | Rendered 0/4 Tiles, Sample 145/1000
^C^\^C^\^\^C^C^\^C^\^C^\^C^\^C^\^C^\^C^\^C^\^C^C^C^C^C^\SIGQUIT: quit
PC=0x4b45ea m=0 sigcode=128

goroutine 1 [syscall]:
syscall.Syscall6(0x101, 0xffffffffffffff9c, 0xc000133850, 0x80000, 0x0, 0x0, 0x0)
	syscall/asm_linux_amd64.s:43 +0x5 fp=0xc0001e9158 sp=0xc0001e9150 pc=0x4b45c5
syscall.openat(0xc0001e9218, {0x8b0dd2, 0x7f90f685c5e0}, 0x0, 0x0)
	syscall/zsyscall_linux_amd64.go:69 +0x105 fp=0xc0001e91f0 sp=0xc0001e9158 pc=0x4b0525
syscall.Open(...)
	syscall/syscall_linux.go:155
os.openFileNolog({0x8b0dd2, 0x0}, 0x0, 0x0)
	os/file_unix.go:217 +0x9b fp=0xc0001e9240 sp=0xc0001e91f0 pc=0x4d96bb
os.OpenFile({0x8b0dd2, 0xd}, 0x0, 0x1a0)
	os/file.go:338 +0x45 fp=0xc0001e9278 sp=0xc0001e9240 pc=0x4d7785
os.Open(...)
	os/file.go:318
github.com/opencontainers/runc/libcontainer/intelrdt.parseCpuInfoFile({0x8b0dd2, 0x63677270})
	github.com/opencontainers/runc/libcontainer/intelrdt/intelrdt.go:331 +0x6c fp=0xc0001e9380 sp=0xc0001e9278 pc=0x696b4c
github.com/opencontainers/runc/libcontainer/intelrdt.featuresInit.func1()
	github.com/opencontainers/runc/libcontainer/intelrdt/intelrdt.go:213 +0x37 fp=0xc0001e9448 sp=0xc0001e9380 pc=0x699f17
sync.(*Once).doSlow(0xc0001e94d0, 0x75417e)
	sync/once.go:68 +0xd2 fp=0xc0001e94b0 sp=0xc0001e9448 pc=0x47f072
sync.(*Once).Do(...)
	sync/once.go:59
github.com/opencontainers/runc/libcontainer/intelrdt.featuresInit()
	github.com/opencontainers/runc/libcontainer/intelrdt/intelrdt.go:211 +0x31 fp=0xc0001e94d0 sp=0xc0001e94b0 pc=0x696611
github.com/opencontainers/runc/libcontainer/intelrdt.IsCATEnabled(...)
	github.com/opencontainers/runc/libcontainer/intelrdt/intelrdt.go:532
github.com/opencontainers/runc/libcontainer.IntelRdtFs(0xc0001c8090)
	github.com/opencontainers/runc/libcontainer/factory_linux.go:151 +0x25 fp=0xc0001e94e0 sp=0xc0001e94d0 pc=0x7541c5
github.com/opencontainers/runc/libcontainer.New({0xc00012a408, 0x13}, {0xc0001e95f0, 0x5, 0x1})
	github.com/opencontainers/runc/libcontainer/factory_linux.go:208 +0x1fd fp=0xc0001e9518 sp=0xc0001e94e0 pc=0x75445d
main.loadFactory(0x2)
	github.com/opencontainers/runc/utils_linux.go:72 +0x2ae fp=0xc0001e9628 sp=0xc0001e9518 pc=0x7c2b6e
main.getContainer(0xc0001586e0)
	github.com/opencontainers/runc/utils_linux.go:85 +0x4b fp=0xc0001e9660 sp=0xc0001e9628 pc=0x7c2dab
main.glob..func7(0xc0001586e0)
	github.com/opencontainers/runc/kill.go:40 +0x58 fp=0xc0001e96b0 sp=0xc0001e9660 pc=0x7c7038
github.com/opencontainers/runc/vendor/github.com/urfave/cli.HandleAction({0x812ea0, 0x8d0450}, 0x4)
	github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:523 +0xa8 fp=0xc0001e96c8 sp=0xc0001e96b0 pc=0x789b68
github.com/opencontainers/runc/vendor/github.com/urfave/cli.Command.Run({{0x8a9da0, 0x4}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x8c989c, 0x52}, {0x0, ...}, ...}, ...)
	github.com/opencontainers/runc/vendor/github.com/urfave/cli/command.go:174 +0x63a fp=0xc0001e98a8 sp=0xc0001e96c8 pc=0x78a93a
github.com/opencontainers/runc/vendor/github.com/urfave/cli.(*App).Run(0xc000178700, {0xc000130000, 0x4, 0x4})
	github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:276 +0x80c fp=0xc0001e9be8 sp=0xc0001e98a8 pc=0x787dcc
main.main()
	github.com/opencontainers/runc/main.go:163 +0x11bc fp=0xc0001e9f80 sp=0xc0001e9be8 pc=0x7bdd1c
runtime.main()
	runtime/proc.go:255 +0x227 fp=0xc0001e9fe0 sp=0xc0001e9f80 pc=0x43b607
runtime.goexit()
	runtime/asm_amd64.s:1581 +0x1 fp=0xc0001e9fe8 sp=0xc0001e9fe0 pc=0x469621

rax    0x3
rbx    0xc00002c800
rcx    0x4b45ea
rdx    0x80000
rdi    0xffffffffffffff9c
rsi    0xc000133850
rbp    0xc0001e91e0
rsp    0xc0001e9150
r8     0x0
r9     0x0
r10    0x0
r11    0x206
r12    0xc000133850
r13    0x1
r14    0xc0000001a0
r15    0x185
rip    0x4b45ea
rflags 0x206
cs     0x33
fs     0x0
gs     0x0
ERRO[0050] Error forwarding signal 2 to container 904f5b2672ce5bcdf5ab850356afac91431fedff0dbc26fc9781d6dcd32e9461: error sending signal to container 904f5b2672ce5bcdf5ab850356afac91431fedff0dbc26fc9781d6dcd32e9461: `/usr/sbin/runc kill 904f5b2672ce5bcdf5ab850356afac91431fedff0dbc26fc9781d6dcd32e9461 2` failed: exit status 2
```

**Output of `podman version`:**

```
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.17.3
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpus: 40
  distribution:
    codename: jammy
    distribution: ubuntu
    version: "22.04"
  eventLogger: journald
  hostname: video3
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.13.0-19-generic
  linkmode: dynamic
  logDriver: journald
  memFree: 127267328000
  memTotal: 135121195008
  ociRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: |-
      runc version 1.0.1-0ubuntu3
      spec: 1.0.2-dev
      go: go1.17.3
      libseccomp: 2.5.2
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.6.1
  swapFree: 8589930496
  swapTotal: 8589930496
  uptime: 61h 39m 24.82s (Approximately 2.54 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries: {}
store:
  configFile: /home/user/.config/containers/storage.conf
  containerStore:
    number: 11
    paused: 0
    running: 0
    stopped: 11
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/user/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 18
  runRoot: /run/user/1000/containers
  volumePath: /home/user/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.4
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.17.3
  OsArch: linux/amd64
  Version: 3.4.4
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Listing... Done
podman/jammy,now 3.4.4+ds1-1ubuntu1 amd64 [installed]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
Podman sends the TERM signal to the pid1 of the container, if the container process ignores it , then there is nothing that Podman can do.

You could do a `podman stop $CID` in a separate terminal, which will stop the container with a SIGKILL after 10 seconds.

**Comment by vans163** [comment]
> Podman sends the TERM signal to the pid1 of the container, if the container process ignores it , then there is nothing that Podman can do.
> 
> You could do a `podman stop $CID` in a separate terminal, which will stop the container with a SIGKILL after 10 seconds.

I dont see why podman cant send the `podman stop` by intercepting CTRL+C//.

**Comment by rhatdan** [comment]
Podman hands off the terminal handling and does not monitor what is going on.  BTW Docker works the same way.

**Comment by vans163** [comment]
I would like to add that if `podman run` is called and the caller dies (say running podman from inside script then script dies) podman keeps running.  Does that mean instead of podman run maybe something like podman exec needs to be used?

**Comment by mheon** [comment]
While I agree with Dan that we can’t do more than forward signals, the
stacktrace there looks worth investigating and fixing, Podman should not
panic
