### ISSUE TITLE
panic seen in RHCOS8 tests

### ISSUE THREAD

**Issue by cgwalters** [containers/podman#13911]
See https://github.com/coreos/coreos-assembler/pull/2805#issuecomment-1101559127

```
Apr 15 12:02:08.627814 podman[1704]: time="2022-04-15T12:02:08Z" level=info msg="Setting parallel job count to 4"
Apr 15 12:02:08.630516 podman[1708]: time="2022-04-15T12:02:08Z" level=info msg="Setting parallel job count to 4"
Apr 15 12:02:08.631356 podman[1708]: time="2022-04-15T12:02:08Z" level=info msg="Using systemd socket activation to determine API endpoint"
Apr 15 12:02:08.635564 podman[1708]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 15 12:02:08.635564 podman[1708]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x55ca3ef712d7]
Apr 15 12:02:08.635564 podman[1708]: goroutine 1 [running]:
Apr 15 12:02:08.636459 podman[1708]: panic({0x55ca3f64ebe0, 0x55ca40571e80})
Apr 15 12:02:08.636459 podman[1708]:         /usr/lib/golang/src/runtime/panic.go:1147 +0x3a8 fp=0xc0006df588 sp=0xc0006df4c8 pc=0x55ca3de44088
Apr 15 12:02:08.636459 podman[1708]: runtime.panicmem(...)
Apr 15 12:02:08.636459 podman[1708]:         /usr/lib/golang/src/runtime/panic.go:221
Apr 15 12:02:08.636459 podman[1708]: runtime.sigpanic()
Apr 15 12:02:08.636459 podman[1708]:         /usr/lib/golang/src/runtime/signal_unix.go:735 +0x327 fp=0xc0006df5d8 sp=0xc0006df588 pc=0x55ca3de5aae7
Apr 15 12:02:08.636459 podman[1708]: github.com/containers/podman/pkg/api/server.newServer(0xc0000d9a40, 0xc000044090, {{0x0, 0x0}, {0x0, 0x0}, 0x12a05f200, {0x0, 0x0}})
Apr 15 12:02:08.636459 podman[1708]:         /builddir/build/BUILD/containers-podman-49f8da7/_build/src/github.com/containers/podman/pkg/api/server/server.go:89 +0x1d7 fp=0xc0006dfa40 sp=0xc0006df5d8 pc=0x55ca3ef712d7
Apr 15 12:02:08.636459 podman[1708]: github.com/containers/podman/pkg/api/server.NewServerWithSettings(...)
Apr 15 12:02:08.636459 podman[1708]:         /builddir/build/BUILD/containers-podman-49f8da7/_build/src/github.com/containers/podman/pkg/api/server/server.go:64
Apr 15 12:02:08.636459 podman[1708]: github.com/containers/podman/cmd/podman/system.restService(0x55ca406781d0, 0x0, {{0x0, 0x0}, {0x0, 0x0}, 0x12a05f200, {0x0, 0x0}})
Apr 15 12:02:08.636459 podman[1708]:         /builddir/build/BUILD/containers-podman-49f8da7/_build/src/github.com/containers/podman/cmd/podman/system/service_abi.go:91 +0x5df fp=0xc0006dfc78 sp=0xc0006dfa40 pc=0x55ca3ef7b3ff
Apr 15 12:02:08.636459 podman[1708]: github.com/containers/podman/cmd/podman/system.service(0x55ca405a1b80, {0x55ca406781d0, 0x0, 0x0})
Apr 15 12:02:08.636459 podman[1708]:         /builddir/build/BUILD/containers-podman-49f8da7/_build/src/github.com/containers/podman/cmd/podman/system/service.go:102 +0x276 fp=0xc0006dfd70 sp=0xc0006dfc78 pc=0x55ca3ef7a956
Apr 15 12:02:08.638779 podman[1708]: github.com/containers/podman/vendor/github.com/spf13/cobra.(*Command).execute(0x55ca405a1b80, {0xc00003c0b0, 0x0, 0x0})
Apr 15 12:02:08.638779 podman[1708]:         /builddir/build/BUILD/containers-podman-49f8da7/_build/src/github.com/containers/podman/vendor/github.com/spf13/cobra/command.go:856 +0x60e fp=0xc0006dfe30 sp=0xc0006dfd70 pc=0x55ca3e44c0ae
Apr 15 12:02:08.638779 podman[1708]: github.com/containers/podman/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x55ca405a5000)
Apr 15 12:02:08.638779 podman[1708]:         /builddir/build/BUILD/containers-podman-49f8da7/_build/src/github.com/containers/podman/vendor/github.com/spf13/cobra/command.go:974 +0x3bc fp=0xc0006dfee8 sp=0xc0006dfe30 pc=0x55ca3e44c79c
Apr 15 12:02:08.638779 podman[1708]: github.com/containers/podman/vendor/github.com/spf13/cobra.(*Command).Execute(...)
Apr 15 12:02:08.638779 podman[1708]:         /builddir/build/BUILD/containers-podman-49f8da7/_build/src/github.com/containers/podman/vendor/github.com/spf13/cobra/command.go:902
Apr 15 12:02:08.638779 podman[1708]: github.com/containers/podman/vendor/github.com/spf13/cobra.(*Command).ExecuteContext(...)
Apr 15 12:02:08.638779 podman[1708]:         /builddir/build/BUILD/containers-podman-49f8da7/_build/src/github.com/containers/podman/vendor/github.com/spf13/cobra/command.go:895
Apr 15 12:02:08.638779 podman[1708]: main.Execute()
Apr 15 12:02:08.638779 podman[1708]:         /builddir/build/BUILD/containers-podman-49f8da7/_build/src/github.com/containers/podman/cmd/podman/root.go:100 +0xbe fp=0xc0006dff50 sp=0xc0006dfee8 pc=0x55ca3efda81e
Apr 15 12:02:08.638779 podman[1708]: main.main()
Apr 15 12:02:08.638779 podman[1708]:         /builddir/build/BUILD/containers-podman-49f8da7/_build/src/github.com/containers/podman/cmd/podman/main.go:39 +0x7c fp=0xc0006dff80 sp=0xc0006dff50 pc=0x55ca3efda1dc
Apr 15 12:02:08.638779 podman[1708]: runtime.main()
Apr 15 12:02:08.638779 podman[1708]:         /usr/lib/golang/src/runtime/proc.go:255 +0x227 fp=0xc0006dffe0 sp=0xc0006dff80 pc=0x55ca3de46be7
Apr 15 12:02:08.638779 podman[1708]: runtime.goexit()
Apr 15 12:02:08.638779 podman[1708]:         /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0006dffe8 sp=0xc0006dffe0 pc=0x55ca3de78361
Apr 15 12:02:08.638779 podman[1708]: goroutine 2 [force gc (idle)]:
Apr 15 12:02:08.638779 podman[1708]: runtime.gopark(0x0, 0x0, 0x0, 0x0, 0x0)
Apr 15 12:02:08.638779 podman[1708]:         /usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc000058fb0 sp=0xc000058f90 pc=0x55ca3de46fb6
Apr 15 12:02:08.638779 podman[1708]: runtime.goparkunlock(...)
Apr 15 12:02:08.638779 podman[1708]:         /usr/lib/golang/src/runtime/proc.go:372
Apr 15 12:02:08.638779 podman[1708]: runtime.forcegchelper()
Apr 15 12:02:08.638779 podman[1708]:         /usr/lib/golang/src/runtime/proc.go:306 +0xad fp=0xc000058fe0 sp=0xc000058fb0 pc=0x55ca3de46e4d
Apr 15 12:02:08.638779 podman[1708]: runtime.goexit()
Apr 15 12:02:08.640494 podman[1708]:         /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000058fe8 sp=0xc000058fe0 pc=0x55ca3de78361
Apr 15 12:02:08.640494 podman[1708]: created by runtime.init.8
Apr 15 12:02:08.640494 podman[1708]:         /usr/lib/golang/src/runtime/proc.go:294 +0x25
Apr 15 12:02:08.640494 podman[1708]: goroutine 3 [GC sweep wait]:
Apr 15 12:02:08.640494 podman[1708]: runtime.gopark(0x1, 0x0, 0x0, 0x0, 0x0)
Apr 15 12:02:08.640494 podman[1708]:         /usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc0000597b0 sp=0xc000059790 pc=0x55ca3de46fb6
Apr 15 12:02:08.640494 podman[1708]: runtime.goparkunlock(...)
Apr 15 12:02:08.640494 podman[1708]:         /usr/lib/golang/src/runtime/proc.go:372
Apr 15 12:02:08.640494 podman[1708]: runtime.bgsweep()
Apr 15 12:02:08.640494 podman[1708]:         /usr/lib/golang/src/runtime/mgcsweep.go:182 +0xd8 fp=0xc0000597e0 sp=0xc0000597b0 pc=0x55ca3de316b8
Apr 15 12:02:08.640494 podman[1708]: runtime.goexit()
Apr 15 12:02:08.640494 podman[1708]:         /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0000597e8 sp=0xc0000597e0 pc=0x55ca3de78361
Apr 15 12:02:08.640494 podman[1708]: created by runtime.gcenable
Apr 15 12:02:08.640494 podman[1708]:         /usr/lib/golang/src/runtime/mgc.go:181 +0x55
Apr 15 12:02:08.640494 podman[1708]: goroutine 4 [GC scavenge wait]:
Apr 15 12:02:08.640494 podman[1708]: runtime.gopark(0xc000059fb8, 0x0, 0x0, 0x0, 0x0)
Apr 15 12:02:08.640494 podman[1708]:         /usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc000059f80 sp=0xc000059f60 pc=0x55ca3de46fb6
Apr 15 12:02:08.640494 podman[1708]: runtime.goparkunlock(...)
Apr 15 12:02:08.640494 podman[1708]:         /usr/lib/golang/src/runtime/proc.go:372
Apr 15 12:02:08.640494 podman[1708]: runtime.bgscavenge()
Apr 15 12:02:08.640494 podman[1708]:         /usr/lib/golang/src/runtime/mgcscavenge.go:314 +0x288 fp=0xc000059fe0 sp=0xc000059f80 pc=0x55ca3de2f928
Apr 15 12:02:08.640494 podman[1708]: runtime.goexit()
Apr 15 12:02:08.640494 podman[1708]:         /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000059fe8 sp=0xc000059fe0 pc=0x55ca3de78361
Apr 15 12:02:08.640494 podman[1708]: created by runtime.gcenable
Apr 15 12:02:08.640494 podman[1708]:         /usr/lib/golang/src/runtime/mgc.go:182 +0x65
Apr 15 12:02:08.640494 podman[1708]: goroutine 5 [finalizer wait]:
Apr 15 12:02:08.640494 podman[1708]: runtime.gopark(0x55ca40645060, 0xc000058770, 0x91, 0x3e, 0x55ca405c23a0)
Apr 15 12:02:08.640494 podman[1708]:         /usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc000058630 sp=0xc000058610 pc=0x55ca3de46fb6
Apr 15 12:02:08.640494 podman[1708]: runtime.goparkunlock(...)
Apr 15 12:02:08.640494 podman[1708]:         /usr/lib/golang/src/runtime/proc.go:372
Apr 15 12:02:08.640494 podman[1708]: runtime.runfinq()
Apr 15 12:02:08.640494 podman[1708]:         /usr/lib/golang/src/runtime/mfinal.go:177 +0xb3 fp=0xc0000587e0 sp=0xc000058630 pc=0x55ca3de27193
Apr 15 12:02:08.640494 podman[1708]: runtime.goexit()
Apr 15 12:02:08.640494 podman[1708]:         /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0000587e8 sp=0xc0000587e0 pc=0x55ca3de78361
Apr 15 12:02:08.640494 podman[1708]: created by runtime.createfing
Apr 15 12:02:08.640494 podman[1708]:         /usr/lib/golang/src/runtime/mfinal.go:157 +0x45
Apr 15 12:02:08.640494 podman[1708]: goroutine 8 [GC worker (idle)]:
Apr 15 12:02:08.640494 podman[1708]: runtime.gopark(0x6f324df77, 0xc00037f260, 0x18, 0x14, 0x0)
Apr 15 12:02:08.676630 podman[1708]:         /usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc00005a760 sp=0xc00005a740 pc=0x55ca3de46fb6
Apr 15 12:02:08.676630 podman[1708]: runtime.gcBgMarkWorker()
Apr 15 12:02:08.676630 podman[1708]:         /usr/lib/golang/src/runtime/mgc.go:1200 +0xe5 fp=0xc00005a7e0 sp=0xc00005a760 pc=0x55ca3de29be5
Apr 15 12:02:08.676630 podman[1708]: runtime.goexit()
Apr 15 12:02:08.676630 podman[1708]:         /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00005a7e8 sp=0xc00005a7e0 pc=0x55ca3de78361
Apr 15 12:02:08.676630 podman[1708]: created by runtime.gcBgMarkStartWorkers
Apr 15 12:02:08.676630 podman[1708]:         /usr/lib/golang/src/runtime/mgc.go:1124 +0x25
Apr 15 12:02:08.676630 podman[1708]: goroutine 9 [chan receive]:
Apr 15 12:02:08.676630 podman[1708]: runtime.gopark(0xc000055ed8, 0x55ca3de4cc3b, 0x20, 0x5f, 0x55ca3de63385)
Apr 15 12:02:08.676630 podman[1708]:         /usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc000055ec8 sp=0xc000055ea8 pc=0x55ca3de46fb6
Apr 15 12:02:08.676630 podman[1708]: runtime.chanrecv(0xc00007cfc0, 0xc000055fa0, 0x1)
Apr 15 12:02:08.676630 podman[1708]:         /usr/lib/golang/src/runtime/chan.go:576 +0x56c fp=0xc000055f58 sp=0xc000055ec8 pc=0x55ca3de1506c
Apr 15 12:02:08.676630 podman[1708]: runtime.chanrecv2(0x12a05f200, 0x0)
Apr 15 12:02:08.676630 podman[1708]:         /usr/lib/golang/src/runtime/chan.go:444 +0x18 fp=0xc000055f80 sp=0xc000055f58 pc=0x55ca3de14ad8
Apr 15 12:02:08.676630 podman[1708]: github.com/containers/podman/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x0)
Apr 15 12:02:08.676630 podman[1708]:         /builddir/build/BUILD/containers-podman-49f8da7/_build/src/github.com/containers/podman/vendor/k8s.io/klog/v2/klog.go:1169 +0x6a fp=0xc000055fc8 sp=0xc000055f80 pc=0x55ca3e9da64a
Apr 15 12:02:08.676630 podman[1708]: github.com/containers/podman/vendor/k8s.io/klog/v2.init.0·dwrap·7()
Apr 15 12:02:08.676630 podman[1708]:         /builddir/build/BUILD/containers-podman-49f8da7/_build/src/github.com/containers/podman/vendor/k8s.io/klog/v2/klog.go:420 +0x26 fp=0xc000055fe0 sp=0xc000055fc8 pc=0x55ca3e9d8106
Apr 15 12:02:08.676630 podman[1708]: runtime.goexit()
Apr 15 12:02:08.676630 podman[1708]:         /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000055fe8 sp=0xc000055fe0 pc=0x55ca3de78361
Apr 15 12:02:08.676630 podman[1708]: created by github.com/containers/podman/vendor/k8s.io/klog/v2.init.0
Apr 15 12:02:08.676630 podman[1708]:         /builddir/build/BUILD/containers-podman-49f8da7/_build/src/github.com/containers/podman/vendor/k8s.io/klog/v2/klog.go:420 +0xfb
Apr 15 12:02:08.676630 podman[1708]: goroutine 10 [select, locked to thread]:
Apr 15 12:02:08.676630 podman[1708]: runtime.gopark(0xc0000557a8, 0x2, 0x90, 0x56, 0xc0000557a4)
Apr 15 12:02:08.676630 podman[1708]:         /usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc000055610 sp=0xc0000555f0 pc=0x55ca3de46fb6
Apr 15 12:02:08.676630 podman[1708]: runtime.selectgo(0xc0000557a8, 0xc0000557a0, 0x0, 0x0, 0x0, 0x1)
Apr 15 12:02:08.670284 systemd[1479]: Started D-Bus User Message Bus.
Apr 15 12:02:08.693575 podman[1708]:         /usr/lib/golang/src/runtime/select.go:327 +0x772 fp=0xc000055758 sp=0xc000055610 pc=0x55ca3de56db2
Apr 15 12:02:08.693575 podman[1708]: runtime.ensureSigM.func1()
Apr 15 12:02:08.693575 podman[1708]:         /usr/lib/golang/src/runtime/signal_unix.go:890 +0x1a9 fp=0xc0000557e0 sp=0xc000055758 pc=0x55ca3de70c49
Apr 15 12:02:08.693575 podman[1708]: runtime.goexit()
Apr 15 12:02:08.693575 podman[1708]:         /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0000557e8 sp=0xc0000557e0 pc=0x55ca3de78361
Apr 15 12:02:08.693575 podman[1708]: created by runtime.ensureSigM
Apr 15 12:02:08.693575 podman[1708]:         /usr/lib/golang/src/runtime/signal_unix.go:873 +0xbf
Apr 15 12:02:08.693575 podman[1708]: goroutine 11 [syscall]:
Apr 15 12:02:08.693575 podman[1708]: runtime.notetsleepg(0x0, 0x0)
Apr 15 12:02:08.693575 podman[1708]:         /usr/lib/golang/src/runtime/lock_futex.go:236 +0x34 fp=0xc0000567a0 sp=0xc000056768 pc=0x55ca3de1a5d4
Apr 15 12:02:08.693575 podman[1708]: os/signal.signal_recv()
Apr 15 12:02:08.693575 podman[1708]:         /usr/lib/golang/src/runtime/sigqueue.go:169 +0x98 fp=0xc0000567c0 sp=0xc0000567a0 pc=0x55ca3de74878
Apr 15 12:02:08.693575 podman[1708]: os/signal.loop()
Apr 15 12:02:08.693575 podman[1708]:         /usr/lib/golang/src/os/signal/signal_unix.go:24 +0x19 fp=0xc0000567e0 sp=0xc0000567c0 pc=0x55ca3e4bc5d9
Apr 15 12:02:08.693575 podman[1708]: runtime.goexit()
Apr 15 12:02:08.693575 podman[1708]:         /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0000567e8 sp=0xc0000567e0 pc=0x55ca3de78361
Apr 15 12:02:08.693575 podman[1708]: created by os/signal.Notify.func1.1
Apr 15 12:02:08.693575 podman[1708]:         /usr/lib/golang/src/os/signal/signal.go:151 +0x2c
Apr 15 12:02:08.693575 podman[1708]: goroutine 12 [select]:
Apr 15 12:02:08.693575 podman[1708]: runtime.gopark(0xc000056fb0, 0x2, 0x0, 0x0, 0xc000056ea4)
Apr 15 12:02:08.693575 podman[1708]:         /usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc000069d08 sp=0xc000069ce8 pc=0x55ca3de46fb6
Apr 15 12:02:08.693575 podman[1708]: runtime.selectgo(0xc000069fb0, 0xc000056ea0, 0x0, 0x0, 0x0, 0x1)
Apr 15 12:02:08.693575 podman[1708]:         /usr/lib/golang/src/runtime/select.go:327 +0x772 fp=0xc000069e50 sp=0xc000069d08 pc=0x55ca3de56db2
Apr 15 12:02:08.693575 podman[1708]: github.com/containers/podman/libpod/shutdown.Start.func1()
Apr 15 12:02:08.693575 podman[1708]:         /builddir/build/BUILD/containers-podman-49f8da7/_build/src/github.com/containers/podman/libpod/shutdown/handler.go:47 +0x99 fp=0xc000069fe0 sp=0xc000069e50 pc=0x55ca3ec570b9
Apr 15 12:02:08.693575 podman[1708]: runtime.goexit()
Apr 15 12:02:08.693575 podman[1708]:         /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000069fe8 sp=0xc000069fe0 pc=0x55ca3de78361
Apr 15 12:02:08.693575 podman[1708]: created by github.com/containers/podman/libpod/shutdown.Start
Apr 15 12:02:08.693575 podman[1708]:         /builddir/build/BUILD/containers-podman-49f8da7/_build/src/github.com/containers/podman/libpod/shutdown/handler.go:46 +0xea
Apr 15 12:02:08.693575 podman[1708]: goroutine 14 [sleep]:
Apr 15 12:02:08.693575 podman[1708]: runtime.gopark(0x704559372, 0xc000056e50, 0xe5, 0x54, 0x200)
Apr 15 12:02:08.695719 podman[1708]:         /usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc000056e20 sp=0xc000056e00 pc=0x55ca3de46fb6
Apr 15 12:02:08.695719 podman[1708]: time.Sleep(0x5f5e100)
Apr 15 12:02:08.695719 podman[1708]:         /usr/lib/golang/src/runtime/time.go:193 +0x12e fp=0xc000056e60 sp=0xc000056e20 pc=0x55ca3de7514e
Apr 15 12:02:08.695719 podman[1708]: github.com/containers/podman/libpod.(*Runtime).libimageEvents.func2()
Apr 15 12:02:08.695719 podman[1708]:         /builddir/build/BUILD/containers-podman-49f8da7/_build/src/github.com/containers/podman/libpod/runtime.go:795 +0x59 fp=0xc000056fe0 sp=0xc000056e60 pc=0x55ca3ed387d9
Apr 15 12:02:08.695719 podman[1708]: runtime.goexit()
Apr 15 12:02:08.695719 podman[1708]:         /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000056fe8 sp=0xc000056fe0 pc=0x55ca3de78361
Apr 15 12:02:08.695719 podman[1708]: created by github.com/containers/podman/libpod.(*Runtime).libimageEvents
Apr 15 12:02:08.695719 podman[1708]:         /builddir/build/BUILD/containers-podman-49f8da7/_build/src/github.com/containers/podman/libpod/runtime.go:772 +0x109
Apr 15 12:02:08.695719 podman[1708]: goroutine 15 [runnable]:
Apr 15 12:02:08.695719 podman[1708]: github.com/containers/podman/pkg/servicereaper.Start·dwrap·1()
Apr 15 12:02:08.695719 podman[1708]:         /builddir/build/BUILD/containers-podman-49f8da7/_build/src/github.com/containers/podman/pkg/servicereaper/service.go:35 fp=0xc0000577e0 sp=0xc0000577d8 pc=0x55ca3ec3e540
Apr 15 12:02:08.695719 podman[1708]: runtime.goexit()
Apr 15 12:02:08.695719 podman[1708]:         /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0000577e8 sp=0xc0000577e0 pc=0x55ca3de78361
Apr 15 12:02:08.695719 podman[1708]: created by github.com/containers/podman/pkg/servicereaper.Start
Apr 15 12:02:08.695719 podman[1708]:         /builddir/build/BUILD/containers-podman-49f8da7/_build/src/github.com/containers/podman/pkg/servicereaper/service.go:35 +0xa5
Apr 15 12:02:08.695719 podman[1708]: goroutine 16 [runnable]:
Apr 15 12:02:08.695719 podman[1708]: github.com/containers/podman/pkg/domain/infra.StartWatcher.func1()
Apr 15 12:02:08.695719 podman[1708]:         /builddir/build/BUILD/containers-podman-49f8da7/_build/src/github.com/containers/podman/pkg/domain/infra/runtime_libpod.go:374 fp=0xc000057fe0 sp=0xc000057fd8 pc=0x55ca3eea5ce0
Apr 15 12:02:08.695719 podman[1708]: runtime.goexit()
Apr 15 12:02:08.695719 podman[1708]:         /usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000057fe8 sp=0xc000057fe0 pc=0x55ca3de78361
Apr 15 12:02:08.695719 podman[1708]: created by github.com/containers/podman/pkg/domain/infra.StartWatcher
Apr 15 12:02:08.695719 podman[1708]:         /builddir/build/BUILD/containers-podman-49f8da7/_build/src/github.com/containers/podman/pkg/domain/infra/runtime_libpod.go:374 +0xbe
```

```
$ podman run --rm -ti registry.ci.openshift.org/rhcos-devel/rhel-coreos:4.11
bash-4.4# rpm -q podman
podman-4.0.0-3.module+el8.6.0+14305+6b14f34e.x86_64
bash-4.4# 
```

**Comment by cgwalters** [comment]
It wasn't immediately obvious to me what the failure condition here is, and I am not sure we've seen this happen before, so it may represent a rare race?  I think this is inside a systemd unit, but I didn't dig in to check.

**Comment by Luap99** [comment]
Can you reproduce this somehow or did this happen just once?

**Comment by Luap99** [comment]
Looking at the code we assume the we always have a valid net.Listener returned by activation.Listeners()
https://github.com/coreos/go-systemd/blob/f5f8d59a116b1ca501dd87cdb28f6ce89ccf58dc/activation/listeners.go#L25-L28
However it can return nil if it cannot listen on the fd, i.e. udp connection so we should check that in podman.

**Comment by Luap99** [comment]
https://github.com/containers/podman/pull/13950 should fix the panic but I have no idea how to trigger this condition. Maybe systemd used an invalid fd for podman?

**Comment by cgwalters** [comment]
> Can you reproduce this somehow or did this happen just once?

This is the only time I have seen this happen.  I wouldn't worry too much more about this.
