### ISSUE TITLE
[Linux] Podman static binary for 4.0.2 release have fatal error

### ISSUE THREAD

**Issue by praveenkumar** [containers/podman#14353]
- Download the podman static binary from https://github.com/containers/podman/releases/download/v4.0.2/podman-remote-static.tar.gz and untar it.
- Try to run any command or help

```
$ curl -L -O https://github.com/containers/podman/releases/download/v4.0.2/podman-remote-static.tar.gz
$ tar -xvf podman-remote-static.tar.gz 
$ ./podman-remote-static -h
fatal error: unexpected signal during runtime execution
[signal SIGFPE: floating-point exception code=0x1 addr=0x7f32e474b599 pc=0x7f32e474b599]

runtime stack:
runtime.throw({0x127e3e1?, 0xfba6ea?})
	/usr/lib/golang/src/runtime/panic.go:992 +0x71
runtime.sigpanic()
	/usr/lib/golang/src/runtime/signal_unix.go:802 +0x3a9

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0xf07460, 0xc00061f4d8)
	/usr/lib/golang/src/runtime/cgocall.go:157 +0x5c fp=0xc00061f4b0 sp=0xc00061f478 pc=0x4059dc
os/user._Cfunc_mygetpwnam_r(0xc0000378b8, 0xc000376f30, 0x287abe0, 0x400, 0xc00053c248)
	_cgo_gotypes.go:158 +0x4c fp=0xc00061f4d8 sp=0xc00061f4b0 pc=0x72bb6c
os/user.lookupUser.func1.1({0xc0000378b8, 0xc0001e0ff0?, 0x0?}, 0x1c06480?, 0xc00061f580?, 0x40f927?)
	/usr/lib/golang/src/os/user/cgo_lookup_unix.go:69 +0xbb fp=0xc00061f538 sp=0xc00061f4d8 pc=0x72c45b
os/user.lookupUser.func1()
	/usr/lib/golang/src/os/user/cgo_lookup_unix.go:69 +0x31 fp=0xc00061f578 sp=0xc00061f538 pc=0x72c371
os/user.retryWithBuffer(0xc0001e0ff0, 0xc00061f668)
	/usr/lib/golang/src/os/user/cgo_lookup_unix.go:244 +0x39 fp=0xc00061f5c0 sp=0xc00061f578 pc=0x72d559
os/user.lookupUser({0x1246b60, 0x7})
	/usr/lib/golang/src/os/user/cgo_lookup_unix.go:60 +0x165 fp=0xc00061f6b8 sp=0xc00061f5c0 pc=0x72c145
os/user.Lookup({0x1246b60, 0x7})
	/usr/lib/golang/src/os/user/lookup.go:36 +0x91 fp=0xc00061f6f8 sp=0xc00061f6b8 pc=0x72b711
github.com/containers/storage/pkg/chrootarchive.init.0()
	/home/lsm5/go/src/github.com/containers/podman/vendor/github.com/containers/storage/pkg/chrootarchive/archive.go:23 +0x25 fp=0xc00061f730 sp=0xc00061f6f8 pc=0xa10885
runtime.doInit(0x1bab2e0)
	/usr/lib/golang/src/runtime/proc.go:6222 +0x126 fp=0xc00061f860 sp=0xc00061f730 pc=0x446aa6
runtime.doInit(0x1bac4e0)
	/usr/lib/golang/src/runtime/proc.go:6199 +0x71 fp=0xc00061f990 sp=0xc00061f860 pc=0x4469f1
runtime.doInit(0x1bb08a0)
	/usr/lib/golang/src/runtime/proc.go:6199 +0x71 fp=0xc00061fac0 sp=0xc00061f990 pc=0x4469f1
runtime.doInit(0x1ba9060)
	/usr/lib/golang/src/runtime/proc.go:6199 +0x71 fp=0xc00061fbf0 sp=0xc00061fac0 pc=0x4469f1
runtime.doInit(0x1baa960)
	/usr/lib/golang/src/runtime/proc.go:6199 +0x71 fp=0xc00061fd20 sp=0xc00061fbf0 pc=0x4469f1
runtime.doInit(0x1bad200)
	/usr/lib/golang/src/runtime/proc.go:6199 +0x71 fp=0xc00061fe50 sp=0xc00061fd20 pc=0x4469f1
runtime.doInit(0x1bb1820)
	/usr/lib/golang/src/runtime/proc.go:6199 +0x71 fp=0xc00061ff80 sp=0xc00061fe50 pc=0x4469f1
runtime.main()
	/usr/lib/golang/src/runtime/proc.go:233 +0x1d3 fp=0xc00061ffe0 sp=0xc00061ff80 pc=0x439a53
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00061ffe8 sp=0xc00061ffe0 pc=0x4682a1
```

**Comment by zhangguanzhang** [comment]
link to: https://github.com/containers/podman/issues/13557

**Comment by rhatdan** [comment]
Could you check the 4.1?

**Comment by praveenkumar** [comment]
@rhatdan https://github.com/containers/podman/issues/14201 is issue with 4.1 which have windows binary instead Linux :(

**Comment by praveenkumar** [comment]
Also this is blocker for us to provide podman bundle for crc because we depend on the `podman-remote` binaries (for all platform) to add the system connection and provide direct client binary to the users after using podman bundle.
