### ISSUE TITLE
 ERRO[0000] failed to move the rootless netns slirp4netns process to the systemd user.slice: Process org.freedesktop.systemd1 exited with status 1

### ISSUE THREAD

**Issue by nkartem** [containers/podman#15088]
ERRO[0000] failed to move the rootless netns slirp4netns process to the systemd user.slice: Process org.freedesktop.systemd1 exited with status 1

**Is this a BUG REPORT **

/kind bug

**Description**
I use `dockre-compose.yaml`
```
version: '3.1'
services:   
  asterisk:
    image: asterisk
    container_name: asterisk
    restart: always
    ports:
      - 5022:5022/udp
      - 10000-20000:10000-20000/udp
    command: systemctl start asterisk
```
Then I start:  `podman-compose up -d`
and have  error: 
**ERRO[0000] failed to move the rootless netns slirp4netns process to the systemd user.slice: Process org.freedesktop.systemd1 exited with status 1**

if I **commit** range ports        `- 10000-20000:10000-20000/udp `
This problem **disappears!**

**Output of `podman version`: 
```
podman version 4.0.2
```
**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.24.1
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.0-1.module+el8.6.0+14877+f643d2d6.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: 87b7a9037cbd1d81288bdf2d6705dfda889f7cf9'
  cpus: 2
  distribution:
    distribution: '"rhel"'
    version: "8.5"
  eventLogger: file
  hostname: 303-rra-localhost
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 4.18.0-348.2.1.el8_5.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 677515264
  memTotal: 1877229568
  networkBackend: cni
  ociRuntime:
    name: runc
    package: runc-1.0.2-1.module+el8.5.0+12582+56d94c81.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.2
      spec: 1.0.2-dev
      go: go1.16.7
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-1.module+el8.5.0+12582+56d94c81.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 2154557440
  swapTotal: 2181033984
  uptime: 1h 18m 11.77s (Approximately 0.04 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /home/user/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /opt/podman/var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 4
  runRoot: /opt/podman/run/containers/storage
  volumePath: /opt/podman/var/lib/containers/storage/volumes
version:
  APIVersion: 4.0.2
  Built: 1650363392
  BuiltTime: Tue Apr 19 13:16:32 2022
  GitCommit: ""
  GoVersion: go1.17.7
  OsArch: linux/amd64
  Version: 4.0.2

```

 rpm -q podman

```
 podman-4.0.2-6.module+el8.6.0+14877+f643d2d6.x86_64
```

**AWS, VMware**

**Comment by vrothberg** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
I am not able to reproduce locally.

How have you created the user session?  Through ssh?

Can you reproduce the issue using only podman without `podman-compose`?

**Comment by nkartem** [comment]
Hi, yes I connect through ssh. If I use only podman all work. Some problems with podman-compose v 1.0.3. If I use podman-compose v 0.1.8 (https://pypi.org/project/podman-compose/0.1.8/) all work.  

And also I noticed
I start `podman-compose up -d ` with a range port   '- 10000-20000:10000-20000/udp' in 'docker-compose.yaml' file is not working and  when I press `Ctrl+C` I see:

```
['podman', 'network', 'exists', 'podman_default']
podman run --name=asterisk -d --label io.podman.compose.config-hash=123 --label io.podman.compose.project=podman --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=podman --label com.docker.compose.project.working_dir=/home/podman --label com.docker.compose.project.config_files=docker-compose.yaml --label com.docker.compose.container-number=1 --label com.docker.compose.service=asterisk --net podman_default --network-alias asterisk -p 5022:5022/udp -p 10000-20000:10000-20000/udp --hostname asterisk --restart always name/asterisk systemctl start asterisk
^CTraceback (most recent call last):
  File "/usr/local/bin/podman-compose", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/podman_compose.py", line 1775, in main
    podman_compose.run()
  File "/usr/local/lib/python3.6/site-packages/podman_compose.py", line 1024, in run
    cmd(self, args)
  File "/usr/local/lib/python3.6/site-packages/podman_compose.py", line 1248, in wrapped
    return func(*args, **kw)
  File "/usr/local/lib/python3.6/site-packages/podman_compose.py", line 1416, in compose_up
    subproc = compose.podman.run([], podman_command, podman_args)
  File "/usr/local/lib/python3.6/site-packages/podman_compose.py", line 834, in run
    exit_code = p.wait()
  File "/usr/lib64/python3.6/subprocess.py", line 1477, in wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib64/python3.6/subprocess.py", line 1424, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
```
