### ISSUE TITLE
Cannot allocate memory for etcd

### ISSUE THREAD

**Issue by adzcai** [containers/podman#15123]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I'm unable to run an `etcd` container in a podman VM. It panics with the error message "cannot allocate memory", which I expect is related to podman configuration, although I can't figure out what the issue might be. I'm on a Mac M1 in case that might be related.

**Steps to reproduce the issue:**

1. Install podman with `brew install podman`

2. Init the podman VM with `podman machine init --cpus 4 -m 8192 --rootful --now`

3. Run the ETCD container with `podman run gcr.io/etcd-development/etcd:v3.4.15`

**Describe the results you received:**

```none
[WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
2022-07-30 06:02:18.678429 I | etcdmain: etcd Version: 3.4.15
2022-07-30 06:02:18.680215 I | etcdmain: Git SHA: aa7126864
2022-07-30 06:02:18.680269 I | etcdmain: Go Version: go1.12.17
2022-07-30 06:02:18.680336 I | etcdmain: Go OS/Arch: linux/amd64
2022-07-30 06:02:18.680492 I | etcdmain: setting maximum number of CPUs to 4, total number of available CPUs is 4
2022-07-30 06:02:18.681067 W | etcdmain: no data-dir provided, using default data-dir ./default.etcd
[WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
2022-07-30 06:02:18.700122 I | embed: name = default
2022-07-30 06:02:18.700227 I | embed: data dir = default.etcd
2022-07-30 06:02:18.700299 I | embed: member dir = default.etcd/member
2022-07-30 06:02:18.700384 I | embed: heartbeat = 100ms
2022-07-30 06:02:18.700483 I | embed: election = 1000ms
2022-07-30 06:02:18.700564 I | embed: snapshot count = 100000
2022-07-30 06:02:18.701358 I | embed: advertise client URLs = http://localhost:2379
2022-07-30 06:02:18.708263 C | mvcc/backend: cannot open database at default.etcd/member/snap/db (cannot allocate memory)
panic: cannot open database at default.etcd/member/snap/db (cannot allocate memory)

goroutine 138 [running]:
github.com/coreos/pkg/capnslog.(*PackageLogger).Panicf(0xc0001343e0, 0x10bb84a, 0x1f, 0xc00011b728, 0x2, 0x2)
	/root/go/pkg/mod/github.com/coreos/pkg@v0.0.0-20160727233714-3ac0863d7acf/capnslog/pkg_logger.go:75 +0x135
go.etcd.io/etcd/mvcc/backend.newBackend(0xc000274360, 0x1b, 0x5f5e100, 0x2710, 0x109eb1b, 0x5, 0x280000000, 0x0, 0x0, 0xc00003bf10)
	/tmp/etcd-release-3.4.15/etcd/release/etcd/mvcc/backend/backend.go:163 +0x741
go.etcd.io/etcd/mvcc/backend.New(...)
	/tmp/etcd-release-3.4.15/etcd/release/etcd/mvcc/backend/backend.go:139
go.etcd.io/etcd/etcdserver.newBackend(0x10a0d51, 0x7, 0x0, 0x0, 0x0, 0x0, 0xc000124b00, 0x1, 0x1, 0xc000124980, ...)
	/tmp/etcd-release-3.4.15/etcd/release/etcd/etcdserver/backend.go:53 +0x1c8
go.etcd.io/etcd/etcdserver.openBackend.func1(0xc000238120, 0xc00014cb00)
	/tmp/etcd-release-3.4.15/etcd/release/etcd/etcdserver/backend.go:74 +0x78
created by go.etcd.io/etcd/etcdserver.openBackend
	/tmp/etcd-release-3.4.15/etcd/release/etcd/etcdserver/backend.go:73 +0x109
```

**Describe the results you expected:**

If I run the container on Docker Desktop for Mac, the container successfully runs:

```none
~ $ docker run gcr.io/etcd-development/etcd:v3.4.15
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
[WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
2022-07-30 06:03:46.283413 I | etcdmain: etcd Version: 3.4.15
2022-07-30 06:03:46.285190 I | etcdmain: Git SHA: aa7126864
2022-07-30 06:03:46.285290 I | etcdmain: Go Version: go1.12.17
2022-07-30 06:03:46.285349 I | etcdmain: Go OS/Arch: linux/amd64
2022-07-30 06:03:46.285415 I | etcdmain: setting maximum number of CPUs to 4, total number of available CPUs is 4
2022-07-30 06:03:46.286046 W | etcdmain: no data-dir provided, using default data-dir ./default.etcd
[WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
2022-07-30 06:03:46.304640 I | embed: name = default
2022-07-30 06:03:46.304745 I | embed: data dir = default.etcd
2022-07-30 06:03:46.304811 I | embed: member dir = default.etcd/member
2022-07-30 06:03:46.304968 I | embed: heartbeat = 100ms
2022-07-30 06:03:46.305367 I | embed: election = 1000ms
2022-07-30 06:03:46.305575 I | embed: snapshot count = 100000
2022-07-30 06:03:46.306297 I | embed: advertise client URLs = http://localhost:2379
2022-07-30 06:03:46.426428 I | etcdserver: starting member 8e9e05c52164694d in cluster cdf818194e3a8c32
raft2022/07/30 06:03:46 INFO: 8e9e05c52164694d switched to configuration voters=()
raft2022/07/30 06:03:46 INFO: 8e9e05c52164694d became follower at term 0
raft2022/07/30 06:03:46 INFO: newRaft 8e9e05c52164694d [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
raft2022/07/30 06:03:46 INFO: 8e9e05c52164694d became follower at term 1
raft2022/07/30 06:03:46 INFO: 8e9e05c52164694d switched to configuration voters=(10276657743932975437)
2022-07-30 06:03:46.466762 W | auth: simple token is not cryptographically signed
2022-07-30 06:03:46.480353 I | etcdserver: starting server... [version: 3.4.15, cluster version: to_be_decided]
2022-07-30 06:03:46.482549 I | etcdserver: 8e9e05c52164694d as single-node; fast-forwarding 9 ticks (election ticks 10)
raft2022/07/30 06:03:46 INFO: 8e9e05c52164694d switched to configuration voters=(10276657743932975437)
2022-07-30 06:03:46.512394 I | etcdserver/membership: added member 8e9e05c52164694d [http://localhost:2380] to cluster cdf818194e3a8c32
2022-07-30 06:03:46.522324 I | embed: listening for peers on 127.0.0.1:2380
raft2022/07/30 06:03:46 INFO: 8e9e05c52164694d is starting a new election at term 1
raft2022/07/30 06:03:46 INFO: 8e9e05c52164694d became candidate at term 2
raft2022/07/30 06:03:46 INFO: 8e9e05c52164694d received MsgVoteResp from 8e9e05c52164694d at term 2
raft2022/07/30 06:03:46 INFO: 8e9e05c52164694d became leader at term 2
raft2022/07/30 06:03:46 INFO: raft.node: 8e9e05c52164694d elected leader 8e9e05c52164694d at term 2
2022-07-30 06:03:46.980975 I | etcdserver: setting up the initial cluster version to 3.4
2022-07-30 06:03:46.991708 I | embed: ready to serve client requests
2022-07-30 06:03:46.992488 N | etcdserver/membership: set the initial cluster version to 3.4
2022-07-30 06:03:46.995453 I | etcdserver: published {Name:default ClientURLs:[http://localhost:2379]} to cluster cdf818194e3a8c32
2022-07-30 06:03:47.000596 I | etcdserver/api: enabled capabilities for version 3.4
2022-07-30 06:03:47.034144 N | embed: serving insecure client requests on 127.0.0.1:2379, this is strongly discouraged!
```

**Additional information you deem important (e.g. issue happens only occasionally):**

I've tried reinstalling podman, and also running `/opt/homebrew/Cellar/podman/4.1.1/bin/podman-mac-helper install`, but neither resolved the issue. Running `ulimit -v` inside the VM as per [this issue](https://github-com.translate.goog/apache/servicecomb-service-center/issues/383?_x_tr_sl=zh-CN&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp) shows

```
real-time non-blocking time  (microseconds, -R) unlimited
core file size              (blocks, -c) unlimited
data seg size               (kbytes, -d) unlimited
scheduling priority                 (-e) 0
file size                   (blocks, -f) unlimited
pending signals                     (-i) 31081
max locked memory           (kbytes, -l) 8192
max memory size             (kbytes, -m) unlimited
open files                          (-n) 1024
pipe size                (512 bytes, -p) 8
POSIX message queues         (bytes, -q) 819200
real-time priority                  (-r) 0
stack size                  (kbytes, -s) 8192
cpu time                   (seconds, -t) unlimited
max user processes                  (-u) 31081
virtual memory              (kbytes, -v) unlimited
file locks                          (-x) unlimited
```

**Output of `podman version`:**

```
podman version 4.1.1
```

**Output of `podman info --debug`:**

```
host:
  arch: arm64
  buildahVersion: 1.26.1
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - pids
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.0-2.fc36.aarch64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: '
  cpuUtilization:
    idlePercent: 88.91
    systemPercent: 8.24
    userPercent: 2.85
  cpus: 4
  distribution:
    distribution: fedora
    variant: coreos
    version: "36"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.18.13-200.fc36.aarch64
  linkmode: dynamic
  logDriver: journald
  memFree: 7518097408
  memTotal: 8303304704
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.4.5-1.fc36.aarch64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.5
      commit: c381048530aa750495cf502ddb7181f2ded5b400
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.aarch64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 1m 12.08s
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 106825756672
  graphRootUsed: 2245263360
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.1.1
  Built: 1655914710
  BuiltTime: Wed Jun 22 10:18:30 2022
  GitCommit: ""
  GoVersion: go1.18.3
  Os: linux
  OsArch: linux/arm64
  Version: 4.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
$ brew list podman
/opt/homebrew/Cellar/podman/4.1.1/bin/podman
/opt/homebrew/Cellar/podman/4.1.1/bin/podman-mac-helper
/opt/homebrew/Cellar/podman/4.1.1/bin/podman-remote
/opt/homebrew/Cellar/podman/4.1.1/etc/bash_completion.d/podman
/opt/homebrew/Cellar/podman/4.1.1/libexec/gvproxy
/opt/homebrew/Cellar/podman/4.1.1/share/fish/vendor_completions.d/podman.fish
/opt/homebrew/Cellar/podman/4.1.1/share/man/ (163 files)
/opt/homebrew/Cellar/podman/4.1.1/share/zsh/site-functions/_podman
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

**Yes**

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical, Mac M1, 16 GB memory

**Comment by rhatdan** [comment]
This looks like the container is running out of memory within the VM. Does etcd require a certain amount of memory to run?

@vrothberg @giuseppe thoughts?

**Comment by adzcai** [comment]
The same error happens if I `podman machine set -m 10240 && podman machine start`.

**Comment by mheon** [comment]
Any chance you can try the container with `--privileged`? I wonder if it's trying some sort of memory-manipulation syscall that's blocked by Seccomp and/or capabilities

**Comment by adzcai** [comment]
Unfortunately it still returns the same error:
```
~ $ podman run --privileged gcr.io/etcd-development/etcd:latest
2022-07-31 18:32:15.830618 I | etcdmain: etcd Version: 3.3.12
2022-07-31 18:32:15.833762 I | etcdmain: Git SHA: d57e8b8
2022-07-31 18:32:15.833817 I | etcdmain: Go Version: go1.10.8
2022-07-31 18:32:15.833859 I | etcdmain: Go OS/Arch: linux/amd64
2022-07-31 18:32:15.833919 I | etcdmain: setting maximum number of CPUs to 4, total number of available CPUs is 4
2022-07-31 18:32:15.834553 W | etcdmain: no data-dir provided, using default data-dir ./default.etcd
2022-07-31 18:32:15.847864 I | embed: listening for peers on http://localhost:2380
2022-07-31 18:32:15.849203 I | embed: listening for client requests on localhost:2379
2022-07-31 18:32:15.858635 C | mvcc/backend: cannot open database at default.etcd/member/snap/db (cannot allocate memory)
panic: cannot open database at default.etcd/member/snap/db (cannot allocate memory)
```

**Comment by giuseppe** [comment]
what is the ulimit for virtual memory (`ulimit -v`)?

**Comment by josephbharrison** [comment]
This appears to be an etcd + Apple Silicon bug, as this problem exists with docker and colima/docker on M1 Mac OS X. 

For other M1 Mac users, here's a `docker` work-around for Apple silicon, which can hopefully be transposed to `podman` (though I've not tested with `podman`):

```bash
export DOCKER_DEFAULT_PLATFORM=linux/arm64/v8
docker run --env ETCD_UNSUPPORTED_ARCH=arm64 gcr.io/etcd-development/etcd:v3.4.20-arm64
```
... and `docker compose` equivalent (with $PROJECT and volume mount):

```bash
export PROJECT=my-project
docker compose -p $PROJECT up
```

```yaml
# docker-compose.yaml
version: '3.1'

services:
  etcd:
    image: gcr.io/etcd-development/etcd:v3.4.20-arm64
    hostname: etcd.${PROJECT}
    container_name: etcd.${PROJECT}
    platform: linux/arm64/v8
    volumes:
      - ~/data/${PROJECT}/etcd:/default.etcd:rw
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_UNSUPPORTED_ARCH=arm64

networks:
  default:
    name: ${PROJECT}   
```

**Comment by giuseppe** [comment]
thanks for the recipe!

I am closing this issue since there is nothing Podman can do about it

**Comment by josephbharrison** [comment]
yeah, this looks like a compatibility issue with etcd amd64 docker and Apple silicon (and def not specific to podman) -- but happily in looking for a fix I came across this post and learned about podman ... looks cool! :)

**Comment by kovyrin** [comment]
Thank you! Just tested the following it it worked perfectly on my M1 Pro:

```
podman run -it --rm --env ETCD_UNSUPPORTED_ARCH=arm64 gcr.io/etcd-development/etcd:v3.4.20-arm64
```
