### ISSUE TITLE
make: *** [gvproxy] Error 1

### ISSUE THREAD

**Issue by Conrad9602** [containers/podman#15484]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

/kind feature

**Description**

When I used Homebrew to install Podman, it keeps reporting this error for any versions except @4.2.0. My brew version is 3.5.10-49-gb2ddb34

```

==> Installing xzhu1/local-podman/podman@4.0.3
==> make podman-remote-darwin
==> make gvproxy
Last 15 lines from /Users/xzhu1/Library/Logs/Homebrew/podman@4.0.3/02.make:

make
gvproxy

go build -ldflags '-s -w' -o bin/gvproxy ./cmd/gvproxy
package github.com/containers/gvisor-tap-vsock/cmd/gvproxy
        imports github.com/containers/gvisor-tap-vsock/pkg/virtualnetwork
        imports github.com/containers/gvisor-tap-vsock/pkg/services/dhcp
        imports github.com/containers/gvisor-tap-vsock/pkg/tap
        imports gvisor.dev/gvisor/pkg/tcpip
        imports gvisor.dev/gvisor/pkg/atomicbitops
        imports gvisor.dev/gvisor/pkg/state
        imports gvisor.dev/gvisor/pkg/state/wire
        imports gvisor.dev/gvisor/pkg/gohacks: build constraints exclude all Go files in /private/tmp/podmanA4.0.3--gvproxy-20220825-34716-1i3xlgb/gvisor-tap-vsock-0.3.0/vendor/gvisor.dev/gvisor/pkg/gohacks
make: *** [gvproxy] Error 1

Do not report this issue to Homebrew/brew or Homebrew/core!

/usr/local/Homebrew/Library/Homebrew/utils/github/api.rb:303:in `raise_error': Validation Failed: [{"message"=>"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.", "resource"=>"Search", "field"=>"q", "code"=>"invalid"}] (GitHub::API::ValidationFailedError)
        from /usr/local/Homebrew/Library/Homebrew/utils/github/api.rb:233:in `open_rest'
        from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:173:in `search'
        from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:34:in `search_issues'
        from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:67:in `issues_for_formula'
        from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:498:in `fetch_issues'
        from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:493:in `issues'
        from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:549:in `dump'
        from /usr/local/Homebrew/Library/Homebrew/brew.rb:148:in `rescue in <main>'
        from /usr/local/Homebrew/Library/Homebrew/brew.rb:136:in `<main>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2518:in `block in system': Failed executing: make gvproxy (BuildError)

```

**Steps to reproduce the issue:**

1.

2.

3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

podman version 4.2.0

**Output of `podman info`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
@ashley-cui PTAL

**Comment by ashley-cui** [comment]
This looks like a non-standard install, as the core homebrew should only have the latest version of podman (4.0.2) in it. What does your install formula look like?

**Comment by Conrad9602** [comment]
```
class PodmanAT403 < Formula
  desc "Tool for managing OCI containers and pods"
  homepage "https://podman.io/"
  license "Apache-2.0"

  stable do
    url "https://github.com/containers/podman/archive/v4.0.3.tar.gz"
    sha256 "e3b53fc9142d4f2dc085f17a377d92ffb8bfe7756c4f47b8128b38bcc3540cbc"
    resource "gvproxy" do
      url "https://github.com/containers/gvisor-tap-vsock/archive/v0.3.0.tar.gz"
      sha256 "6ca454ae73fce3574fa2b615e6c923ee526064d0dc2bcf8dab3cca57e9678035"
    end
  end

  head do
    url "https://github.com/containers/podman.git", branch: "main"

    resource "gvproxy" do
      url "https://github.com/containers/gvisor-tap-vsock.git", branch: "main"
    end
  end

  depends_on "go" => :build
  depends_on "go-md2man" => :build
  depends_on "qemu"

  def install
    ENV["CGO_ENABLED"] = "1"
    os = OS.kernel_name.downcase

    inreplace "vendor/github.com/containers/common/pkg/config/config_#{os}.go",
              "/usr/local/libexec/podman",
              libexec

    system "make", "podman-remote-#{os}"
    if OS.mac?
      bin.install "bin/#{os}/podman" => "podman-remote"
      bin.install_symlink bin/"podman-remote" => "podman"
      bin.install "bin/#{os}/podman-mac-helper" => "podman-mac-helper"
    else
      bin.install "bin/podman-remote"
    end

    resource("gvproxy").stage do
      system "make", "gvproxy"
      libexec.install "bin/gvproxy"
    end

    system "make", "podman-remote-#{os}-docs"
    man1.install Dir["docs/build/remote/#{os}/*.1"]

    bash_completion.install "completions/bash/podman"
    zsh_completion.install "completions/zsh/_podman"
    fish_completion.install "completions/fish/podman.fish"
  end

  test do
    assert_match "podman-remote version #{version}", shell_output("#{bin}/podman-remote -v")
    assert_match(/Cannot connect to Podman/i, shell_output("#{bin}/podman-remote info 2>&1", 125))

    machineinit_output = shell_output("podman-remote machine init --image-path fake-testi123 fake-testvm 2>&1", 125)
    assert_match "Error: open fake-testi123: no such file or directory", machineinit_output
  end
end

```
