### ISSUE TITLE
Setting sigstore to a normal path (without file://) causes a segmentation fault SIGSEGV

### ISSUE THREAD

**Issue by faern** [containers/podman#16301]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

If I configure the `sigstore` to be a path without `file://`, podman segfaults.

**Steps to reproduce the issue:**

1. Set up podman to read image signatures from a regular filesystem path. `~/.config/containers/registries.d/default.yaml`:
    ```yml
    default-docker:
      sigstore: /home/faern/podman-sigstore/  # <- causes the SIGSEGV
      # sigstore: file:///home/faern/podman-sigstore/ # <- this works
    ```

2. Pull any image: `podman pull alpine`

**Describe the results you received:**

```
$ podman pull alpine
....
Resolved "alpine" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull docker.io/library/alpine:latest...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x556b6c054083]

goroutine 1 [running]:
panic({0x556b6d35fca0, 0x556b6df97b80})
	/usr/lib/golang/src/runtime/panic.go:941 +0x397 fp=0xc000598480 sp=0xc0005983c0 pc=0x556b6bf5d9d7
runtime.panicmem(...)
	/usr/lib/golang/src/runtime/panic.go:220
runtime.sigpanic()
	/usr/lib/golang/src/runtime/signal_unix.go:818 +0x31d fp=0xc0005984d0 sp=0xc000598480 pc=0x556b6bf7449d
net/url.(*URL).ResolveReference(0x0, 0xc000c5ab40)
	/usr/lib/golang/src/net/url/url.go:1071 +0x83 fp=0xc000598518 sp=0xc0005984d0 pc=0x556b6c054083
net/url.(*URL).Parse(0xc000abe590?, {0xc000a33520?, 0xc000a38ec0?})
	/usr/lib/golang/src/net/url/url.go:1059 +0x47 fp=0xc000598540 sp=0xc000598518 pc=0x556b6c053fc7
github.com/containers/podman/vendor/github.com/containers/image/v5/docker.(*registryConfiguration).lookasideStorageBaseURL(0x556b6c2d8e6c?, {{0x556b6d553260?, 0xc000a38ec0?}}, 0xe0?)
	/builddir/build/BUILD/podman-4.2.1/_build/src/github.com/containers/podman/vendor/github.com/containers/image/v5/docker/registries_d.go:168 +0x68 fp=0xc000598640 sp=0xc000598540 pc=0x556b6c525008
github.com/containers/podman/vendor/github.com/containers/image/v5/docker.newDockerClientFromRef(0xc000c7f0e0, {{0x556b6d553260?, 0xc000a38ec0?}}, 0x0?, 0x0?, {0x556b6cf103a7, 0x4})
	/builddir/build/BUILD/podman-4.2.1/_build/src/github.com/containers/podman/vendor/github.com/containers/image/v5/docker/docker_client.go:223 +0x12e fp=0xc000598728 sp=0xc000598640 pc=0x556b6c50cece
github.com/containers/podman/vendor/github.com/containers/image/v5/docker.newImageSourceAttempt({0x556b6d557370, 0xc000be4a50}, 0xc000c7f0e0, {{0x556b6d553260?, 0xc000a38ce0?}}, {{{0xc000a33540, 0x1f}, 0x0, {0x0, 0x0}}, ...}, ...)
	/builddir/build/BUILD/podman-4.2.1/_build/src/github.com/containers/podman/vendor/github.com/containers/image/v5/docker/docker_image_src.go:134 +0x1f7 fp=0xc0005987c0 sp=0xc000598728 pc=0x556b6c51e217
github.com/containers/podman/vendor/github.com/containers/image/v5/docker.newImageSource({0x556b6d557370, 0xc000be4a50}, 0xc000c7f0e0, {{0x556b6d553260?, 0xc000a38ce0?}})
	/builddir/build/BUILD/podman-4.2.1/_build/src/github.com/containers/podman/vendor/github.com/containers/image/v5/docker/docker_image_src.go:87 +0x719 fp=0xc000598a00 sp=0xc0005987c0 pc=0x556b6c51de19
github.com/containers/podman/vendor/github.com/containers/image/v5/docker.dockerReference.NewImageSource(...)
	/builddir/build/BUILD/podman-4.2.1/_build/src/github.com/containers/podman/vendor/github.com/containers/image/v5/docker/docker_transport.go:144
github.com/containers/podman/vendor/github.com/containers/image/v5/docker.(*dockerReference).NewImageSource(0x556b6d55efb0?, {0x556b6d557370?, 0xc000be4a50?}, 0xc000598ac8?)
	<autogenerated>:1 +0x45 fp=0xc000598a38 sp=0xc000598a00 pc=0x556b6c5273a5
github.com/containers/podman/vendor/github.com/containers/image/v5/copy.Image({0x556b6d557370, 0xc000be4a50}, 0x4f?, {0x556b6d55ca20, 0xc00063b5c0}, {0x556b6d55d1a0?, 0xc000abe510?}, 0x556b6bf32f25?)
	/builddir/build/BUILD/podman-4.2.1/_build/src/github.com/containers/podman/vendor/github.com/containers/image/v5/copy/copy.go:222 +0x3f0 fp=0xc000598df0 sp=0xc000598a38 pc=0x556b6c8b4110
github.com/containers/podman/vendor/github.com/containers/common/libimage.(*copier).copy.func1()
	/builddir/build/BUILD/podman-4.2.1/_build/src/github.com/containers/podman/vendor/github.com/containers/common/libimage/copier.go:378 +0xfd fp=0xc000598f40 sp=0xc000598df0 pc=0x556b6c9b30fd
github.com/containers/podman/vendor/github.com/containers/common/pkg/retry.IfNecessary({0x556b6d557370, 0xc000be4a50}, 0xc0005990c8, 0xc000360af8)
	/builddir/build/BUILD/podman-4.2.1/_build/src/github.com/containers/podman/vendor/github.com/containers/common/pkg/retry/retry.go:34 +0x4e fp=0xc000599020 sp=0xc000598f40 pc=0x556b6c98d8ae
github.com/containers/podman/vendor/github.com/containers/common/libimage.(*copier).copy(0xc000360a00, {0x556b6d557370, 0xc000be4a50}, {0x556b6d55d1a0, 0xc000abe510}, {0x556b6d55ca20, 0xc00063b5c0})
	/builddir/build/BUILD/podman-4.2.1/_build/src/github.com/containers/podman/vendor/github.com/containers/common/libimage/copier.go:384 +0x395 fp=0xc000599130 sp=0xc000599020 pc=0x556b6c9b2ef5
github.com/containers/podman/vendor/github.com/containers/common/libimage.(*Runtime).copySingleImageFromRegistry(0xc000b50400, {0x556b6d557370, 0xc000be4a50}, {0x7ffe7b0dc993, 0x6}, 0x0, 0xc000599a38)
	/builddir/build/BUILD/podman-4.2.1/_build/src/github.com/containers/podman/vendor/github.com/containers/common/libimage/pull.go:627 +0x1575 fp=0xc000599538 sp=0xc000599130 pc=0x556b6c9cca15
github.com/containers/podman/vendor/github.com/containers/common/libimage.(*Runtime).copyFromRegistry(0xc000b50400, {0x556b6d557370, 0xc000be4a50}, {0x556b6d55d1a0, 0xc000c30c00}, {0x7ffe7b0dc993?, 0x556b6c04cdeb?}, 0x0, 0xc000599a38)
	/builddir/build/BUILD/podman-4.2.1/_build/src/github.com/containers/podman/vendor/github.com/containers/common/libimage/pull.go:382 +0x225 fp=0xc000599650 sp=0xc000599538 pc=0x556b6c9cac45
github.com/containers/podman/vendor/github.com/containers/common/libimage.(*Runtime).Pull(0xc000b50400, {0x556b6d557370, 0xc000be4a50}, {0x7ffe7b0dc993, 0x6}, 0x0, 0xc000599a38)
	/builddir/build/BUILD/podman-4.2.1/_build/src/github.com/containers/podman/vendor/github.com/containers/common/libimage/pull.go:147 +0xa65 fp=0xc0005999e8 sp=0xc000599650 pc=0x556b6c9c8925
github.com/containers/podman/pkg/domain/infra/abi.(*ImageEngine).Pull(0x0?, {0x556b6d557370?, 0xc000be4a50?}, {0x7ffe7b0dc993?, 0x0?}, {0x0, {0x0, 0x0}, {0x0, 0x0}, ...})
	/builddir/build/BUILD/podman-4.2.1/_build/src/github.com/containers/podman/pkg/domain/infra/abi/images.go:244 +0x1d9 fp=0xc000599bf8 sp=0xc0005999e8 pc=0x556b6cd4ccf9
github.com/containers/podman/cmd/podman/images.imagePull(0x556b6dfb9ca0?, {0xc000591390, 0x1, 0x1?})
	/builddir/build/BUILD/podman-4.2.1/_build/src/github.com/containers/podman/cmd/podman/images/pull.go:162 +0x388 fp=0xc000599d58 sp=0xc000599bf8 pc=0x556b6ce14148
github.com/containers/podman/vendor/github.com/spf13/cobra.(*Command).execute(0x556b6dfb9ca0, {0xc00003c1a0, 0x1, 0x1})
	/builddir/build/BUILD/podman-4.2.1/_build/src/github.com/containers/podman/vendor/github.com/spf13/cobra/command.go:872 +0x694 fp=0xc000599e30 sp=0xc000599d58 pc=0x556b6c57bb74
github.com/containers/podman/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x556b6dfcbea0)
	/builddir/build/BUILD/podman-4.2.1/_build/src/github.com/containers/podman/vendor/github.com/spf13/cobra/command.go:990 +0x3b4 fp=0xc000599ee8 sp=0xc000599e30 pc=0x556b6c57c1f4
github.com/containers/podman/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/builddir/build/BUILD/podman-4.2.1/_build/src/github.com/containers/podman/vendor/github.com/spf13/cobra/command.go:918
github.com/containers/podman/vendor/github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/builddir/build/BUILD/podman-4.2.1/_build/src/github.com/containers/podman/vendor/github.com/spf13/cobra/command.go:911
main.Execute()
	/builddir/build/BUILD/podman-4.2.1/_build/src/github.com/containers/podman/cmd/podman/root.go:99 +0xc5 fp=0xc000599f50 sp=0xc000599ee8 pc=0x556b6cf02065
main.main()
	/builddir/build/BUILD/podman-4.2.1/_build/src/github.com/containers/podman/cmd/podman/main.go:40 +0x7c fp=0xc000599f80 sp=0xc000599f50 pc=0x556b6cf0151c
runtime.main()
	/usr/lib/golang/src/runtime/proc.go:250 +0x213 fp=0xc000599fe0 sp=0xc000599f80 pc=0x556b6bf60553
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000599fe8 sp=0xc000599fe0 pc=0x556b6bf91c01

....
```

I'm not including the full stacktrace. The remaining goroutines seems to be mostly GC.

**Describe the results you expected:**

Since podman can read the sigstore from file, I would expect it to be able to take regular file paths. But even if the `file://` prefix is a hard requirement, the command should not crash in this way, rather print that the configuration is invalid.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.2.1
API Version:  4.2.1
Go Version:   go1.18.5
Built:        Wed Sep  7 21:58:19 2022
OS/Arch:      linux/amd64
```

**Output of `podman info`:**

```
host:
  arch: amd64
  buildahVersion: 1.27.0
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.0-2.fc36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: '
  cpuUtilization:
    idlePercent: 95.24
    systemPercent: 1.21
    userPercent: 3.55
  cpus: 8
  distribution:
    distribution: fedora
    variant: workstation
    version: "36"
  eventLogger: journald
  hostname: removed
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.18.16-200.fc36.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 354779136
  memTotal: 33347612672
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.5-1.fc36.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.5
      commit: 54ebb8ca8bf7e6ddae2eb919f5b82d1d96863dea
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.x86_64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 126976
  swapTotal: 8589930496
  uptime: 1205h 33m 47.00s (Approximately 50.21 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/faern/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/faern/.local/share/containers/storage
  graphRootAllocated: 1022487429120
  graphRootUsed: 275545317376
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 78
  runRoot: /run/user/1000/containers
  volumePath: /home/faern/.local/share/containers/storage/volumes
version:
  APIVersion: 4.2.1
  Built: 1662580699
  BuiltTime: Wed Sep  7 21:58:19 2022
  GitCommit: ""
  GoVersion: go1.18.5
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

```
$ rpm -q podman
podman-4.2.1-2.fc36.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Tested latest version: No. But I can't find any reported issue or posted PR on this issue. So I would be surprised if the bug was not still there in 4.3.0
Checked the troubleshooting guide: Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

My physical machine, running Fedora 36

**Comment by vrothberg** [comment]
Thanks for reaching out!

@mtrmac FYI

**Comment by mtrmac** [comment]
Oh, wow. `net/url.Parse` vs. `localVariableNamedURL.Parse`.

**Comment by mtrmac** [comment]
Thanks for reporting this! It will be fixed by https://github.com/containers/image/pull/1704.
