### ISSUE TITLE
podman [COMMAND] panic: invalid page type: 23: 10

### ISSUE THREAD

**Issue by shine-fire** [containers/podman#16587]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug
（maybe）

**Description**

**Steps to reproduce the issue:**

1. I reboot my RHEL 8.7 OS;

2. I found my software cannot use after OS reboot , then I found podman has problem when I use "podman ps" command to check my container. It cannot output my all containers.

**Describe the results you received:**
"podman ps" output error, cannot output my container.

**Describe the results you expected:**
"podman ps" can output my container

**Additional [information](url) you deem important (e.g. issue happens only occasionally):**
I use podman command output error:
```bash
~]# podman
Manage pods, containers and images

Usage:
  podman [options] [command]
...skipping...

Error: missing command 'podman COMMAND'
```

**Output of `podman version`:**
**Output of `podman info`:**

Cannot output of `podman version` or other COMMAND now. It will output same error messages.
like this: 
```
panic: invalid page type: 23: 10

goroutine 1 [running]:
panic({0x560db1290ec0, 0xc000d87910})
	/usr/lib/golang/src/runtime/panic.go:941 +0x397 fp=0xc0006b6718 sp=0xc0006b6658 pc=0x560dafcf57d7
github.com/containers/podman/vendor/go.etcd.io/bbolt.(*Cursor).search(0xc0006b6840, {0x560db1fa6d70, 0x5, 0x5}, 0xc0006b67f8?)
	/builddir/build/BUILD/containers-podman-35c0df3/_build/src/github.com/containers/podman/vendor/go.etcd.io/bbolt/cursor.go:250 +0x285 fp=0xc0006b67b0 sp=0xc0006b6718 pc=0x560db05e2805
github.com/containers/podman/vendor/go.etcd.io/bbolt.(*Cursor).seek(0xc0006b6840, {0x560db1fa6d70?, 0x10?, 0x10?})
	/builddir/build/BUILD/containers-podman-35c0df3/_build/src/github.com/containers/podman/vendor/go.etcd.io/bbolt/cursor.go:159 +0x48 fp=0xc0006b6808 sp=0xc0006b67b0 pc=0x560db05e2028
github.com/containers/podman/vendor/go.etcd.io/bbolt.(*Bucket).Get(0xc000d57c40, {0x560db1fa6d70, 0x5, 0x5})
	/builddir/build/BUILD/containers-podman-35c0df3/_build/src/github.com/containers/podman/vendor/go.etcd.io/bbolt/bucket.go:262 +0x85 fp=0xc0006b6870 sp=0xc0006b6808 pc=0x560db05df845
github.com/containers/podman/libpod.(*BoltState).Refresh.func1.4({0x7ff88445bb20, 0x40, 0x40?}, {0xc00012a558?, 0x560db1fa7e10?, 0x14?})
	/builddir/build/BUILD/containers-podman-35c0df3/_build/src/github.com/containers/podman/libpod/boltdb_state.go:378 +0x76 fp=0xc0006b6930 sp=0xc0006b6870 pc=0x560db098fb96
github.com/containers/podman/vendor/go.etcd.io/bbolt.(*Bucket).ForEach(0xc00035b900, 0xc0006b6b88)
	/builddir/build/BUILD/containers-podman-35c0df3/_build/src/github.com/containers/podman/vendor/go.etcd.io/bbolt/bucket.go:390 +0xa4 fp=0xc0006b6990 sp=0xc0006b6930 pc=0x560db05dffc4
github.com/containers/podman/libpod.(*BoltState).Refresh.func1(0xc00023a090?)
	/builddir/build/BUILD/containers-podman-35c0df3/_build/src/github.com/containers/podman/libpod/boltdb_state.go:371 +0x492 fp=0xc0006b6cc8 sp=0xc0006b6990 pc=0x560db098f252
github.com/containers/podman/vendor/go.etcd.io/bbolt.(*DB).Update(0xc0000a60a0?, 0x560db14f9450)
	/builddir/build/BUILD/containers-podman-35c0df3/_build/src/github.com/containers/podman/vendor/go.etcd.io/bbolt/db.go:741 +0x82 fp=0xc0006b6d30 sp=0xc0006b6cc8 pc=0x560db05e5862
github.com/containers/podman/libpod.(*BoltState).Refresh(0xc0000a60a0)
	/builddir/build/BUILD/containers-podman-35c0df3/_build/src/github.com/containers/podman/libpod/boltdb_state.go:170 +0xab fp=0xc0006b6d88 sp=0xc0006b6d30 pc=0x560db099126b
github.com/containers/podman/libpod.(*Runtime).refresh(0xc00003fa40, {0xc00097cab0, 0x11})
	/builddir/build/BUILD/containers-podman-35c0df3/_build/src/github.com/containers/podman/libpod/runtime.go:934 +0xaf fp=0xc0006b6ef0 sp=0xc0006b6d88 pc=0x560db0a67a6f
github.com/containers/podman/libpod.makeRuntime(0xc00003fa40)
	/builddir/build/BUILD/containers-podman-35c0df3/_build/src/github.com/containers/podman/libpod/runtime.go:653 +0x213a fp=0xc0006b7390 sp=0xc0006b6ef0 pc=0x560db0a6621a
github.com/containers/podman/libpod.newRuntimeFromConfig(0xc000c3d100, {0xc0006b77a0, 0x0, 0x560db14faf18?})
	/builddir/build/BUILD/containers-podman-35c0df3/_build/src/github.com/containers/podman/libpod/runtime.go:236 +0x43d fp=0xc0006b76c0 sp=0xc0006b7390 pc=0x560db0a63a3d
github.com/containers/podman/libpod.NewRuntime({0xc000434c00?, 0x560db0cc385d?}, {0xc0006b77a0, 0x0, 0x0})
	/builddir/build/BUILD/containers-podman-35c0df3/_build/src/github.com/containers/podman/libpod/runtime.go:179 +0x51 fp=0xc0006b76f0 sp=0xc0006b76c0 pc=0x560db0a63531
github.com/containers/podman/pkg/domain/infra.getRuntime({0x560db150e7f8, 0xc0000460d0}, 0xc000434c00, 0xc0006b7a68)
	/builddir/build/BUILD/containers-podman-35c0df3/_build/src/github.com/containers/podman/pkg/domain/infra/runtime_libpod.go:275 +0x1a17 fp=0xc0006b7a48 sp=0xc0006b76f0 pc=0x560db0b73b37
github.com/containers/podman/pkg/domain/infra.GetRuntime.func1()
	/builddir/build/BUILD/containers-podman-35c0df3/_build/src/github.com/containers/podman/pkg/domain/infra/runtime_libpod.go:84 +0x48 fp=0xc0006b7a98 sp=0xc0006b7a48 pc=0x560db0b72048
sync.(*Once).doSlow(0xd00000000000001f?, 0x1f?)
	/usr/lib/golang/src/sync/once.go:68 +0xc2 fp=0xc0006b7af8 sp=0xc0006b7a98 pc=0x560dafd33e22
sync.(*Once).Do(...)
	/usr/lib/golang/src/sync/once.go:59
github.com/containers/podman/pkg/domain/infra.GetRuntime({0x560db150e7f8?, 0xc0000460d0?}, 0x2?, 0x560db0cca773?)
	/builddir/build/BUILD/containers-podman-35c0df3/_build/src/github.com/containers/podman/pkg/domain/infra/runtime_libpod.go:83 +0x6f fp=0xc0006b7b40 sp=0xc0006b7af8 pc=0x560db0b71f8f
github.com/containers/podman/pkg/domain/infra.NewLibpodImageRuntime(0x560db1f992a0?, 0xc0006b7bb0?)
	/builddir/build/BUILD/containers-podman-35c0df3/_build/src/github.com/containers/podman/pkg/domain/infra/runtime_proxy.go:25 +0x34 fp=0xc0006b7b78 sp=0xc0006b7b40 pc=0x560db0b755f4
github.com/containers/podman/pkg/domain/infra.NewImageEngine(0x560db0ccd3aa?)
	/builddir/build/BUILD/containers-podman-35c0df3/_build/src/github.com/containers/podman/pkg/domain/infra/runtime_abi.go:34 +0x4a fp=0xc0006b7be8 sp=0xc0006b7b78 pc=0x560db0b7192a
github.com/containers/podman/cmd/podman/registry.NewImageEngine(0x560db12faca0?, {0xc000c68c60?, 0x560db0cc9c01?, 0xa?})
	/builddir/build/BUILD/containers-podman-35c0df3/_build/src/github.com/containers/podman/cmd/podman/registry/registry.go:53 +0x51 fp=0xc0006b7c00 sp=0xc0006b7be8 pc=0x560db0b75e31
main.persistentPreRunE(0x560db1f7f3a0, {0x560db2054578, 0x0, 0x0})
	/builddir/build/BUILD/containers-podman-35c0df3/_build/src/github.com/containers/podman/cmd/podman/root.go:213 +0x8c7 fp=0xc0006b7d58 sp=0xc0006b7c00 pc=0x560db0caee07
github.com/containers/podman/vendor/github.com/spf13/cobra.(*Command).execute(0x560db1f7f3a0, {0xc00003c050, 0x0, 0x0})
	/builddir/build/BUILD/containers-podman-35c0df3/_build/src/github.com/containers/podman/vendor/github.com/spf13/cobra/command.go:847 +0x58b fp=0xc0006b7e30 sp=0xc0006b7d58 pc=0x560db032c54b
github.com/containers/podman/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x560db1f992a0)
	/builddir/build/BUILD/containers-podman-35c0df3/_build/src/github.com/containers/podman/vendor/github.com/spf13/cobra/command.go:990 +0x3b4 fp=0xc0006b7ee8 sp=0xc0006b7e30 pc=0x560db032ccd4
github.com/containers/podman/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/builddir/build/BUILD/containers-podman-35c0df3/_build/src/github.com/containers/podman/vendor/github.com/spf13/cobra/command.go:918
github.com/containers/podman/vendor/github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/builddir/build/BUILD/containers-podman-35c0df3/_build/src/github.com/containers/podman/vendor/github.com/spf13/cobra/command.go:911
main.Execute()
	/builddir/build/BUILD/containers-podman-35c0df3/_build/src/github.com/containers/podman/cmd/podman/root.go:99 +0xc5 fp=0xc0006b7f50 sp=0xc0006b7ee8 pc=0x560db0cae405
main.main()
	/builddir/build/BUILD/containers-podman-35c0df3/_build/src/github.com/containers/podman/cmd/podman/main.go:40 +0x7c fp=0xc0006b7f80 sp=0xc0006b7f50 pc=0x560db0cad8bc
runtime.main()
	/usr/lib/golang/src/runtime/proc.go:250 +0x213 fp=0xc0006b7fe0 sp=0xc0006b7f80 pc=0x560dafcf8413
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0006b7fe8 sp=0xc0006b7fe0 pc=0x560dafd29aa1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:361 +0xd6 fp=0xc000072fb0 sp=0xc000072f90 pc=0x560dafcf87d6
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:367
runtime.forcegchelper()
	/usr/lib/golang/src/runtime/proc.go:301 +0xad fp=0xc000072fe0 sp=0xc000072fb0 pc=0x560dafcf866d
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000072fe8 sp=0xc000072fe0 pc=0x560dafd29aa1
created by runtime.init.7
	/usr/lib/golang/src/runtime/proc.go:289 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:361 +0xd6 fp=0xc000073790 sp=0xc000073770 pc=0x560dafcf87d6
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:367
runtime.bgsweep(0x0?)
	/usr/lib/golang/src/runtime/mgcsweep.go:297 +0xd7 fp=0xc0000737c8 sp=0xc000073790 pc=0x560dafce36b7
runtime.gcenable.func1()
	/usr/lib/golang/src/runtime/mgc.go:177 +0x26 fp=0xc0000737e0 sp=0xc0000737c8 pc=0x560dafcd9226
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0000737e8 sp=0xc0000737e0 pc=0x560dafd29aa1
created by runtime.gcenable
	/usr/lib/golang/src/runtime/mgc.go:177 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x1d1c56f2a328?, 0x10000?, 0x0?, 0x0?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:361 +0xd6 fp=0xc000073f20 sp=0xc000073f00 pc=0x560dafcf87d6
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:367
runtime.bgscavenge(0x0?)
	/usr/lib/golang/src/runtime/mgcscavenge.go:364 +0x2a5 fp=0xc000073fc8 sp=0xc000073f20 pc=0x560dafce14c5
runtime.gcenable.func2()
	/usr/lib/golang/src/runtime/mgc.go:178 +0x26 fp=0xc000073fe0 sp=0xc000073fc8 pc=0x560dafcd91c6
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000073fe8 sp=0xc000073fe0 pc=0x560dafd29aa1
created by runtime.gcenable
	/usr/lib/golang/src/runtime/mgc.go:178 +0xaa

goroutine 5 [finalizer wait]:
runtime.gopark(0xc000003860?, 0x0?, 0x70?, 0x27?, 0x560dafd053b1?)
	/usr/lib/golang/src/runtime/proc.go:361 +0xd6 fp=0xc000072630 sp=0xc000072610 pc=0x560dafcf87d6
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:367
runtime.runfinq()
	/usr/lib/golang/src/runtime/mfinal.go:177 +0xb3 fp=0xc0000727e0 sp=0xc000072630 pc=0x560dafcd8253
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0000727e8 sp=0xc0000727e0 pc=0x560dafd29aa1
created by runtime.createfing
	/usr/lib/golang/src/runtime/mfinal.go:157 +0x45

goroutine 6 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:361 +0xd6 fp=0xc000074758 sp=0xc000074738 pc=0x560dafcf87d6
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1207 +0xe5 fp=0xc0000747e0 sp=0xc000074758 pc=0x560dafcdb345
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0000747e8 sp=0xc0000747e0 pc=0x560dafd29aa1
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1131 +0x25

goroutine 18 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:361 +0xd6 fp=0xc00006e758 sp=0xc00006e738 pc=0x560dafcf87d6
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1207 +0xe5 fp=0xc00006e7e0 sp=0xc00006e758 pc=0x560dafcdb345
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00006e7e8 sp=0xc00006e7e0 pc=0x560dafd29aa1
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1131 +0x25

goroutine 19 [GC worker (idle)]:
runtime.gopark(0x1d1c577aa3db?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:361 +0xd6 fp=0xc00006ef58 sp=0xc00006ef38 pc=0x560dafcf87d6
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1207 +0xe5 fp=0xc00006efe0 sp=0xc00006ef58 pc=0x560dafcdb345
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00006efe8 sp=0xc00006efe0 pc=0x560dafd29aa1
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1131 +0x25

goroutine 7 [GC worker (idle)]:
runtime.gopark(0x1d1c577aa395?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:361 +0xd6 fp=0xc000074f58 sp=0xc000074f38 pc=0x560dafcf87d6
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1207 +0xe5 fp=0xc000074fe0 sp=0xc000074f58 pc=0x560dafcdb345
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000074fe8 sp=0xc000074fe0 pc=0x560dafd29aa1
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1131 +0x25

goroutine 8 [GC worker (idle)]:
runtime.gopark(0x1d1c577fbbf1?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:361 +0xd6 fp=0xc000075758 sp=0xc000075738 pc=0x560dafcf87d6
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1207 +0xe5 fp=0xc0000757e0 sp=0xc000075758 pc=0x560dafcdb345
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0000757e8 sp=0xc0000757e0 pc=0x560dafd29aa1
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1131 +0x25

goroutine 9 [GC worker (idle)]:
runtime.gopark(0x1d1c577aa63e?, 0xc00010e020?, 0x18?, 0x14?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:361 +0xd6 fp=0xc000075f58 sp=0xc000075f38 pc=0x560dafcf87d6
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1207 +0xe5 fp=0xc000075fe0 sp=0xc000075f58 pc=0x560dafcdb345
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000075fe8 sp=0xc000075fe0 pc=0x560dafd29aa1
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1131 +0x25

goroutine 34 [GC worker (idle)]:
runtime.gopark(0x1d1c577a784c?, 0x3?, 0x1f?, 0xc?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:361 +0xd6 fp=0xc000114758 sp=0xc000114738 pc=0x560dafcf87d6
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1207 +0xe5 fp=0xc0001147e0 sp=0xc000114758 pc=0x560dafcdb345
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0001147e8 sp=0xc0001147e0 pc=0x560dafd29aa1
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1131 +0x25

goroutine 20 [GC worker (idle)]:
runtime.gopark(0x1d1c577a832d?, 0x3?, 0xfd?, 0x48?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:361 +0xd6 fp=0xc00006f758 sp=0xc00006f738 pc=0x560dafcf87d6
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1207 +0xe5 fp=0xc00006f7e0 sp=0xc00006f758 pc=0x560dafcdb345
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00006f7e8 sp=0xc00006f7e0 pc=0x560dafd29aa1
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1131 +0x25

goroutine 10 [GC worker (idle)]:
runtime.gopark(0x560db20560c0?, 0x1?, 0x24?, 0xaa?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:361 +0xd6 fp=0xc000110758 sp=0xc000110738 pc=0x560dafcf87d6
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1207 +0xe5 fp=0xc0001107e0 sp=0xc000110758 pc=0x560dafcdb345
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0001107e8 sp=0xc0001107e0 pc=0x560dafd29aa1
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1131 +0x25

goroutine 21 [GC worker (idle)]:
runtime.gopark(0x560db20560c0?, 0x1?, 0x63?, 0x69?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:361 +0xd6 fp=0xc00006ff58 sp=0xc00006ff38 pc=0x560dafcf87d6
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1207 +0xe5 fp=0xc00006ffe0 sp=0xc00006ff58 pc=0x560dafcdb345
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00006ffe8 sp=0xc00006ffe0 pc=0x560dafd29aa1
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1131 +0x25

goroutine 11 [GC worker (idle)]:
runtime.gopark(0x1d1c577aa42b?, 0x1?, 0x60?, 0x2a?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:361 +0xd6 fp=0xc000110f58 sp=0xc000110f38 pc=0x560dafcf87d6
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1207 +0xe5 fp=0xc000110fe0 sp=0xc000110f58 pc=0x560dafcdb345
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000110fe8 sp=0xc000110fe0 pc=0x560dafd29aa1
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1131 +0x25

goroutine 22 [GC worker (idle)]:
runtime.gopark(0x1d1c577a97eb?, 0x1?, 0x36?, 0x89?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:361 +0xd6 fp=0xc000070758 sp=0xc000070738 pc=0x560dafcf87d6
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1207 +0xe5 fp=0xc0000707e0 sp=0xc000070758 pc=0x560dafcdb345
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0000707e8 sp=0xc0000707e0 pc=0x560dafd29aa1
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1131 +0x25

goroutine 36 [select, locked to thread]:
runtime.gopark(0xc000111fa8?, 0x2?, 0x50?, 0x78?, 0xc000111fa4?)
	/usr/lib/golang/src/runtime/proc.go:361 +0xd6 fp=0xc000111e18 sp=0xc000111df8 pc=0x560dafcf87d6
runtime.selectgo(0xc000111fa8, 0xc000111fa0, 0x0?, 0x0, 0xc00033e690?, 0x1)
	/usr/lib/golang/src/runtime/select.go:328 +0x772 fp=0xc000111f58 sp=0xc000111e18 pc=0x560dafd084d2
runtime.ensureSigM.func1()
	/usr/lib/golang/src/runtime/signal_unix.go:973 +0x1bb fp=0xc000111fe0 sp=0xc000111f58 pc=0x560dafd0c89b
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000111fe8 sp=0xc000111fe0 pc=0x560dafd29aa1
created by runtime.ensureSigM
	/usr/lib/golang/src/runtime/signal_unix.go:956 +0xbd

goroutine 13 [syscall]:
runtime.notetsleepg(0x0?, 0x0?)
	/usr/lib/golang/src/runtime/lock_futex.go:235 +0x34 fp=0xc0001117a0 sp=0xc000111768 pc=0x560dafcc9754
os/signal.signal_recv()
	/usr/lib/golang/src/runtime/sigqueue.go:151 +0x2f fp=0xc0001117c0 sp=0xc0001117a0 pc=0x560dafd25f4f
os/signal.loop()
	/usr/lib/golang/src/os/signal/signal_unix.go:23 +0x19 fp=0xc0001117e0 sp=0xc0001117c0 pc=0x560db006e179
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0001117e8 sp=0xc0001117e0 pc=0x560dafd29aa1
created by os/signal.Notify.func1.1
	/usr/lib/golang/src/os/signal/signal.go:151 +0x2a

goroutine 14 [select]:
runtime.gopark(0xc0001127b0?, 0x2?, 0x0?, 0x0?, 0xc0001126ac?)
	/usr/lib/golang/src/runtime/proc.go:361 +0xd6 fp=0xc000083d18 sp=0xc000083cf8 pc=0x560dafcf87d6
runtime.selectgo(0xc000083fb0, 0xc0001126a8, 0x0?, 0x0, 0x0?, 0x1)
	/usr/lib/golang/src/runtime/select.go:328 +0x772 fp=0xc000083e58 sp=0xc000083d18 pc=0x560dafd084d2
github.com/containers/podman/libpod/shutdown.Start.func1()
	/builddir/build/BUILD/containers-podman-35c0df3/_build/src/github.com/containers/podman/libpod/shutdown/handler.go:47 +0x93 fp=0xc000083fe0 sp=0xc000083e58 pc=0x560db09685f3
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000083fe8 sp=0xc000083fe0 pc=0x560dafd29aa1
created by github.com/containers/podman/libpod/shutdown.Start
	/builddir/build/BUILD/containers-podman-35c0df3/_build/src/github.com/containers/podman/libpod/shutdown/handler.go:46 +0xe7

goroutine 16 [sleep]:
runtime.gopark(0x1d1c57e37652?, 0xc000113630?, 0x5?, 0x45?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:361 +0xd6 fp=0xc000113600 sp=0xc0001135e0 pc=0x560dafcf87d6
time.Sleep(0x5f5e100)
	/usr/lib/golang/src/runtime/time.go:194 +0x12e fp=0xc000113640 sp=0xc000113600 pc=0x560dafd2686e
github.com/containers/podman/libpod.(*Runtime).libimageEvents.func2()
	/builddir/build/BUILD/containers-podman-35c0df3/_build/src/github.com/containers/podman/libpod/runtime.go:858 +0x59 fp=0xc0001137e0 sp=0xc000113640 pc=0x560db0a67399
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0001137e8 sp=0xc0001137e0 pc=0x560dafd29aa1
created by github.com/containers/podman/libpod.(*Runtime).libimageEvents
	/builddir/build/BUILD/containers-podman-35c0df3/_build/src/github.com/containers/podman/libpod/runtime.go:835 +0x105
Aborted (core dumped)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

```
~]# rpm -q podman
podman-4.2.0-4.module+el8.7.0+17064+3b31f55c.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**
Yes!
I installed the latest version of Podman from RHEL Repository now. And i tested reinstall old version but Podman cannot work current still.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AMD x86 physical (my pc)

**Comment by shine-fire** [comment]
I have solved this problem now. follow this solution from redhat: [podman commands crash with "panic: invalid page type: xxxxxxxxxxxxx: yyyy"](https://access.redhat.com/solutions/5191521) 

Remove boltdb file and files underoverlay-containers directory
```bash
# rm /var/lib/containers/storage/libpod/bolt_state.db
# rm -rf /var/lib/containers/storage/overlay-containers/
```

And then I can use `podman ps`. But cannot list my containers because i deleted the `bolt_state.db` and `overlay-containers/`.
I have to rebuild my containers and get right again.

Example：
```bash
[root@my-pc qbittorrent]# ./start.sh 
8cd4f124c56d7125c40624ac889518d92099c96fed8163da7b72892ebfb257bd
[root@my-pc qbittorrent]# podman ps 
CONTAINER ID  IMAGE                                     COMMAND               CREATED        STATUS                      PORTS                                                                   NAMES
8cd4f124c56d  docker.io/linuxserver/qbittorrent:latest                        7 minutes ago  Up 7 minutes ago            0.0.0.0:6881->6881/udp, 0.0.0.0:6881->6881/tcp, 0.0.0.0:8080->8080/tcp  qbittorrent
```

**Comment by vrothberg** [comment]
Glad you could resolve the issue, @shine-fire! Thanks for sharing the fix.

**Comment by mheon** [comment]
Another DB corruption issue with Bolt. Fourth since summer. Beginning to become seriously concerned.
