### ISSUE TITLE
podman pull null-pointer dereference (_CONTAINERS_USERNS_CONFIGURED=1)

### ISSUE THREAD

**Issue by kpcyrd** [containers/podman#16948]
/kind bug

**Description**

podman crashes with a null-pointer dereference if `_CONTAINERS_USERNS_CONFIGURED=1`. The container I'm running this in is `quay.io/podman/stable:latest` and a root-less container.

**Steps to reproduce the issue:**

1. `podman run -it --rm --device=/dev/fuse quay.io/podman/stable bash`
2. `_CONTAINERS_USERNS_CONFIGURED=1 podman --log-level debug run -it --rm alpine id`

**Describe the results you received:**

<details>

```
[root@91d2318141a3 /]# podman --version
podman version 4.3.1
[root@91d2318141a3 /]# _CONTAINERS_USERNS_CONFIGURED=1 podman --log-level debug run -it --rm alpine id
INFO[0000] podman filtering at log level debug          
DEBU[0000] Called run.PersistentPreRunE(podman --log-level debug run -it --rm alpine id) 
DEBU[0000] Merged system config "/usr/share/containers/containers.conf" 
DEBU[0000] Merged system config "/etc/containers/containers.conf" 
DEBU[0000] Using conmon: "/usr/bin/conmon"              
DEBU[0000] Initializing boltdb state at /var/lib/containers/storage/libpod/bolt_state.db 
DEBU[0000] systemd-logind: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /var/lib/containers/storage 
DEBU[0000] Using run root /run/containers/storage       
DEBU[0000] Using static dir /var/lib/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/libpod                    
DEBU[0000] Using volume path /var/lib/containers/storage/volumes 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] Not configuring container store              
DEBU[0000] Initializing event backend file              
DEBU[0000] Configured OCI runtime runc initialization failed: no valid executable found for OCI runtime runc: invalid argument 
DEBU[0000] Configured OCI runtime runj initialization failed: no valid executable found for OCI runtime runj: invalid argument 
DEBU[0000] Configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument 
DEBU[0000] Configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument 
DEBU[0000] Configured OCI runtime krun initialization failed: no valid executable found for OCI runtime krun: invalid argument 
DEBU[0000] Using OCI runtime "/usr/bin/crun"            
INFO[0000] Setting parallel job count to 13             
DEBU[0000] Could not move to subcgroup: mkdir /sys/fs/cgroup/init: read-only file system 
DEBU[0000] Failed to add pause process to systemd sandbox cgroup: exec: "dbus-launch": executable file not found in $PATH 
DEBU[0000] Pulling image alpine (policy: missing)       
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9262861faa7]

goroutine 1 [running]:
panic({0x92628fa75a0, 0x92629bf2c30})
	/usr/lib/golang/src/runtime/panic.go:987 +0x3ba fp=0xc000527e30 sp=0xc000527d70 pc=0x92627b6617a
runtime.panicmem(...)
	/usr/lib/golang/src/runtime/panic.go:260
runtime.sigpanic()
	/usr/lib/golang/src/runtime/signal_unix.go:835 +0x2f6 fp=0xc000527e80 sp=0xc000527e30 pc=0x92627b7d236
github.com/containers/podman/vendor/github.com/containers/common/libimage.(*Runtime).Pull(0x0, {0x926291a0f60, 0xc000309770}, {0x7a44ff9e68f7, 0x6}, 0x1, 0xc000528268)
	/builddir/build/BUILD/podman-4.3.1/_build/src/github.com/containers/podman/vendor/github.com/containers/common/libimage/pull.go:119 +0x727 fp=0xc000528218 sp=0xc000527e80 pc=0x9262861faa7
github.com/containers/podman/pkg/domain/infra/abi.(*ImageEngine).Pull(0x92628f8d400?, {0x926291a0f60?, 0xc000309770?}, {0x7a44ff9e68f7?, 0xc00036fe00?}, {0x0, {0x0, 0x0}, {0x0, 0x0}, ...})
	/builddir/build/BUILD/podman-4.3.1/_build/src/github.com/containers/podman/pkg/domain/infra/abi/images.go:245 +0x205 fp=0xc000528428 sp=0xc000528218 pc=0x926289779a5
github.com/containers/podman/cmd/podman/containers.PullImage({0x7a44ff9e68f7, 0x6}, 0xc000421000)
	/builddir/build/BUILD/podman-4.3.1/_build/src/github.com/containers/podman/cmd/podman/containers/create.go:330 +0x35d fp=0xc0005285e8 sp=0xc000528428 pc=0x92628a2097d
github.com/containers/podman/cmd/podman/containers.run(0x92629c0f4c0?, {0xc000339b40?, 0x2, 0x4})
	/builddir/build/BUILD/podman-4.3.1/_build/src/github.com/containers/podman/cmd/podman/containers/run.go:144 +0x38e fp=0xc000529cf8 sp=0xc0005285e8 pc=0x92628a2dd8e
github.com/containers/podman/vendor/github.com/spf13/cobra.(*Command).execute(0x92629c0f4c0, {0xc0000400c0, 0x4, 0x4})
	/builddir/build/BUILD/podman-4.3.1/_build/src/github.com/containers/podman/vendor/github.com/spf13/cobra/command.go:916 +0x862 fp=0xc000529e30 sp=0xc000529cf8 pc=0x926280ba9a2
github.com/containers/podman/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x92629c2d4e0)
	/builddir/build/BUILD/podman-4.3.1/_build/src/github.com/containers/podman/vendor/github.com/spf13/cobra/command.go:1040 +0x3bd fp=0xc000529ee8 sp=0xc000529e30 pc=0x926280bb21d
github.com/containers/podman/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/builddir/build/BUILD/podman-4.3.1/_build/src/github.com/containers/podman/vendor/github.com/spf13/cobra/command.go:968
github.com/containers/podman/vendor/github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/builddir/build/BUILD/podman-4.3.1/_build/src/github.com/containers/podman/vendor/github.com/spf13/cobra/command.go:961
main.Execute()
	/builddir/build/BUILD/podman-4.3.1/_build/src/github.com/containers/podman/cmd/podman/root.go:105 +0xc5 fp=0xc000529f50 sp=0xc000529ee8 pc=0x92628b3b8a5
main.main()
	/builddir/build/BUILD/podman-4.3.1/_build/src/github.com/containers/podman/cmd/podman/main.go:40 +0x7c fp=0xc000529f80 sp=0xc000529f50 pc=0x92628b3ad1c
runtime.main()
	/usr/lib/golang/src/runtime/proc.go:250 +0x213 fp=0xc000529fe0 sp=0xc000529f80 pc=0x92627b68e13
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000529fe8 sp=0xc000529fe0 pc=0x92627b9b241

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:363 +0xd6 fp=0xc000064fb0 sp=0xc000064f90 pc=0x92627b691d6
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:369
runtime.forcegchelper()
	/usr/lib/golang/src/runtime/proc.go:302 +0xad fp=0xc000064fe0 sp=0xc000064fb0 pc=0x92627b6906d
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000064fe8 sp=0xc000064fe0 pc=0x92627b9b241
created by runtime.init.7
	/usr/lib/golang/src/runtime/proc.go:290 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:363 +0xd6 fp=0xc000065790 sp=0xc000065770 pc=0x92627b691d6
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:369
runtime.bgsweep(0x0?)
	/usr/lib/golang/src/runtime/mgcsweep.go:297 +0xd7 fp=0xc0000657c8 sp=0xc000065790 pc=0x92627b53b97
runtime.gcenable.func1()
	/usr/lib/golang/src/runtime/mgc.go:178 +0x26 fp=0xc0000657e0 sp=0xc0000657c8 pc=0x92627b487e6
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000657e8 sp=0xc0000657e0 pc=0x92627b9b241
created by runtime.gcenable
	/usr/lib/golang/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc00007c000?, 0x92628dff368?, 0x0?, 0x0?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:363 +0xd6 fp=0xc000065f70 sp=0xc000065f50 pc=0x92627b691d6
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:369
runtime.(*scavengerState).park(0x92629cb15e0)
	/usr/lib/golang/src/runtime/mgcscavenge.go:389 +0x53 fp=0xc000065fa0 sp=0xc000065f70 pc=0x92627b51bf3
runtime.bgscavenge(0x0?)
	/usr/lib/golang/src/runtime/mgcscavenge.go:622 +0x65 fp=0xc000065fc8 sp=0xc000065fa0 pc=0x92627b521e5
runtime.gcenable.func2()
	/usr/lib/golang/src/runtime/mgc.go:179 +0x26 fp=0xc000065fe0 sp=0xc000065fc8 pc=0x92627b48786
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000065fe8 sp=0xc000065fe0 pc=0x92627b9b241
created by runtime.gcenable
	/usr/lib/golang/src/runtime/mgc.go:179 +0xaa

goroutine 5 [finalizer wait]:
runtime.gopark(0x92629cb3380?, 0xc000007860?, 0x0?, 0x0?, 0xc000064770?)
	/usr/lib/golang/src/runtime/proc.go:363 +0xd6 fp=0xc000064628 sp=0xc000064608 pc=0x92627b691d6
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:369
runtime.runfinq()
	/usr/lib/golang/src/runtime/mfinal.go:180 +0x10f fp=0xc0000647e0 sp=0xc000064628 pc=0x92627b478ef
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000647e8 sp=0xc0000647e0 pc=0x92627b9b241
created by runtime.createfing
	/usr/lib/golang/src/runtime/mfinal.go:157 +0x45

goroutine 6 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:363 +0xd6 fp=0xc000066750 sp=0xc000066730 pc=0x92627b691d6
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1235 +0xf1 fp=0xc0000667e0 sp=0xc000066750 pc=0x92627b4a951
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000667e8 sp=0xc0000667e0 pc=0x92627b9b241
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1159 +0x25

goroutine 7 [GC worker (idle)]:
runtime.gopark(0x827d973538f?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:363 +0xd6 fp=0xc000066f50 sp=0xc000066f30 pc=0x92627b691d6
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1235 +0xf1 fp=0xc000066fe0 sp=0xc000066f50 pc=0x92627b4a951
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000066fe8 sp=0xc000066fe0 pc=0x92627b9b241
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1159 +0x25

goroutine 18 [GC worker (idle)]:
runtime.gopark(0x827d97363f3?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:363 +0xd6 fp=0xc000060750 sp=0xc000060730 pc=0x92627b691d6
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1235 +0xf1 fp=0xc0000607e0 sp=0xc000060750 pc=0x92627b4a951
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000607e8 sp=0xc0000607e0 pc=0x92627b9b241
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1159 +0x25

goroutine 19 [GC worker (idle)]:
runtime.gopark(0x827d9734dfa?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:363 +0xd6 fp=0xc000072f50 sp=0xc000072f30 pc=0x92627b691d6
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1235 +0xf1 fp=0xc000072fe0 sp=0xc000072f50 pc=0x92627b4a951
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000072fe8 sp=0xc000072fe0 pc=0x92627b9b241
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1159 +0x25

goroutine 8 [select, locked to thread]:
runtime.gopark(0xc000061fa8?, 0x2?, 0x4e?, 0x97?, 0xc000061fa4?)
	/usr/lib/golang/src/runtime/proc.go:363 +0xd6 fp=0xc000075e18 sp=0xc000075df8 pc=0x92627b691d6
runtime.selectgo(0xc000075fa8, 0xc000061fa0, 0x0?, 0x0, 0x0?, 0x1)
	/usr/lib/golang/src/runtime/select.go:328 +0x7bc fp=0xc000075f58 sp=0xc000075e18 pc=0x92627b7931c
runtime.ensureSigM.func1()
	/usr/lib/golang/src/runtime/signal_unix.go:991 +0x1b4 fp=0xc000075fe0 sp=0xc000075f58 pc=0x92627b7d774
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000075fe8 sp=0xc000075fe0 pc=0x92627b9b241
created by runtime.ensureSigM
	/usr/lib/golang/src/runtime/signal_unix.go:974 +0xbd

goroutine 34 [syscall]:
runtime.notetsleepg(0x0?, 0x0?)
	/usr/lib/golang/src/runtime/lock_futex.go:236 +0x34 fp=0xc000530fa0 sp=0xc000530f68 pc=0x92627b3abd4
os/signal.signal_recv()
	/usr/lib/golang/src/runtime/sigqueue.go:152 +0x2f fp=0xc000530fc0 sp=0xc000530fa0 pc=0x92627b976ef
os/signal.loop()
	/usr/lib/golang/src/os/signal/signal_unix.go:23 +0x19 fp=0xc000530fe0 sp=0xc000530fc0 pc=0x92627ed8859
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000530fe8 sp=0xc000530fe0 pc=0x92627b9b241
created by os/signal.Notify.func1.1
	/usr/lib/golang/src/os/signal/signal.go:151 +0x2a

goroutine 20 [select]:
runtime.gopark(0xc00052cfb0?, 0x2?, 0x0?, 0x0?, 0xc00052ceac?)
	/usr/lib/golang/src/runtime/proc.go:363 +0xd6 fp=0xc000077d18 sp=0xc000077cf8 pc=0x92627b691d6
runtime.selectgo(0xc000077fb0, 0xc00052cea8, 0x0?, 0x0, 0x0?, 0x1)
	/usr/lib/golang/src/runtime/select.go:328 +0x7bc fp=0xc000077e58 sp=0xc000077d18 pc=0x92627b7931c
github.com/containers/podman/libpod/shutdown.Start.func1()
	/builddir/build/BUILD/podman-4.3.1/_build/src/github.com/containers/podman/libpod/shutdown/handler.go:47 +0x93 fp=0xc000077fe0 sp=0xc000077e58 pc=0x9262878b3b3
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000077fe8 sp=0xc000077fe0 pc=0x92627b9b241
created by github.com/containers/podman/libpod/shutdown.Start
	/builddir/build/BUILD/podman-4.3.1/_build/src/github.com/containers/podman/libpod/shutdown/handler.go:46 +0xe7

goroutine 22 [chan receive]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:363 +0xd6 fp=0xc0000636f0 sp=0xc0000636d0 pc=0x92627b691d6
runtime.chanrecv(0xc000284a80, 0xc0000637c8, 0x1)
	/usr/lib/golang/src/runtime/chan.go:583 +0x49b fp=0xc000063780 sp=0xc0000636f0 pc=0x92627b355fb
runtime.chanrecv2(0x0?, 0x0?)
	/usr/lib/golang/src/runtime/chan.go:447 +0x18 fp=0xc0000637a8 sp=0xc000063780 pc=0x92627b35138
github.com/containers/podman/libpod.(*Runtime).startWorker.func1()
	/builddir/build/BUILD/podman-4.3.1/_build/src/github.com/containers/podman/libpod/runtime_worker.go:6 +0x74 fp=0xc0000637e0 sp=0xc0000637a8 pc=0x926288fec74
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000637e8 sp=0xc0000637e0 pc=0x92627b9b241
created by github.com/containers/podman/libpod.(*Runtime).startWorker
	/builddir/build/BUILD/podman-4.3.1/_build/src/github.com/containers/podman/libpod/runtime_worker.go:5 +0x96
Aborted (core dumped)
```

</details>

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 4.3.1
```

**Output of `podman info`:**

```
host:
  arch: amd64
  buildahVersion: 1.28.0
  cgroupControllers:
  - cpu
  - memory
  - pids
  cgroupManager: cgroupfs
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.5-1.fc37.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.5, commit: '
  cpuUtilization:
    idlePercent: 84.81
    systemPercent: 3.08
    userPercent: 12.11
  cpus: 4
  distribution:
    distribution: fedora
    variant: container
    version: "37"
  eventLogger: file
  hostname: 91d2318141a3
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 0
      size: 1
    uidmap:
    - container_id: 0
      host_id: 0
      size: 1
  kernel: 6.0.15-hardened1-1-hardened
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 700776448
  memTotal: 8033456128
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.7.2-1.fc37.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.7.2
      commit: 0356bf4aff9a133d655dc13b1d9ac9424706cac4
      rundir: /run/user/0/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    path: /run/user/0/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-8.fc37.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 7608987648
  swapTotal: 8589930496
  uptime: 2h 33m 0.00s (Approximately 0.08 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /root/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.imagestore: /var/lib/shared
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.9-6.fc37.x86_64
      Version: |-
        fusermount3 version: 3.10.5
        fuse-overlayfs: version 1.9
        FUSE library version 3.10.5
        using FUSE kernel interface version 7.31
    overlay.mountopt: nodev,fsync=0
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 991336333312
  graphRootUsed: 922507169792
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.3.1
  Built: 1668178887
  BuiltTime: Fri Nov 11 15:01:27 2022
  GitCommit: ""
  GoVersion: go1.19.2
  Os: linux
  OsArch: linux/amd64
  Version: 4.3.1
```

**Have you tested with the latest version of Podman and have you checked [the Podman Troubleshooting Guide](https://github.com/containers/podman/blob/main/troubleshooting.md)?**

No

**Comment by vrothberg** [comment]
Thanks for reaching out.

I don´t think it's safe to manually set  _CONTAINERS_USERNS_CONFIGURED. @giuseppe PTAL

**Comment by giuseppe** [comment]
Yes, it is used internally by Podman when it creates the rootless user namespace, it is not supposed to be used directly
