### ISSUE TITLE
[Bug]: podman pull in yocto kirkstone

### ISSUE THREAD

**Issue by Razriel3** [containers/podman#16979]
### Issue Description

running on ubuntu 20.04 as build machine.
podman install on this machine is 3.4.2
when running from regular shell podman pull succesful
when running from honister version podman pull succesful
when running same recipe from kirkston version it fails.

### Steps to reproduce the issue

Steps to reproduce the issue
1. running bitbake of recipe. the recipe is trying to pull image using podman.
2. podman pull postgres:14
3.

### Describe the results you received

Log data follows:
| DEBUG: Executing shell function do_pull_image
| cannot setresgid: Invalid argument
| panic: runtime error: invalid memory address or nil pointer dereference
| [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5632d0bb17a0]
|
| goroutine 1 [running]:
| github.com/containers/podman/vendor/github.com/containers/common/libimage.(*Runtime).Pull(0x0, 0x5632d1b3d720, 0xc0007b56e0, 0xc0001f9c90, 0xb, 0x0, 0xc000159a40, 0x0, 0x0, 0x0, ...)
| /usr/src/packages/BUILD/src/github.com/containers/podman/vendor/github.com/containers/common/libimage/pull.go:117 +0x500
| github.com/containers/podman/pkg/domain/infra/abi.(*ImageEngine).Pull(0xc00012c3d0, 0x5632d1b3d720, 0xc0007b56e0, 0x7ffde5cbbe0c, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
| /usr/src/packages/BUILD/src/github.com/containers/podman/pkg/domain/infra/abi/images.go:231 +0x1e5
| github.com/containers/podman/cmd/podman/images.imagePull(0x5632d26d5e20, 0xc0000894f0, 0x1, 0x1, 0x0, 0x0)
| /usr/src/packages/BUILD/src/github.com/containers/podman/cmd/podman/images/pull.go:160 +0x2d5
| github.com/containers/podman/vendor/github.com/spf13/cobra.(*Command).execute(0x5632d26d5e20, 0xc00003c1a0, 0x1, 0x1, 0x5632d26d5e20, 0xc00003c1a0)
| /usr/src/packages/BUILD/src/github.com/containers/podman/vendor/github.com/spf13/cobra/command.go:856 +0x47c
| github.com/containers/podman/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x5632d26e7120, 0xc00004a188, 0x5632d1886480, 0x5632d27a98f0)
| /usr/src/packages/BUILD/src/github.com/containers/podman/vendor/github.com/spf13/cobra/command.go:974 +0x375
| github.com/containers/podman/vendor/github.com/spf13/cobra.(*Command).Execute(...)
| /usr/src/packages/BUILD/src/github.com/containers/podman/vendor/github.com/spf13/cobra/command.go:902
| github.com/containers/podman/vendor/github.com/spf13/cobra.(*Command).ExecuteContext(...)
| /usr/src/packages/BUILD/src/github.com/containers/podman/vendor/github.com/spf13/cobra/command.go:895
| main.Execute()
| /usr/src/packages/BUILD/src/github.com/containers/podman/cmd/podman/root.go:91 +0xee
| main.main()
| /usr/src/packages/BUILD/src/github.com/containers/podman/cmd/podman/main.go:39 +0x94
| WARNING: exit code 2 from a shell command.

### Describe the results you expected

image should be download to local disk.
possible to list it using podman images in any shell.

### podman info output

```shell
cannot setresgid: Invalid argument
ERRO[0000] Error getting info on OCI runtime crun: error getting version of OCI runtime crun: /usr/bin/crun --version failed: unknown fcntl argument 1034, assuming long argument.
unknown fcntl argument 1033, assuming long argument.
Failed to re-execute libcrun via memory file descriptor
(exit status 1)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x158 pc=0x562815b020fe]

goroutine 1 [running]:
github.com/containers/podman/libpod.(*Runtime).storeInfo(0xc0004c96c0, 0xc0001f0400, 0x0, 0x0)
/usr/src/packages/BUILD/src/github.com/containers/podman/libpod/info.go:279 +0x7e
github.com/containers/podman/libpod.(*Runtime).info(0xc0004c96c0, 0x0, 0x0, 0x2)
/usr/src/packages/BUILD/src/github.com/containers/podman/libpod/info.go:47 +0x132
github.com/containers/podman/libpod.(*Runtime).Info(...)
/usr/src/packages/BUILD/src/github.com/containers/podman/libpod/runtime.go:909
github.com/containers/podman/pkg/domain/infra/abi.(*ContainerEngine).Info(0xc0000101a8, 0x562816591720, 0xc0001d5140, 0x562815070f4a, 0xc0005ee200, 0xc000147ce8)
/usr/src/packages/BUILD/src/github.com/containers/podman/pkg/domain/infra/abi/system.go:27 +0x34
github.com/containers/podman/cmd/podman/system.info(0x562817137520, 0xc0001120e0, 0x0, 0x1, 0x0, 0x0)
/usr/src/packages/BUILD/src/github.com/containers/podman/cmd/podman/system/info.go:72 +0x78
github.com/containers/podman/vendor/github.com/spf13/cobra.(*Command).execute(0x562817137520, 0xc00003c1a0, 0x1, 0x1, 0x562817137520, 0xc00003c1a0)
/usr/src/packages/BUILD/src/github.com/containers/podman/vendor/github.com/spf13/cobra/command.go:856 +0x47c
github.com/containers/podman/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x56281713b120, 0xc0000482b8, 0x5628162da480, 0x5628171fd8f0)
/usr/src/packages/BUILD/src/github.com/containers/podman/vendor/github.com/spf13/cobra/command.go:974 +0x375
github.com/containers/podman/vendor/github.com/spf13/cobra.(*Command).Execute(...)
/usr/src/packages/BUILD/src/github.com/containers/podman/vendor/github.com/spf13/cobra/command.go:902
github.com/containers/podman/vendor/github.com/spf13/cobra.(*Command).ExecuteContext(...)
/usr/src/packages/BUILD/src/github.com/containers/podman/vendor/github.com/spf13/cobra/command.go:895
main.Execute()
/usr/src/packages/BUILD/src/github.com/containers/podman/cmd/podman/root.go:91 +0xee
main.main()
/usr/src/packages/BUILD/src/github.com/containers/podman/cmd/podman/main.go:39 +0x94
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

No

### Additional environment details

running on yocto kirkstone.
same recipe was working fine on same buid machine and same podman but on yocto honister version.

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by rhatdan** [comment]
This is not something that can be fixed upstream, also this is an older version of podman.  Please try with the latest version.
