### ISSUE TITLE
[Bug]: markdown-preprocess not multi-core safe with make

### ISSUE THREAD

**Issue by Foxboron** [containers/podman#17322]
### Issue Description

When building `podman` with a lot of cores, like `make -j64`, it seems the markdown preprocessor is racey and doesn't like this.

The build will fail with 
```
hack/markdown-preprocess
hack/markdown-preprocess
hack/markdown-preprocess
hack/markdown-preprocess
hack/markdown-preprocess
hack/markdown-preprocess
hack/markdown-preprocess
hack/markdown-preprocess
Traceback (most recent call last):
  File "/build/podman/src/podman/hack/markdown-preprocess", line 184, in <module>
Traceback (most recent call last):
  File "/build/podman/src/podman/hack/markdown-preprocess", line 184, in <module>
    main()
  File "/build/podman/src/podman/hack/markdown-preprocess", line 181, in main
    preprocessor.rewrite_optionfiles()
  File "/build/podman/src/podman/hack/markdown-preprocess", line 84, in rewrite_optionfiles
    main()
  File "/build/podman/src/podman/hack/markdown-preprocess", line 178, in main
    if not filecmp.cmp(optionfile, tmpfile):
  File "/usr/lib/python3.10/filecmp.py", line 53, in cmp
    s1 = _sig(os.stat(f1))
FileNotFoundError: [Errno 2] No such file or directory: 'options/latest.md'
    preprocessor.process(infile)
  File "/build/podman/src/podman/hack/markdown-preprocess", line 48, in process
    self.insert_file(fh_out, optionfile)
  File "/build/podman/src/podman/hack/markdown-preprocess", line 100, in insert_file
    with open(path, 'r', encoding='utf-8') as fh_included:
FileNotFoundError: [Errno 2] No such file or directory: 'options/latest.md'
Traceback (most recent call last):
  File "/build/podman/src/podman/hack/markdown-preprocess", line 184, in <module>
    main()
  File "/build/podman/src/podman/hack/markdown-preprocess", line 181, in main
    preprocessor.rewrite_optionfiles()
  File "/build/podman/src/podman/hack/markdown-preprocess", line 84, in rewrite_optionfiles
    if not filecmp.cmp(optionfile, tmpfile):
  File "/usr/lib/python3.10/filecmp.py", line 54, in cmp
    s2 = _sig(os.stat(f2))
FileNotFoundError: [Errno 2] No such file or directory: 'options/memory.md.tmp'
make: *** [Makefile:463: docs/source/markdown/podman-container-inspect.1.md] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Makefile:463: docs/source/markdown/podman-diff.1.md] Error 1
make: *** [Makefile:463: docs/source/markdown/podman-auto-update.1.md] Error 1
make: Leaving directory '/build/podman/src/podman'
```

While forcing `-j1` seems to work fine.

```
hack/markdown-preprocess
if [ ! -x "/usr/bin/go-md2man" ]; then \
	make -C test/tools build/go-md2man ; \
fi
mkdir -p docs/build/man
make: Leaving directory '/build/podman/src/podman'
make: Entering directory '/build/podman/src/podman'
if [ ! -x "/usr/bin/go-md2man" ]; then \
	make -C test/tools build/go-md2man ; \
fi
mkdir -p docs/build/man
(cd docs; ./dckrman.sh ./build/man/*.1)
```

I think it's related to this commit as this did not happen with `4.3.0`.
https://github.com/containers/podman/commit/c9c2f644dac42243189473c41baa7995202043df

### Steps to reproduce the issue

Steps to reproduce the issue
1. `make -j64`

### Describe the results you received

Failing build.

### Describe the results you expected

A working build.

### podman info output

```shell
podman v4.4.0
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by p-linnane** [comment]
Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project. We are seeing this trying to build podman v4.4.0. podman builds fine if we do not try to build docs. Relevant GitHub Actions run: https://github.com/Homebrew/homebrew-core/actions/runs/4071150551/jobs/7012750769

Relates to https://github.com/Homebrew/homebrew-core/pull/122122

**Comment by vrothberg** [comment]
Thanks for reaching!

@edsantiago PTAL
