### ISSUE TITLE
Error installing Podman  on Mac M1(osx 13.1) 

### ISSUE THREAD

**Issue by cdaddio** [containers/podman#17485]
Hi all, i have this issue installing podman via brew, it seems,  during meson build 

`==> Installing podman dependency: glib
==> Patching
==> Applying hardcoded-paths.diff
patching file 'gio/xdgmime/xdgmime.c'
patching file 'glib/gutils.c'
==> meson setup build --default-library=both --localstatedir=/Users/var -Diconv=auto -Dgio_module_dir=/Users/lib/gio/modules -Dbsymbolic_functions=false -Ddtrace=false --prefix=/opt/homebrew/Cellar/glib/2.74.5 --li
Last 15 lines from /Users/cristian/Library/Logs/Homebrew/glib/01.meson:
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/opt/meson/bin/meson", line 33, in <module>
    sys.exit(load_entry_point('meson==1.0.0', 'console_scripts', 'meson')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/opt/meson/bin/meson", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for meson
`

Thank you

**Comment by Luap99** [comment]
Please report this to homebrew, the podman team does not maintain homebrew packages.
