### ISSUE TITLE
Network connection timing out inside podman container

### ISSUE THREAD

**Issue by 125priyank** [containers/podman#19093]
### Issue Description

In a podman container, we are facing connection timing out when connecting to a socket. The code which runs inside container is similar to this
```
#!/usr/bin/env python3
import socket
import time

server='142.251.46.174'
port=80

conn = 1
while True:
  s = socket.socket()
  s.settimeout(3)
  print( "connecting..." )
  s.connect( (server, port))
  print( "connected." )
  time.sleep(1)
  s.close()
  print( "connection {}".format( conn ) )
  conn += 1
```

### Steps to reproduce the issue

Steps to reproduce the issue
1. Create a container from an image which has the Python script
2. sudo podman exec -it <ctnr> ./script.py

### Describe the results you received

After some iterations we can see the request timing out
```
.
.
connection 227
connecting...
Traceback (most recent call last):
  File "/root/./conn.py", line 15, in <module>
    s.connect( (server, port))
TimeoutError: timed out
e74d803d9a17:~#
```

### Describe the results you expected

No connection timeout.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.30.0
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.7-2.fc38.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: fab2fef7227d2dc16478d29f1185953f81451702'
  cpuUtilization:
    idlePercent: 90.89
    systemPercent: 1.23
    userPercent: 7.88
  cpus: 24
  databaseBackend: boltdb
  distribution:
    distribution: '"almalinux"'
    version: "9.0"
  eventLogger: journald
  hostname: mock127.sjc.aristanetworks.com
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 10000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 10000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.10.62-32152435.AroraKernel510.el7.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 169840312320
  memTotal: 270363676672
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.8.5-1.fc38.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.5
      commit: b6f80f766c9a89eb7b1440c0a70ab287434b17ed
      rundir: /run/user/10000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    path: /run/user/10000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-12.fc38.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.2
  swapFree: 0
  swapTotal: 0
  uptime: 473h 40m 36.00s (Approximately 19.71 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/arastra/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/arastra/.local/share/containers/storage
  graphRootAllocated: 210107351040
  graphRootUsed: 15801094144
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 5
  runRoot: /run/user/10000/containers
  transientStore: false
  volumePath: /home/arastra/.local/share/containers/storage/volumes
version:
  APIVersion: 4.5.1
  Built: 1685123928
  BuiltTime: Fri May 26 10:58:48 2023
  GitCommit: ""
  GoVersion: go1.20.4
  Os: linux
  OsArch: linux/amd64
  Version: 4.5.1
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

### Additional information

docker inspect container output

```
[
     {
          "Id": "5c14d0b097472483e0ab276e6145a71f46120af3f41d04a1df5203ddd566acdb",
          "Created": "2023-07-03T05:54:21.298052775-07:00",
          "Path": "/usr/bin/dumb-init",
          "Args": [
               "--",
               "bash"
          ],
          "State": {
               "OciVersion": "1.1.0-rc.1",
               "Status": "running",
               "Running": true,
               "Paused": false,
               "Restarting": false,
               "OOMKilled": false,
               "Dead": false,
               "Pid": 1438380,
               "ConmonPid": 1438378,
               "ExitCode": 0,
               "Error": "",
               "StartedAt": "2023-07-03T05:54:21.436961922-07:00",
               "FinishedAt": "0001-01-01T00:00:00Z",
               "Health": {
                    "Status": "",
                    "FailingStreak": 0,
                    "Log": null
               },
               "CgroupPath": "/machine.slice/libpod-5c14d0b097472483e0ab276e6145a71f46120af3f41d04a1df5203ddd566acdb.scope",
               "CheckpointedAt": "0001-01-01T00:00:00Z",
               "RestoredAt": "0001-01-01T00:00:00Z"
          },
          "Image": "80a7b9f513102213310c9c4a04e092f451a7df9b492fda7adb394cbce45c44b2",
          "ImageDigest": "sha256:c1cee4a6fdee24f9cf1c6040d7d4f50006857cf9598ac791fb7710ece93080a8",
          "ImageName": "docker.corp.arista.io/orca/mockd-mockd-trunk-x86_64_el7:31761530",
          "Rootfs": "",
          "Pod": "",
          "ResolvConfPath": "/run/containers/storage/overlay-containers/5c14d0b097472483e0ab276e6145a71f46120af3f41d04a1df5203ddd566acdb/userdata/resolv.conf",
          "HostnamePath": "/run/containers/storage/overlay-containers/5c14d0b097472483e0ab276e6145a71f46120af3f41d04a1df5203ddd566acdb/userdata/hostname",
          "HostsPath": "/run/containers/storage/overlay-containers/5c14d0b097472483e0ab276e6145a71f46120af3f41d04a1df5203ddd566acdb/userdata/hosts",
          "StaticDir": "/var/lib/containers/storage/overlay-containers/5c14d0b097472483e0ab276e6145a71f46120af3f41d04a1df5203ddd566acdb/userdata",
          "OCIConfigPath": "/var/lib/containers/storage/overlay-containers/5c14d0b097472483e0ab276e6145a71f46120af3f41d04a1df5203ddd566acdb/userdata/config.json",
          "OCIRuntime": "crun",
          "ConmonPidFile": "/run/containers/storage/overlay-containers/5c14d0b097472483e0ab276e6145a71f46120af3f41d04a1df5203ddd566acdb/userdata/conmon.pid",
          "PidFile": "/run/containers/storage/overlay-containers/5c14d0b097472483e0ab276e6145a71f46120af3f41d04a1df5203ddd566acdb/userdata/pidfile",
          "Name": "hardcore_germain",
          "RestartCount": 0,
          "Driver": "overlay",
          "MountLabel": "",
          "ProcessLabel": "",
          "AppArmorProfile": "",
          "EffectiveCaps": [
               "CAP_CHOWN",
               "CAP_DAC_OVERRIDE",
               "CAP_FOWNER",
               "CAP_FSETID",
               "CAP_KILL",
               "CAP_NET_BIND_SERVICE",
               "CAP_SETFCAP",
               "CAP_SETGID",
               "CAP_SETPCAP",
               "CAP_SETUID",
               "CAP_SYS_CHROOT"
          ],
          "BoundingCaps": [
               "CAP_CHOWN",
               "CAP_DAC_OVERRIDE",
               "CAP_FOWNER",
               "CAP_FSETID",
               "CAP_KILL",
               "CAP_NET_BIND_SERVICE",
               "CAP_SETFCAP",
               "CAP_SETGID",
               "CAP_SETPCAP",
               "CAP_SETUID",
               "CAP_SYS_CHROOT"
          ],
          "ExecIDs": [],
          "GraphDriver": {
               "Name": "overlay",
               "Data": {
                    "LowerDir": "/var/lib/containers/storage/overlay/117428e4a921fbaa7e49b7dad6c39ebc7572505ef7abfd31c811b124b347fc28/diff:/var/lib/containers/storage/overlay/602fe7eb775c139a411e5b9b8059ab02dc1cb757a5d1970211aeb9862abe0a0a/diff:/var/lib/containers/storage/overlay/a035ee6ce628dcabe36763aff71d2fcdb971e5f44ab0f0046fd70672bdfbc6f0/diff:/var/lib/containers/storage/overlay/9c83926435069e1c524163e6d69b72766e7d3969345d1ece0928a1c8ebbac622/diff:/var/lib/containers/storage/overlay/f02e4576e3b5cd72a870bc3c7d59ed8fb5d01b8b8812b60f4c094e49978fe44e/diff:/var/lib/containers/storage/overlay/b79e70830721723542ddb884359edcda6cc65db6217578bf228350821dccacce/diff:/var/lib/containers/storage/overlay/6ada63a70757126c3cd42cb6239dc06c29bb467e21984b5d8b7465bdbc3d8f0f/diff:/var/lib/containers/storage/overlay/56f608f6ae28d42d4c4a5ddf431816fb8b44be463ed5fec3753b4a3fe32d29ac/diff:/var/lib/containers/storage/overlay/ba5c107c7b8b65651c8d1521248b38a02d9b242b8458c94e07a37bceb822f802/diff:/var/lib/containers/storage/overlay/23aa7b7dd956d2b903193a4df5ced9ebd76f2777d270f826357cd649326f8c38/diff:/var/lib/containers/storage/overlay/e756d63d8b246ab53d7902eaafdf352191e01a83ae09d7ae7ccf3ac05f370a6f/diff:/var/lib/containers/storage/overlay/0598bbe8e9583416461ff64f674f744287bdb75f2fb4749d8b057355c2aee62b/diff:/var/lib/containers/storage/overlay/4b446c04acf25839c50ff69efc38f3d4323fadf0e4d95c536396cc0792fc1272/diff:/var/lib/containers/storage/overlay/df2d0dca963e8c85df9909b81e20424dec2f6c53825899248e63773c87dbefaa/diff:/var/lib/containers/storage/overlay/aeadf59a9ef5cc68d85871b7d0929d8832cb4a42932b77c1cde666b08acd3ebc/diff:/var/lib/containers/storage/overlay/95af55abf662400ea716ddd0578fe0ebb422c51a4b9bd589948f9a7bd0c3c2f3/diff:/var/lib/containers/storage/overlay/f2b0cf9012b3bee126f6f2237c05b4ac5e28d57d37a0016e9b8d9914eeb35c83/diff:/var/lib/containers/storage/overlay/1e5f9559b55402f099d4f8ca5db38c380ed5f2f3f076bd0c9ce010d1c19ca68b/diff:/var/lib/containers/storage/overlay/55bb3ff453a1aafa5164b8cfaf3cdb5193f8c5143d07106f8a4b433b979142f0/diff:/var/lib/containers/storage/overlay/8367a1ad35f396963e3805003f49a92222c3601a533719777fe86625572fc451/diff:/var/lib/containers/storage/overlay/3872dfd8f4fb6816b8d2eeb8d6e7e0db9234ae285d66c1fc6714e4cc66302aa0/diff:/var/lib/containers/storage/overlay/196769cb28726ec9b449395a352ce66af812bb65fdd95ee9361d42bf8253e1df/diff:/var/lib/containers/storage/overlay/bbfe54dcde3d04921fd89feb42965fcf70d91c97da483bf3bfbf5d94cdb610b2/diff:/var/lib/containers/storage/overlay/0dcdd64a22d2b9a0cbb1e8111a2606c6d23ebab2adc25c19744240b7e808fa09/diff:/var/lib/containers/storage/overlay/17693417c0fc0d781131889b0fb55bd4956ed889e90d8392cbf6b3d3522d307a/diff:/var/lib/containers/storage/overlay/1a7ba622bd101a5b4b7a562cc6ca4b0539f7486f42d2e83c0680af481741555d/diff:/var/lib/containers/storage/overlay/aef6d34930ac84a66c930ab6e70c8ecd8bf74db73dbaa28b39bb6235fee09dfa/diff:/var/lib/containers/storage/overlay/53d77b07f2e74bd91962636520faf9f8b0c6f06fb1e6b662964a10a31dd2ff7b/diff:/var/lib/containers/storage/overlay/5a405a5311607addbd1afd56e8a4bc2b4c79fd7fc79697f0123caf55fb3f94e5/diff:/var/lib/containers/storage/overlay/0a166aac1271aababc2fa9e6d78ef1d65d257933219ea490f8f3301dbdb4c09b/diff",
                    "MergedDir": "/var/lib/containers/storage/overlay/9f3f490b4806855e1a62e424cd43cfbbeef0f1c7a7d452bc68063c7bb71c9cd8/merged",
                    "UpperDir": "/var/lib/containers/storage/overlay/9f3f490b4806855e1a62e424cd43cfbbeef0f1c7a7d452bc68063c7bb71c9cd8/diff",
                    "WorkDir": "/var/lib/containers/storage/overlay/9f3f490b4806855e1a62e424cd43cfbbeef0f1c7a7d452bc68063c7bb71c9cd8/work"
               }
          },
          "Mounts": [],
          "Dependencies": [],
          "NetworkSettings": {
               "EndpointID": "",
               "Gateway": "10.88.0.1",
               "IPAddress": "10.88.2.199",
               "IPPrefixLen": 16,
               "IPv6Gateway": "",
               "GlobalIPv6Address": "",
               "GlobalIPv6PrefixLen": 0,
               "MacAddress": "ea:59:69:b9:fa:4c",
               "Bridge": "",
               "SandboxID": "",
               "HairpinMode": false,
               "LinkLocalIPv6Address": "",
               "LinkLocalIPv6PrefixLen": 0,
               "Ports": {},
               "SandboxKey": "/run/netns/netns-d16b17d8-bd62-82a7-2882-a858f60fd885",
               "Networks": {
                    "podman": {
                         "EndpointID": "",
                         "Gateway": "10.88.0.1",
                         "IPAddress": "10.88.2.199",
                         "IPPrefixLen": 16,
                         "IPv6Gateway": "",
                         "GlobalIPv6Address": "",
                         "GlobalIPv6PrefixLen": 0,
                         "MacAddress": "ea:59:69:b9:fa:4c",
                         "NetworkID": "podman",
                         "DriverOpts": null,
                         "IPAMConfig": null,
                         "Links": null,
                         "Aliases": [
                              "5c14d0b09747"
                         ]
                    }
               }
          },
          "Namespace": "",
          "IsInfra": false,
          "IsService": false,
          "Config": {
               "Hostname": "5c14d0b09747",
               "Domainname": "",
               "User": "",
               "AttachStdin": false,
               "AttachStdout": false,
               "AttachStderr": false,
               "Tty": true,
               "OpenStdin": true,
               "StdinOnce": false,
               "Env": [
                    "container=podman",
                    "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                    "TERM=xterm",
                    "HOME=/root",
                    "HOSTNAME=5c14d0b09747"
               ],
               "Cmd": [
                    "bash"
               ],
               "Image": "docker.corp.arista.io/orca/mockd-mockd-trunk-x86_64_el7:31761530",
               "Volumes": null,
               "WorkingDir": "/",
               "Entrypoint": "/usr/bin/dumb-init --",
               "OnBuild": null,
               "Labels": {
                    "a4cBuildVersion": "6a23b7abeb",
                    "changeNum": "31761530",
                    "extraMounts": "",
                    "owner": "arastra",
                    "ownerID": "",
                    "platform": "x86_64_el7",
                    "primaryBranch": "mockd-trunk",
                    "project": "mockd-trunk",
                    "provider": "orca",
                    "service": "Mockd",
                    "timestamp": "2023-05-08 09:29"
               },
               "Annotations": {
                    "io.container.manager": "libpod",
                    "io.podman.annotations.autoremove": "TRUE",
                    "org.opencontainers.image.stopSignal": "15"
               },
               "StopSignal": 15,
               "HealthcheckOnFailureAction": "none",
               "CreateCommand": [
                    "/usr/bin/podman",
                    "run",
                    "--rm",
                    "-it",
                    "80a7b9f51310",
                    "bash"
               ],
               "Umask": "0022",
               "Timeout": 0,
               "StopTimeout": 10,
               "Passwd": true,
               "sdNotifyMode": "container"
          },
          "HostConfig": {
               "Binds": [],
               "CgroupManager": "systemd",
               "CgroupMode": "private",
               "ContainerIDFile": "",
               "LogConfig": {
                    "Type": "journald",
                    "Config": null,
                    "Path": "",
                    "Tag": "",
                    "Size": "0B"
               },
               "NetworkMode": "bridge",
               "PortBindings": {},
               "RestartPolicy": {
                    "Name": "",
                    "MaximumRetryCount": 0
               },
               "AutoRemove": true,
               "VolumeDriver": "",
               "VolumesFrom": null,
               "CapAdd": [],
               "CapDrop": [],
               "Dns": [],
               "DnsOptions": [],
               "DnsSearch": [],
               "ExtraHosts": [],
               "GroupAdd": [],
               "IpcMode": "shareable",
               "Cgroup": "",
               "Cgroups": "default",
               "Links": null,
               "OomScoreAdj": 0,
               "PidMode": "private",
               "Privileged": false,
               "PublishAllPorts": false,
               "ReadonlyRootfs": false,
               "SecurityOpt": [],
               "Tmpfs": {},
               "UTSMode": "private",
               "UsernsMode": "",
               "ShmSize": 65536000,
               "Runtime": "oci",
               "ConsoleSize": [
                    0,
                    0
               ],
               "Isolation": "",
               "CpuShares": 0,
               "Memory": 0,
               "NanoCpus": 0,
               "CgroupParent": "",
               "BlkioWeight": 0,
               "BlkioWeightDevice": null,
               "BlkioDeviceReadBps": null,
               "BlkioDeviceWriteBps": null,
               "BlkioDeviceReadIOps": null,
               "BlkioDeviceWriteIOps": null,
               "CpuPeriod": 0,
               "CpuQuota": 0,
               "CpuRealtimePeriod": 0,
               "CpuRealtimeRuntime": 0,
               "CpusetCpus": "",
               "CpusetMems": "",
               "Devices": [],
               "DiskQuota": 0,
               "KernelMemory": 0,
               "MemoryReservation": 0,
               "MemorySwap": 0,
               "MemorySwappiness": 0,
               "OomKillDisable": false,
               "PidsLimit": 2048,
               "Ulimits": [
                    {
                         "Name": "RLIMIT_NOFILE",
                         "Soft": 1048576,
                         "Hard": 1048576
                    },
                    {
                         "Name": "RLIMIT_NPROC",
                         "Soft": 4194304,
                         "Hard": 4194304
                    }
               ],
               "CpuCount": 0,
               "CpuPercent": 0,
               "IOMaximumIOps": 0,
               "IOMaximumBandwidth": 0,
               "CgroupConf": null
          }
     }
]
```

**Comment by 125priyank** [comment]
No, I am using podman network only. You can see the 'podman inspect' output
```
"NetworkSettings": {
               "EndpointID": "",
               "Gateway": "10.88.0.1",
               "IPAddress": "10.88.2.199",
               "IPPrefixLen": 16,
               "IPv6Gateway": "",
               "GlobalIPv6Address": "",
               "GlobalIPv6PrefixLen": 0,
               "MacAddress": "ea:59:69:b9:fa:4c",
               "Bridge": "",
               "SandboxID": "",
               "HairpinMode": false,
               "LinkLocalIPv6Address": "",
               "LinkLocalIPv6PrefixLen": 0,
               "Ports": {},
               "SandboxKey": "/run/netns/netns-d16b17d8-bd62-82a7-2882-a858f60fd885",
               "Networks": {
                    "podman": {
                         "EndpointID": "",
                         "Gateway": "10.88.0.1",
                         "IPAddress": "10.88.2.199",
                         "IPPrefixLen": 16,
                         "IPv6Gateway": "",
                         "GlobalIPv6Address": "",
                         "GlobalIPv6PrefixLen": 0,
                         "MacAddress": "ea:59:69:b9:fa:4c",
                         "NetworkID": "podman",
                         "DriverOpts": null,
                         "IPAMConfig": null,
                         "Links": null,
                         "Aliases": [
                              "5c14d0b09747"
                         ]
                    }
               }
          },
```

On the host the script runs fine with no network connection timing out.

**Comment by Luap99** [comment]
Were are you connecting to? Can you try to connect to an ip on your host, I don't think podman is doing anything special here. Does it work if you increase the timeout?

**Comment by 125priyank** [comment]
> Were are you connecting to? 

For my use case, I wanted to connect to an intranet server but this network timeout is happening for local, intranet, WAN connect.
> Can you try to connect to an ip on your host, I don't think podman is doing anything special here. 

I tried, still getting timeout
> Does it work if you increase the timeout?

No, still getting connection timeout for a 10-second timeout.

**Comment by kthommandra** [comment]
some more debugging information -

1.The above test loop runs fine, without any connect timeouts when there are no containers being created concurrently.
2.Along with the above test loop, if we run one/more loops where we are just creating and destroying more podman rootful containers then we can very easily see "stalls" during connect and eventually hitting the timeout.
Something like
```
while true
do
  sudo podman run --rm -it nicolaka/netshoot date
done
```
The stall and connect timeout happens pretty much within 5 mins of running the test loop.

The above issue does not happen at all with docker containers. As per the docs, rootful podman containers are wired in the same way as docker containers in terms of iptables and Linux bridge connections. So not sure what difference is causing this.

If we don't run the podman run command loops (2) then the connect timeouts do not happen.

Using tcpdump we have verified that, when the "connect" timesout, we can see the SYN packet as outgoing in the container, reaching podman0 and not going out over the host interface. The "connect" is being done to an intranet service and most of the times the connection succeeds. There is no issue with the intranet service.

We suspect the packet is getting dropped somewhere in the host stack but not sure why this issue happens only sometimes. 

If the test loop is run on the host then also there is no connect timeout. We suspect something during "podman run" is slowing down the "connect" call in the kernel. Some contention with iptables/conntrack etc.

Note that "ping" from inside the container to the intranet host with the service runs without any issues. It is only the TCP traffic that seems be impacted.

We plan to try and gather more details with nftrace and see if that provides some clues.

**Comment by Luap99** [comment]
Thanks @kthommandra, that is useful information.

When you create/destroy other containers concurrently do they run in a different network? This could be similar to https://github.com/containers/netavark/issues/210.

Can you reproduce this with a recent kernel? This could be some kernel bug. I am not sure why packages would be dropped.

**Comment by kthommandra** [comment]
All the create/destroy podman containers are being done in the same network podman0.
The kernel version we used was 5.10.62

We will try recreate with a recent kernel and update this thread.

Isn't this reasily recreatable on your end?

**Comment by 125priyank** [comment]
@Luap99 The connect timeout is reproducible in kernel 6.4.3 too. This does not seem a kernel bug.

**Comment by Luap99** [comment]
> Isn't this reasily recreatable on your end?

No, I have no idea what your environment looks like and what you are running in parallel etc...
I can run your script (with a different ip of course) without any problems

**Comment by 125priyank** [comment]
> No, I have no idea what your environment looks like and what you are running in parallel etc...

We are not running anything on this server, its a fresh server with only podman running.

### To reproduce the error

1. In one of the terminal create a container with this `sudo podman run --rm -it nicolaka/netshoot bash`
1.1.  Copy and run this script inside this container
```
#!/usr/bin/env python3
import socket
import time

server='142.251.46.174'
port=80

conn = 1
while True:
  s = socket.socket()
  s.settimeout(3)
  print( "connecting..." )
  s.connect( (server, port))
  print( "connected." )
  time.sleep(1)
  s.close()
  print( "connection {}".format( conn ) )
  conn += 1
```

2. In the second terminal run this
```
while true
do
  sudo podman run --rm -it nicolaka/netshoot date
done
```

3. Error received: Within 5 mins you would see this error for the python script you ran inside the container
```
connection 6
connecting...
Traceback (most recent call last):
  File "/root/script.py", line 13, in <module>
    s.connect( (server, port))
TimeoutError: timed out
```

### Environment details

- CPU
```
Architecture:            x86_64
Model name:            Intel(R) Xeon(R) Gold 5318Y CPU @ 2.10GHz
CPU max MHz:         3400.0000
CPU min MHz:         800.0000
BogoMIPS:            4200.00
```

- RAM -  503Gi

- Kernel 

```
uname -a
Linux host 6.4.3-1.el9.elrepo.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Jul 11 13:52:25 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux
```

- OS

```
cat /etc/os-release
NAME="AlmaLinux"
VERSION="9.2 (Turquoise Kodkod)"
ID="almalinux"
```

- Disk : SSDs

- internet speed test

```
sudo ethtool macvlan-bond0 | grep Speed
        Speed: 20000Mb/s
```

```
speedtest-cli
Retrieving speedtest.net configuration...
Testing download speed................................................................................
Download: 496.56 Mbit/s
Testing upload speed......................................................................................................
Upload: 277.30 Mbit/s
```
I followed this article to upgrade my kernel version from 5.10 to 6.4.3 - [link](https://wiki.crowncloud.net/?Installing_the_Linux_Kernel_6x_on_AlmaLinux_9#:~:text=Installing%20the%20Linux%20Kernel%206,x%20on%20AlmaLinux%209&text=It%20is%20designed%20to%20be,software%2C%20including%20the%20Linux%20kernel)

**Comment by Luap99** [comment]
No I had it running for about 500 iterations without an issue. I don't have time to debug further right now.

**Comment by Luap99** [comment]
As I was not able to reproduce nor have anything heard since then I am going to close

**Comment by Galaxy102** [comment]
I also ran into this issue and had to analyze and fix it to satisfy a customer of ours.

I was able to reproduce this issue under the following circumstances using only one host:
- You use Enterprise Linux (Alma, Rocky, RHEL)
- You have two bridge networks, net0 and net1 (name arbitrary)
- You have one container on net0 which publishes ports
- You have a second container (host does also work) on net0 and net1
- The issue occurs for any outbound communication that leaves on the network interface corresponding to net0 (this is a random component - sometime the packets leave on one interface, sometimes on the other one!)

You can see the whole thing in action at https://github.com/Galaxy102/podman-el-network-issue-showcase

The solution is to set the `sysctl` `net.ipv4.conf.default.rp_filter` to `2` before creating the podman networks.

**Comment by Luap99** [comment]
> The solution is to set the sysctl net.ipv4.conf.default.rp_filter to 2

this is fixed in https://github.com/containers/netavark/pull/962

But I don't see how this is related to the original report here as it doesn't mention port forwarding at all.
