### ISSUE TITLE
panic upon exiting from `podman unshare`

### ISSUE THREAD

**Issue by kolyshkin** [containers/podman#19198]
### Issue Description

I ran podman unshare yesterday (did `podman pull`, `podman mount` etc). My ~/.local/share/containers is a symlink to an external drive, which I have unmounted before putting the laptop to sleep.

This morning I exited from `podman unshare`, while the external drive was not connected. Upon exiting, I got the following panic:

```
[root@kir-rhat check-payload]$ 
exit
panic: creating lock file directory: mkdir /home/kir/.local/share/containers: file exists

goroutine 1 [running]:
panic({0x55e3083edac0, 0xc000bf4020})
	/usr/lib/golang/src/runtime/panic.go:987 +0x3bb fp=0xc000c8f900 sp=0xc000c8f840 pc=0x55e306c041bb
github.com/containers/podman/vendor/github.com/containers/storage/pkg/lockfile.(*LockFile).lock(0xc0007164e0, 0x1)
	/builddir/build/BUILD/podman-4.5.1/_build/src/github.com/containers/podman/vendor/github.com/containers/storage/pkg/lockfile/lockfile_unix.go:208 +0x21d fp=0xc000c8f9a0 sp=0xc000c8f900 pc=0x55e306fb21fd
github.com/containers/podman/vendor/github.com/containers/storage/pkg/lockfile.(*LockFile).Lock(...)
	/builddir/build/BUILD/podman-4.5.1/_build/src/github.com/containers/podman/vendor/github.com/containers/storage/pkg/lockfile/lockfile_unix.go:229
github.com/containers/podman/vendor/github.com/containers/storage.(*store).startUsingGraphDriver(0xc0004fa300?)
	/builddir/build/BUILD/podman-4.5.1/_build/src/github.com/containers/podman/vendor/github.com/containers/storage/store.go:944 +0x65 fp=0xc000c8fa58 sp=0xc000c8f9a0 pc=0x55e30753f005
github.com/containers/podman/vendor/github.com/containers/storage.(*store).Shutdown(0xc0004fa300, 0x0)
	/builddir/build/BUILD/podman-4.5.1/_build/src/github.com/containers/podman/vendor/github.com/containers/storage/store.go:3310 +0x69 fp=0xc000c8fd10 sp=0xc000c8fa58 pc=0x55e307556ac9
github.com/containers/podman/vendor/github.com/containers/common/libimage.(*Runtime).Shutdown(...)
	/builddir/build/BUILD/podman-4.5.1/_build/src/github.com/containers/podman/vendor/github.com/containers/common/libimage/runtime.go:143
github.com/containers/podman/libpod.(*Runtime).Shutdown(0xc0002321e0, 0x0)
	/builddir/build/BUILD/podman-4.5.1/_build/src/github.com/containers/podman/libpod/runtime.go:824 +0x1ab fp=0xc000c8fe10 sp=0xc000c8fd10 pc=0x55e307accaab
github.com/containers/podman/pkg/domain/infra/abi.(*ImageEngine).Shutdown.func1()
	/builddir/build/BUILD/podman-4.5.1/_build/src/github.com/containers/podman/pkg/domain/infra/abi/images.go:603 +0x25 fp=0xc000c8fe30 sp=0xc000c8fe10 pc=0x55e307b879e5
sync.(*Once).doSlow(0x55e3083e3440?, 0x55e308606c60?)
	/usr/lib/golang/src/sync/once.go:74 +0xc2 fp=0xc000c8fe90 sp=0xc000c8fe30 pc=0x55e306c45c22
sync.(*Once).Do(...)
	/usr/lib/golang/src/sync/once.go:65
github.com/containers/podman/pkg/domain/infra/abi.(*ImageEngine).Shutdown(0x55e30926fa00?, {0xc000044110?, 0x55e307f1e604?})
	/builddir/build/BUILD/podman-4.5.1/_build/src/github.com/containers/podman/pkg/domain/infra/abi/images.go:602 +0x46 fp=0xc000c8fec0 sp=0xc000c8fe90 pc=0x55e307b87986
main.Execute()
	/builddir/build/BUILD/podman-4.5.1/_build/src/github.com/containers/podman/cmd/podman/root.go:127 +0x229 fp=0xc000c8ff50 sp=0xc000c8fec0 pc=0x55e307e031e9
main.main()
	/builddir/build/BUILD/podman-4.5.1/_build/src/github.com/containers/podman/cmd/podman/main.go:41 +0x7c fp=0xc000c8ff80 sp=0xc000c8ff50 pc=0x55e307e0273c
runtime.main()
	/usr/lib/golang/src/runtime/proc.go:250 +0x212 fp=0xc000c8ffe0 sp=0xc000c8ff80 pc=0x55e306c06ef2
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000c8ffe8 sp=0xc000c8ffe0 pc=0x55e306c3aee1

goroutine 2 [force gc (idle), 3 minutes]:
runtime.gopark(0x207f65ac340?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:381 +0xd6 fp=0xc000072fb0 sp=0xc000072f90 pc=0x55e306c07336
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:387
runtime.forcegchelper()
	/usr/lib/golang/src/runtime/proc.go:305 +0xb0 fp=0xc000072fe0 sp=0xc000072fb0 pc=0x55e306c07170
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000072fe8 sp=0xc000072fe0 pc=0x55e306c3aee1
created by runtime.init.7
	/usr/lib/golang/src/runtime/proc.go:293 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:381 +0xd6 fp=0xc000073780 sp=0xc000073760 pc=0x55e306c07336
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
	/usr/lib/golang/src/runtime/mgcsweep.go:319 +0xde fp=0xc0000737c8 sp=0xc000073780 pc=0x55e306bf18be
runtime.gcenable.func1()
	/usr/lib/golang/src/runtime/mgc.go:178 +0x26 fp=0xc0000737e0 sp=0xc0000737c8 pc=0x55e306be6b26
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000737e8 sp=0xc0000737e0 pc=0x55e306c3aee1
created by runtime.gcenable
	/usr/lib/golang/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x1b422c79fc9?, 0x11f407?, 0x0?, 0x0?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:381 +0xd6 fp=0xc000073f70 sp=0xc000073f50 pc=0x55e306c07336
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:387
runtime.(*scavengerState).park(0x55e30934fe20)
	/usr/lib/golang/src/runtime/mgcscavenge.go:400 +0x53 fp=0xc000073fa0 sp=0xc000073f70 pc=0x55e306bef793
runtime.bgscavenge(0x0?)
	/usr/lib/golang/src/runtime/mgcscavenge.go:633 +0x65 fp=0xc000073fc8 sp=0xc000073fa0 pc=0x55e306befd85
runtime.gcenable.func2()
	/usr/lib/golang/src/runtime/mgc.go:179 +0x26 fp=0xc000073fe0 sp=0xc000073fc8 pc=0x55e306be6ac6
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000073fe8 sp=0xc000073fe0 pc=0x55e306c3aee1
created by runtime.gcenable
	/usr/lib/golang/src/runtime/mgc.go:179 +0xaa

goroutine 5 [finalizer wait, 17 minutes]:
runtime.gopark(0x1a0?, 0x55e309351fa0?, 0x60?, 0x78?, 0xc000072770?)
	/usr/lib/golang/src/runtime/proc.go:381 +0xd6 fp=0xc000072628 sp=0xc000072608 pc=0x55e306c07336
runtime.runfinq()
	/usr/lib/golang/src/runtime/mfinal.go:193 +0x107 fp=0xc0000727e0 sp=0xc000072628 pc=0x55e306be5b47
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000727e8 sp=0xc0000727e0 pc=0x55e306c3aee1
created by runtime.createfing
	/usr/lib/golang/src/runtime/mfinal.go:163 +0x45

goroutine 6 [GC worker (idle), 17 minutes]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:381 +0xd6 fp=0xc000074750 sp=0xc000074730 pc=0x55e306c07336
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1275 +0xf1 fp=0xc0000747e0 sp=0xc000074750 pc=0x55e306be8891
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000747e8 sp=0xc0000747e0 pc=0x55e306c3aee1
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1199 +0x25

goroutine 18 [GC worker (idle), 17 minutes]:
runtime.gopark(0x12854181681?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:381 +0xd6 fp=0xc00006e750 sp=0xc00006e730 pc=0x55e306c07336
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1275 +0xf1 fp=0xc00006e7e0 sp=0xc00006e750 pc=0x55e306be8891
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00006e7e8 sp=0xc00006e7e0 pc=0x55e306c3aee1
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1199 +0x25

goroutine 34 [GC worker (idle), 17 minutes]:
runtime.gopark(0x128541c41ec?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:381 +0xd6 fp=0xc000494750 sp=0xc000494730 pc=0x55e306c07336
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1275 +0xf1 fp=0xc0004947e0 sp=0xc000494750 pc=0x55e306be8891
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0004947e8 sp=0xc0004947e0 pc=0x55e306c3aee1
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1199 +0x25

goroutine 35 [GC worker (idle)]:
runtime.gopark(0x207f79b2541?, 0x1?, 0xa9?, 0xd1?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:381 +0xd6 fp=0xc000494f50 sp=0xc000494f30 pc=0x55e306c07336
runtime.gcBgMarkWorker()
	/usr/lib/golang/src/runtime/mgc.go:1275 +0xf1 fp=0xc000494fe0 sp=0xc000494f50 pc=0x55e306be8891
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000494fe8 sp=0xc000494fe0 pc=0x55e306c3aee1
created by runtime.gcBgMarkStartWorkers
	/usr/lib/golang/src/runtime/mgc.go:1199 +0x25

goroutine 7 [select, 17 minutes, locked to thread]:
runtime.gopark(0xc00006ffa8?, 0x2?, 0x0?, 0x0?, 0xc00006ffa4?)
	/usr/lib/golang/src/runtime/proc.go:381 +0xd6 fp=0xc00006fe18 sp=0xc00006fdf8 pc=0x55e306c07336
runtime.selectgo(0xc00006ffa8, 0xc00006ffa0, 0x0?, 0x0, 0x0?, 0x1)
	/usr/lib/golang/src/runtime/select.go:327 +0x7be fp=0xc00006ff58 sp=0xc00006fe18 pc=0x55e306c1785e
runtime.ensureSigM.func1()
	/usr/lib/golang/src/runtime/signal_unix.go:1000 +0x1b4 fp=0xc00006ffe0 sp=0xc00006ff58 pc=0x55e306c321d4
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00006ffe8 sp=0xc00006ffe0 pc=0x55e306c3aee1
created by runtime.ensureSigM
	/usr/lib/golang/src/runtime/signal_unix.go:983 +0xbd

goroutine 50 [syscall, 17 minutes]:
runtime.notetsleepg(0x0?, 0x0?)
	/usr/lib/golang/src/runtime/lock_futex.go:236 +0x34 fp=0xc0004957a0 sp=0xc000495768 pc=0x55e306bd99d4
os/signal.signal_recv()
	/usr/lib/golang/src/runtime/sigqueue.go:152 +0x2f fp=0xc0004957c0 sp=0xc0004957a0 pc=0x55e306c3726f
os/signal.loop()
	/usr/lib/golang/src/os/signal/signal_unix.go:23 +0x19 fp=0xc0004957e0 sp=0xc0004957c0 pc=0x55e306f997d9
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0004957e8 sp=0xc0004957e0 pc=0x55e306c3aee1
created by os/signal.Notify.func1.1
	/usr/lib/golang/src/os/signal/signal.go:151 +0x2a

goroutine 36 [select, 17 minutes]:
runtime.gopark(0xc0004907b0?, 0x2?, 0x0?, 0x0?, 0xc0004906ac?)
	/usr/lib/golang/src/runtime/proc.go:381 +0xd6 fp=0xc000490518 sp=0xc0004904f8 pc=0x55e306c07336
runtime.selectgo(0xc0004907b0, 0xc0004906a8, 0x0?, 0x0, 0x0?, 0x1)
	/usr/lib/golang/src/runtime/select.go:327 +0x7be fp=0xc000490658 sp=0xc000490518 pc=0x55e306c1785e
github.com/containers/podman/libpod/shutdown.Start.func1()
	/builddir/build/BUILD/podman-4.5.1/_build/src/github.com/containers/podman/libpod/shutdown/handler.go:48 +0x93 fp=0xc0004907e0 sp=0xc000490658 pc=0x55e3079658f3
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0004907e8 sp=0xc0004907e0 pc=0x55e306c3aee1
created by github.com/containers/podman/libpod/shutdown.Start
	/builddir/build/BUILD/podman-4.5.1/_build/src/github.com/containers/podman/libpod/shutdown/handler.go:47 +0xe7

goroutine 37 [chan receive, 17 minutes]:
runtime.gopark(0xc000490f28?, 0x55e306c3f1e5?, 0x28?, 0xf?, 0x55e306d09026?)
	/usr/lib/golang/src/runtime/proc.go:381 +0xd6 fp=0xc000490f00 sp=0xc000490ee0 pc=0x55e306c07336
runtime.chanrecv(0xc00057c180, 0x0, 0x1)
	/usr/lib/golang/src/runtime/chan.go:583 +0x49d fp=0xc000490f90 sp=0xc000490f00 pc=0x55e306bd419d
runtime.chanrecv1(0xc0002f0050?, 0x0?)
	/usr/lib/golang/src/runtime/chan.go:442 +0x18 fp=0xc000490fb8 sp=0xc000490f90 pc=0x55e306bd3c98
github.com/containers/podman/vendor/github.com/godbus/dbus/v5.newConn.func1()
	/builddir/build/BUILD/podman-4.5.1/_build/src/github.com/containers/podman/vendor/github.com/godbus/dbus/v5/conn.go:302 +0x32 fp=0xc000490fe0 sp=0xc000490fb8 pc=0x55e30726be72
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000490fe8 sp=0xc000490fe0 pc=0x55e306c3aee1
created by github.com/containers/podman/vendor/github.com/godbus/dbus/v5.newConn
	/builddir/build/BUILD/podman-4.5.1/_build/src/github.com/containers/podman/vendor/github.com/godbus/dbus/v5/conn.go:301 +0x4f6

goroutine 19 [IO wait, 17 minutes]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/golang/src/runtime/proc.go:381 +0xd6 fp=0xc000625a38 sp=0xc000625a18 pc=0x55e306c07336
runtime.netpollblock(0x0?, 0x6bd0a2f?, 0xe3?)
	/usr/lib/golang/src/runtime/netpoll.go:527 +0xf7 fp=0xc000625a70 sp=0xc000625a38 pc=0x55e306bffb57
internal/poll.runtime_pollWait(0x7f0e5a994328, 0x72)
	/usr/lib/golang/src/runtime/netpoll.go:306 +0x89 fp=0xc000625a90 sp=0xc000625a70 pc=0x55e306c34a89
internal/poll.(*pollDesc).wait(0xc00078e480?, 0xc0001d7d40?, 0x0)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:84 +0x32 fp=0xc000625ab8 sp=0xc000625a90 pc=0x55e306cb87b2
internal/poll.(*pollDesc).waitRead(...)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).ReadMsg(0xc00078e480, {0xc0001d7d40, 0x10, 0x10}, {0xc0004e1920, 0x1000, 0x1000}, 0x70000c000076800?)
	/usr/lib/golang/src/internal/poll/fd_unix.go:304 +0x3aa fp=0xc000625ba8 sp=0xc000625ab8 pc=0x55e306cbaeaa
net.(*netFD).readMsg(0xc00078e480, {0xc0001d7d40?, 0x55e3092be198?, 0xc000781240?}, {0xc0004e1920?, 0xc0001d76fe?, 0xc0001d76f8?}, 0xc0001d76f4?)
	/usr/lib/golang/src/net/fd_posix.go:78 +0x37 fp=0xc000625c30 sp=0xc000625ba8 pc=0x55e306ddb137
net.(*UnixConn).readMsg(0xc0004b2068, {0xc0001d7d40?, 0xc0004d8830?, 0x55e308615ea0?}, {0xc0004e1920?, 0x55e30862bd80?, 0x55e309386828?})
	/usr/lib/golang/src/net/unixsock_posix.go:115 +0x4f fp=0xc000625cc0 sp=0xc000625c30 pc=0x55e306dff38f
net.(*UnixConn).ReadMsgUnix(0xc0004b2068, {0xc0001d7d40?, 0xc000625d50?, 0x55e306c07420?}, {0xc0004e1920?, 0x55e306bdaeea?, 0xc00078a7e0?})
	/usr/lib/golang/src/net/unixsock.go:143 +0x3c fp=0xc000625d38 sp=0xc000625cc0 pc=0x55e306dfcf3c
github.com/containers/podman/vendor/github.com/godbus/dbus/v5.(*oobReader).Read(0xc0004e1900, {0xc0001d7d40?, 0xc000625de8?, 0x55e306bdb2c7?})
	/builddir/build/BUILD/podman-4.5.1/_build/src/github.com/containers/podman/vendor/github.com/godbus/dbus/v5/transport_unix.go:22 +0x45 fp=0xc000625db0 sp=0xc000625d38 pc=0x55e3072849c5
io.ReadAtLeast({0x55e308617160, 0xc0004e1900}, {0xc0001d7d40, 0x10, 0x10}, 0x10)
	/usr/lib/golang/src/io/io.go:332 +0x9a fp=0xc000625df8 sp=0xc000625db0 pc=0x55e306c47b5a
io.ReadFull(...)
	/usr/lib/golang/src/io/io.go:351
github.com/containers/podman/vendor/github.com/godbus/dbus/v5.(*unixTransport).ReadMessage(0xc0005f0780)
	/builddir/build/BUILD/podman-4.5.1/_build/src/github.com/containers/podman/vendor/github.com/godbus/dbus/v5/transport_unix.go:92 +0x11e fp=0xc000625f58 sp=0xc000625df8 pc=0x55e307284fde
github.com/containers/podman/vendor/github.com/godbus/dbus/v5.(*Conn).inWorker(0xc0006fe000)
	/builddir/build/BUILD/podman-4.5.1/_build/src/github.com/containers/podman/vendor/github.com/godbus/dbus/v5/conn.go:389 +0x48 fp=0xc000625fc8 sp=0xc000625f58 pc=0x55e30726c348
github.com/containers/podman/vendor/github.com/godbus/dbus/v5.(*Conn).Auth.func1()
	/builddir/build/BUILD/podman-4.5.1/_build/src/github.com/containers/podman/vendor/github.com/godbus/dbus/v5/auth.go:118 +0x26 fp=0xc000625fe0 sp=0xc000625fc8 pc=0x55e307269546
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000625fe8 sp=0xc000625fe0 pc=0x55e306c3aee1
created by github.com/containers/podman/vendor/github.com/godbus/dbus/v5.(*Conn).Auth
	/builddir/build/BUILD/podman-4.5.1/_build/src/github.com/containers/podman/vendor/github.com/godbus/dbus/v5/auth.go:118 +0x99c
[kir@kir-rhat check-payload]$ 
```

### Steps to reproduce the issue

Steps to reproduce the issue
1. podman unshare
2. ???
3. Ctrl-D

### Describe the results you received

See above

### Describe the results you expected

Perhaps downgrade the panic to an error.

### podman info output

```yaml
[kir@kir-rhat check-payload]$ podman info
Error: opening database /home/kir/.local/share/containers/storage/libpod/bolt_state.db: open /home/kir/.local/share/containers/storage/libpod/bolt_state.db: no such file or directory
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Fedora 38
podman-4.5.1-1.fc38.x86_64

### Additional information

I'm on PTO so can't look into it this week.

**Comment by Luap99** [comment]
Ok removing the underlying storage while podman is running is pretty bad and untested of course.
Should we handle it better? I think so but looking at your stack trace this seems difficult.

The panic comes out of the c/storage file locking code and the lock API has almost no error handling. `.Lock()` `.Unlock()` do not return errors so the only choice it has to ignore or panic for internal errors. If we have to add error handling for each lock that complicates the code quite a lot and even then it is not sure how to recover other returning the error. So in that case other than the bad ux a panic is likely not any worse.

And in general I would expect pretty much all code paths in podman to cause problems not just the locks here.

**Comment by rhatdan** [comment]
Agree this is not much we can do for this failure.
