### ISSUE TITLE
Frequent cleanup failures

### ISSUE THREAD

**Issue by martinpitt** [containers/podman#21872]
We keep getting failures due to our super-complicated setUp/tearDown/restore_dir() actions. A few days ago I tried commit 857ed44e91331a07d06a24ac13fbb36e6414860b and ab8108e410abaf9f05a604564fb6c5ec5857e7a7 , but that still didn't help enough.

E.g. yesterday/today we got failures in https://github.com/containers/podman/pull/21868 ([log](https://artifacts.dev.testing-farm.io/054faf4a-e921-4db7-a5b0-dbac0a0a771e/), [log](https://artifacts.dev.testing-farm.io/5a7d3b24-308f-4efd-be48-6c3ef4c2f4f5/)) due to
```
cp: cannot stat '/home/admin/.local/share/containers/storage/overlay/compat475205185': No such file or directory
Traceback (most recent call last):
  File "/var/ARTIFACTS/work-podman-userpjbprz5f/plans/cockpit-podman/podman-user/discover/default-0/tests/test/check-application", line 145, in setUp
    self.restore_dir("/home/admin/.local/share/containers")
  File "/var/ARTIFACTS/work-podman-userpjbprz5f/plans/cockpit-podman/podman-user/discover/default-0/tests/test/common/testlib.py", line 2050, in restore_dir
    exe(f"mkdir -p {self.vm_tmpdir}; cp -a {path}/ {backup}/")
```

Same thing happened in https://github.com/containers/podman/pull/21778 [log](https://artifacts.dev.testing-farm.io/a31f431c-3bf9-4705-8a37-42f585caeb9e/).

I asked in https://github.com/containers/podman/pull/21592#issuecomment-1968282971 , but we are doing way too much here. I have an idea how to simplify/robustify this, let's see if it works out.

**Comment by martinpitt** [comment]
Crap, sorry -- this was meant for cockpit-podman. But yeah, FYI :grin:
