### ISSUE TITLE
podman multiple erros starting container

### ISSUE THREAD

**Issue by Arkadietz** [containers/podman#22674]
### Issue Description

Podman versions

```
docker@Azeroth ~/apps/qbittorrent $ podman version
Version:      3.4.2
API Version:  3.4.2
Go Version:   go1.15.2
Built:        Thu Jan  1 02:00:00 1970
OS/Arch:      linux/amd64
docker@Azeroth ~/apps/qbittorrent $ podman info
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - cpu
  - memory
  - pids
  cgroupManager: cgroupfs
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.1.2, commit: '
  cpus: 6
  distribution:
    codename: bookworm
    distribution: debian
    version: "12"
  eventLogger: file
  hostname: Azeroth
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  kernel: 6.1.0-20-amd64
  linkmode: dynamic
  logDriver: journald
  memFree: 10866941952
  memTotal: 16584306688
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version UNKNOWN
      commit: ea1fe3938eefa14eb707f1d22adff4db670645d6
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /tmp/podman-run-1001/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.1.8
      commit: unknown
      libslirp: 4.3.1-git
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.4
  swapFree: 3997167616
  swapTotal: 3997167616
  uptime: 186h 22m 39.8s (Approximately 7.75 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - quay.io
  - docker.io
store:
  configFile: /home/docker/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/docker/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 2
  runRoot: /tmp/podman-run-1001/containers
  volumePath: /home/docker/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.2
  Built: 0
```
  BuiltTime: Thu Jan  1 02:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 3.4.2

```
docker@Azeroth ~ $ uname -mr && podman version
6.1.0-20-amd64 x86_64
Version:      3.4.2
API Version:  3.4.2
Go Version:   go1.15.2
Built:        Thu Jan  1 02:00:00 1970
OS/Arch:      linux/amd64
docker@Azeroth ~ $ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

```
docker@Azeroth ~/apps $ podman pull qbittorrentofficial/qbittorrent-nox
Resolved "qbittorrentofficial/qbittorrent-nox" as an alias (/home/docker/.cache/containers/short-name-aliases.conf)
Trying to pull docker.io/qbittorrentofficial/qbittorrent-nox:latest...
Getting image source signatures
Copying blob 3570425b8f1d done
Copying blob fd818a4d8d6c done
Copying blob 0a13da45d5b0 done
Copying blob 2669e65add69 done
Copying blob ff3b09a66cb3 done
Copying blob 4abcf2066143 done
Copying blob 4af64fa45a11 done
Copying config 7556a96114 done
Writing manifest to image destination
Storing signatures
7556a96114a50e2d95a1e5e5c322d9257b80fc7bdb1ed4e9e423470f9b50acb1
```

```
docker@Azeroth ~/apps $ cat qbt-podman-compose.yaml
---
services:
    qbt:
    container_name: qbittorrent-nox
    image: qbittorrentofficial/qbittorrent-nox
    ports:
      # web ui port
      - 8080:8080/tcp
      # for bittorrent traffic
      - 6881:6881/tcp
      - 6881:6881/udp
    environment:
      - TZ=Europe/Sofia
      - UMASK_SET=022
      - QBT_EULA=accept
      - QBT_VERSION=latest
      - QBT_WEBUI_PORT=8080
    tty: true
    stop_grace_period: 30m
    tmpfs:
      - /tmp
    volumes:
      - /home/docker/apps/qbittorrent/config:/config:rw
      - /data/qBittorrent/torrents:/downloads:rw

docker@Azeroth ~/apps $ podman-compose -f qbt-podman-compose.yaml up
Traceback (most recent call last):
  File "/usr/local/bin/podman-compose", line 3313, in <module>
    main()
  File "/usr/local/bin/podman-compose", line 3309, in main
    asyncio.run(async_main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/bin/podman-compose", line 3305, in async_main
    await podman_compose.run()
  File "/usr/local/bin/podman-compose", line 1633, in run
    self._parse_compose_file()
  File "/usr/local/bin/podman-compose", line 1717, in _parse_compose_file
    content = normalize(content)
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/podman-compose", line 1413, in normalize
    normalize_service(service)
  File "/usr/local/bin/podman-compose", line 1365, in normalize_service
    if "build" in service:
       ^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

So please help me to resolve this issue.

### Steps to reproduce the issue

Steps to reproduce the issue
1.
2.
3.

### Describe the results you received

Describe the results you received

### Describe the results you expected

Describe the results you expected

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by rhatdan** [comment]
Podman-compose and podman are not the same thing.
