### ISSUE TITLE
file limits not being honored?

### ISSUE THREAD

**Issue by burhan** [containers/podman#7305]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Struggling to get a simple pod (rootless) and running into all kinds of problems that I am solving one by one. The latest one that has me stumped is I am running into a too many open files panic, where my hard and soft limits are `65535`.

The error is also a bit weird, but I understand why its saying that (note: the error output is not the real issue).

I have seen another bug with file permissions, but that was within the container, this seems to be from the host. If I run the same script from root, it works.

```
[me@localhost ~]$ ulimit -aH | grep files
open files                      (-n) 65535
[me@localhost ~]$ cat /etc/security/limits.d/20-nproc.conf
# Default limit for number of user's processes to prevent
# accidental fork bombs.
# See rhbz #432903 for reasoning.

*          soft    nproc     4096
*          soft    nofile    65535
*          hard    nofile    65535
root       soft    nproc     unlimited
```

**Describe the results you received:**

```
WARN[0000] The cgroups manager is set to systemd but there is no systemd user session available 
WARN[0000] For using systemd, you may need to login using an user session
WARN[0000] Alternatively, you can enable lingering with: `loginctl enable-linger 1000` (possibly as root)
WARN[0000] Falling back to --cgroup-manager=cgroupfs and --events-backend=file
DEBU[0000] Using conmon: "/usr/bin/conmon"
DEBU[0000] Initializing boltdb state at /home/me/.local/share/containers/storage/libpod/bolt_state.db
DEBU[0000] Using graph driver overlay
DEBU[0000] Using graph root /home/me/.local/share/containers/storage
DEBU[0000] Using run root /run/user/1000/containers
DEBU[0000] Using static dir /home/me/.local/share/containers/storage/libpod
DEBU[0000] Using tmp dir /run/user/1000/libpod/tmp
DEBU[0000] Using volume path /home/me/.local/share/containers/storage/volumes
DEBU[0000] Set libpod namespace to ""
DEBU[0000] Not configuring container store
DEBU[0000] Initializing event backend file
DEBU[0000] using runtime "/usr/bin/runc"
WARN[0000] The cgroups manager is set to systemd but there is no systemd user session available 
WARN[0000] For using systemd, you may need to login using an user session
WARN[0000] Alternatively, you can enable lingering with: `loginctl enable-linger 1000` (possibly as root)
WARN[0000] Falling back to --cgroup-manager=cgroupfs and --events-backend=file
DEBU[0000] Using conmon: "/usr/bin/conmon"
DEBU[0000] Initializing boltdb state at /home/me/.local/share/containers/storage/libpod/bolt_state.db
DEBU[0000] Using graph driver overlay
DEBU[0000] Using graph root /home/me/.local/share/containers/storage
DEBU[0000] Using run root /run/user/1000/containers
DEBU[0000] Using static dir /home/me/.local/share/containers/storage/libpod
DEBU[0000] Using tmp dir /run/user/1000/libpod/tmp
DEBU[0000] Using volume path /home/me/.local/share/containers/storage/volumes
DEBU[0000] Set libpod namespace to ""
DEBU[0000] [graphdriver] trying provided driver "overlay"
DEBU[0000] overlay: mount_program=/usr/bin/fuse-overlayfs
DEBU[0000] backingFs=xfs, projectQuotaSupported=false, useNativeDiff=false, usingMetacopy=false 
DEBU[0000] Initializing event backend file
DEBU[0000] using runtime "/usr/bin/runc"
DEBU[0000] Initialized SHM lock manager at path /libpod_rootless_lock_1000
DEBU[0000] Podman detected system restart - performing state refresh
DEBU[0000] setting pod cgroup to /libpod_parent/a233e93adc9c1fa51a2c5efe11f1713c17308e105c6420de9d142cfe3e968b18 
DEBU[0000] Failed to add podman to systemd sandbox cgroup: exec: "dbus-launch": executable file not found in $PATH
INFO[0000] running as rootless
WARN[0000] The cgroups manager is set to systemd but there is no systemd user session available
WARN[0000] For using systemd, you may need to login using an user session
WARN[0000] Alternatively, you can enable lingering with: `loginctl enable-linger 1000` (possibly as root)
WARN[0000] Falling back to --cgroup-manager=cgroupfs and --events-backend=file
DEBU[0000] Using conmon: "/usr/bin/conmon"
DEBU[0000] Initializing boltdb state at /home/me/.local/share/containers/storage/libpod/bolt_state.db
DEBU[0000] Using graph driver overlay
DEBU[0000] Using graph root /home/me/.local/share/containers/storage
DEBU[0000] Using run root /run/user/1000/containers
DEBU[0000] Using static dir /home/me/.local/share/containers/storage/libpod
DEBU[0000] Using tmp dir /run/user/1000/libpod/tmp
DEBU[0000] Using volume path /home/me/.local/share/containers/storage/volumes
DEBU[0000] Set libpod namespace to ""
DEBU[0000] Initializing event backend file
DEBU[0000] using runtime "/usr/bin/runc"
DEBU[0000] Cleaning up container 6becf512fd3f8f7979010269a0ce2a2f1c339293a96fae108f2c9fdd0ebbd529
DEBU[0000] Network is already cleaned up, skipping...
DEBU[0000] Container 6becf512fd3f8f7979010269a0ce2a2f1c339293a96fae108f2c9fdd0ebbd529 storage is already unmounted, skipping...
DEBU[0000] Container 6becf512fd3f8f7979010269a0ce2a2f1c339293a96fae108f2c9fdd0ebbd529 storage is already unmounted, skipping...
DEBU[0000] [graphdriver] trying provided driver "overlay"
DEBU[0000] overlay: mount_program=/usr/bin/fuse-overlayfs
DEBU[0000] backingFs=xfs, projectQuotaSupported=false, useNativeDiff=false, usingMetacopy=false
DEBU[0000] Removing pod cgroup /libpod_parent/a233e93adc9c1fa51a2c5efe11f1713c17308e105c6420de9d142cfe3e968b18 
a233e93adc9c1fa51a2c5efe11f1713c17308e105c6420de9d142cfe3e968b18
WARN[0000] The cgroups manager is set to systemd but there is no systemd user session available 
WARN[0000] For using systemd, you may need to login using an user session
WARN[0000] Alternatively, you can enable lingering with: `loginctl enable-linger 1000` (possibly as root)
WARN[0000] Falling back to --cgroup-manager=cgroupfs and --events-backend=file
DEBU[0000] Using conmon: "/usr/bin/conmon"
DEBU[0000] Initializing boltdb state at /home/me/.local/share/containers/storage/libpod/bolt_state.db
DEBU[0000] Using graph driver overlay
DEBU[0000] Using graph root /home/me/.local/share/containers/storage
DEBU[0000] Using run root /run/user/1000/containers
DEBU[0000] Using static dir /home/me/.local/share/containers/storage/libpod
DEBU[0000] Using tmp dir /run/user/1000/libpod/tmp
DEBU[0000] Using volume path /home/me/.local/share/containers/storage/volumes
DEBU[0000] Set libpod namespace to ""
DEBU[0000] [graphdriver] trying provided driver "overlay"
DEBU[0000] overlay: mount_program=/usr/bin/fuse-overlayfs
DEBU[0000] backingFs=xfs, projectQuotaSupported=false, useNativeDiff=false, usingMetacopy=false 
DEBU[0000] Initializing event backend file
DEBU[0000] using runtime "/usr/bin/runc"
DEBU[0000] Failed to add podman to systemd sandbox cgroup: exec: "dbus-launch": executable file not found in $PATH
INFO[0000] running as rootless
WARN[0000] The cgroups manager is set to systemd but there is no systemd user session available
WARN[0000] For using systemd, you may need to login using an user session
WARN[0000] Alternatively, you can enable lingering with: `loginctl enable-linger 1000` (possibly as root)
WARN[0000] Falling back to --cgroup-manager=cgroupfs and --events-backend=file
DEBU[0000] Using conmon: "/usr/bin/conmon"
DEBU[0000] Initializing boltdb state at /home/me/.local/share/containers/storage/libpod/bolt_state.db
DEBU[0000] Using graph driver overlay
DEBU[0000] Using graph root /home/me/.local/share/containers/storage
DEBU[0000] Using run root /run/user/1000/containers
DEBU[0000] Using static dir /home/me/.local/share/containers/storage/libpod
DEBU[0000] Using tmp dir /run/user/1000/libpod/tmp
DEBU[0000] Using volume path /home/me/.local/share/containers/storage/volumes
DEBU[0000] Set libpod namespace to ""
DEBU[0000] Initializing event backend file
DEBU[0000] using runtime "/usr/bin/runc"
DEBU[0000] Got pod cgroup as /libpod_parent/8f7f6727c09abbf684bb83b4dce64935ac71d6fcb8a53eb3dfce312099498121
DEBU[0000] parsed reference into "[overlay@/home/me/.local/share/containers/storage+/run/user/1000/containers:overlay.mount_program=/usr/bin/fuse-overlayfs]k8s.gcr.io/pause:3.1"
DEBU[0000] parsed reference into "[overlay@/home/me/.local/share/containers/storage+/run/user/1000/containers:overlay.mount_program=/usr/bin/fuse-overlayfs]@da86e6ba6ca197bf6bc5e9d900febd906b133eaa4750e6bed647b0fbe50ed43e"
DEBU[0000] [graphdriver] trying provided driver "overlay"
DEBU[0000] overlay: mount_program=/usr/bin/fuse-overlayfs
DEBU[0000] backingFs=xfs, projectQuotaSupported=false, useNativeDiff=false, usingMetacopy=false
DEBU[0000] exporting opaque data as blob "sha256:da86e6ba6ca197bf6bc5e9d900febd906b133eaa4750e6bed647b0fbe50ed43e" 
DEBU[0000] Using ["/pause"] as infra container entrypoint
DEBU[0000] Allocated lock 1 for container f1bc17dd6718b1edfd74abdb814b226d8908924c59fa09d2c8e9125695ec5b82
DEBU[0000] parsed reference into "[overlay@/home/me/.local/share/containers/storage+/run/user/1000/containers:overlay.mount_program=/usr/bin/fuse-overlayfs]@da86e6ba6ca197bf6bc5e9d900febd906b133eaa4750e6bed647b0fbe50ed43e"
DEBU[0000] exporting opaque data as blob "sha256:da86e6ba6ca197bf6bc5e9d900febd906b133eaa4750e6bed647b0fbe50ed43e"
DEBU[0000] created container "f1bc17dd6718b1edfd74abdb814b226d8908924c59fa09d2c8e9125695ec5b82"
DEBU[0000] container "f1bc17dd6718b1edfd74abdb814b226d8908924c59fa09d2c8e9125695ec5b82" has work directory "/home/me/.local/share/containers/storage/overlay-containers/f1bc17dd6718b1edfd74abdb814b226d8908924c59fa09d2c8e9125695ec5b82/userdata"
DEBU[0000] container "f1bc17dd6718b1edfd74abdb814b226d8908924c59fa09d2c8e9125695ec5b82" has run directory "/run/user/1000/containers/overlay-containers/f1bc17dd6718b1edfd74abdb814b226d8908924c59fa09d2c8e9125695ec5b82/userdata"
8f7f6727c09abbf684bb83b4dce64935ac71d6fcb8a53eb3dfce312099498121
STEP 1: FROM tryretool/backend:latest
STEP 2: CMD ./docker_scripts/start_api.sh
STEP 3: COMMIT retool:latest
panic: error opening "/home/me/.local/share/containers/storage/storage.lock": too many open files in system

goroutine 1 [running]:
panic(0x55d5c4872c60, 0xc000284be0)
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/panic.go:565 +0x2c9 fp=0xc0005b4740 sp=0xc0005b46b0 pc=0x55d5c34a3ec9 
github.com/containers/storage/pkg/lockfile.(*lockfile).lock(0xc000413590, 0x1)
        /builddir/build/BUILD/buildah-9513cb8c7bec0f7789c696aee4d252ebf85194cc/src/github.com/containers/storage/pkg/lockfile/lockfile_unix.go:107 +0x36d fp=0xc0005b47f0 sp=0xc0005b4740 pc=0x55d5c399ccad
github.com/containers/storage/pkg/lockfile.(*lockfile).Lock(0xc000413590)
        /builddir/build/BUILD/buildah-9513cb8c7bec0f7789c696aee4d252ebf85194cc/src/github.com/containers/storage/pkg/lockfile/lockfile_unix.go:130 +0x3f fp=0xc0005b4810 sp=0xc0005b47f0 pc=0x55d5c399cd8f
github.com/containers/storage.(*store).LayerStore(0xc0000a17a0, 0x0, 0x0, 0x0, 0x0)
        /builddir/build/BUILD/buildah-9513cb8c7bec0f7789c696aee4d252ebf85194cc/src/github.com/containers/storage/store.go:754 +0x61 fp=0xc0005b4940 sp=0xc0005b4810 pc=0x55d5c3a300a1
github.com/containers/storage.(*store).DeleteContainer(0xc0000a17a0, 0xc00013ae80, 0x40, 0x0, 0x0)
        /builddir/build/BUILD/buildah-9513cb8c7bec0f7789c696aee4d252ebf85194cc/src/github.com/containers/storage/store.go:2291 +0x4d fp=0xc0005b4a30 sp=0xc0005b4940 pc=0x55d5c3a3f88d
github.com/containers/buildah.(*Builder).Delete(0xc0002bf800, 0xc000450d80, 0xc0005b4c38)
        /builddir/build/BUILD/buildah-9513cb8c7bec0f7789c696aee4d252ebf85194cc/_build/src/github.com/containers/buildah/delete.go:10 +0x54 fp=0xc0005b4aa8 sp=0xc0005b4a30 pc=0x55d5c4060a44
github.com/containers/buildah/imagebuildah.(*StageExecutor).Delete(...)
        /builddir/build/BUILD/buildah-9513cb8c7bec0f7789c696aee4d252ebf85194cc/_build/src/github.com/containers/buildah/imagebuildah/stage_executor.go:689
github.com/containers/buildah/imagebuildah.(*Executor).Build.func1(0xc0005b4ce8, 0x10)
        /builddir/build/BUILD/buildah-9513cb8c7bec0f7789c696aee4d252ebf85194cc/_build/src/github.com/containers/buildah/imagebuildah/executor.go:353 +0x1d6 fp=0xc0005b4ca8 sp=0xc0005b4aa8 pc=0x55d5c40ecfa6
github.com/containers/buildah/imagebuildah.(*Executor).Build.func2(0xc000450db0, 0xc0005b50e8)
        /builddir/build/BUILD/buildah-9513cb8c7bec0f7789c696aee4d252ebf85194cc/_build/src/github.com/containers/buildah/imagebuildah/executor.go:395 +0x2d fp=0xc0005b4ce8 sp=0xc0005b4ca8 pc=0x55d5c40ed60d
github.com/containers/buildah/imagebuildah.(*Executor).Build(0xc0001be500, 0x55d5c4a81300, 0xc0000340e0, 0xc000450d50, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
        /builddir/build/BUILD/buildah-9513cb8c7bec0f7789c696aee4d252ebf85194cc/_build/src/github.com/containers/buildah/imagebuildah/executor.go:476 +0x18ef fp=0xc0005b5098 sp=0xc0005b4ce8 pc=0x55d5c40db83f
github.com/containers/buildah/imagebuildah.BuildDockerfiles(0x55d5c4a81300, 0xc0000340e0, 0x55d5c4aaa080, 0xc0000a17a0, 0xc00016ad20, 0xe, 0x2, 0x0, 0x0, 0x0, ...)
        /builddir/build/BUILD/buildah-9513cb8c7bec0f7789c696aee4d252ebf85194cc/_build/src/github.com/containers/buildah/imagebuildah/build.go:264 +0x5c9 fp=0xc0005b54b8 sp=0xc0005b5098 pc=0x55d5c40d4e49
main.budCmd(0xc0002acf00, 0xc0004134a0, 0x1, 0x5, 0xc00016a698, 0xc000318900, 0xc0004894a0, 0xc000478e00, 0xc000489500, 0x0, ...)
        /builddir/build/BUILD/buildah-9513cb8c7bec0f7789c696aee4d252ebf85194cc/_build/src/github.com/containers/buildah/cmd/buildah/bud.go:347 +0x139d fp=0xc0005b5cd0 sp=0xc0005b54b8 pc=0x55d5c410e1cd
main.init.1.func1(0xc0002acf00, 0xc0004134a0, 0x1, 0x5, 0x0, 0x0)
        /builddir/build/BUILD/buildah-9513cb8c7bec0f7789c696aee4d252ebf85194cc/_build/src/github.com/containers/buildah/cmd/buildah/bud.go:55 +0xd8 fp=0xc0005b5d60 sp=0xc0005b5cd0 pc=0x55d5c413cfb8
github.com/spf13/cobra.(*Command).execute(0xc0002acf00, 0xc000413450, 0x5, 0x5, 0xc0002acf00, 0xc000413450)
        /builddir/build/BUILD/buildah-9513cb8c7bec0f7789c696aee4d252ebf85194cc/src/github.com/spf13/cobra/command.go:826 +0x467 fp=0xc0005b5e48 sp=0xc0005b5d60 pc=0x55d5c40c88e7
github.com/spf13/cobra.(*Command).ExecuteC(0x55d5c540c700, 0x6, 0xc000034077, 0x8)
        /builddir/build/BUILD/buildah-9513cb8c7bec0f7789c696aee4d252ebf85194cc/src/github.com/spf13/cobra/command.go:914 +0x2fe fp=0xc0005b5f20 sp=0xc0005b5e48 pc=0x55d5c40c939e
github.com/spf13/cobra.(*Command).Execute(...)
        /builddir/build/BUILD/buildah-9513cb8c7bec0f7789c696aee4d252ebf85194cc/src/github.com/spf13/cobra/command.go:864
main.main()
        /builddir/build/BUILD/buildah-9513cb8c7bec0f7789c696aee4d252ebf85194cc/_build/src/github.com/containers/buildah/cmd/buildah/main.go:141 +0xb7 
fp=0xc0005b5f98 sp=0xc0005b5f20 pc=0x55d5c412a0c7
runtime.main()
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/proc.go:200 +0x214 fp=0xc0005b5fe0 sp=0xc0005b5f98 pc=0x55d5c34a5c24  
runtime.goexit()
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0005b5fe8 sp=0xc0005b5fe0 pc=0x55d5c34d1431

goroutine 2 [force gc (idle), 1 minutes]:
runtime.gopark(0x55d5c4a3e658, 0x55d5c545bba0, 0x1410, 0x1)
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/proc.go:301 +0xf5 fp=0xc000054fb0 sp=0xc000054f90 pc=0x55d5c34a6025   
runtime.goparkunlock(...)
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/proc.go:307
runtime.forcegchelper()
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/proc.go:250 +0xbb fp=0xc000054fe0 sp=0xc000054fb0 pc=0x55d5c34a5ebb   
runtime.goexit()
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000054fe8 sp=0xc000054fe0 pc=0x55d5c34d1431
created by runtime.init.6
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/proc.go:239 +0x37

goroutine 3 [GC sweep wait]:
runtime.gopark(0x55d5c4a3e658, 0x55d5c545df00, 0x140c, 0x1)
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/proc.go:301 +0xf5 fp=0xc0000557a8 sp=0xc000055788 pc=0x55d5c34a6025   
runtime.goparkunlock(...)
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/proc.go:307
runtime.bgsweep(0xc00003e070)
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/mgcsweep.go:89 +0x138 fp=0xc0000557d8 sp=0xc0000557a8 pc=0x55d5c3498cc8
runtime.goexit()
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0000557e0 sp=0xc0000557d8 pc=0x55d5c34d1431
created by runtime.gcenable
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/mgc.go:208 +0x5a

goroutine 4 [finalizer wait]:
runtime.gopark(0x55d5c4a3e658, 0x55d5c547dde8, 0xc0004e140f, 0x1)
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/proc.go:301 +0xf5 fp=0xc000055f58 sp=0xc000055f38 pc=0x55d5c34a6025
runtime.goparkunlock(...)
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/proc.go:307
runtime.runfinq()
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/mfinal.go:175 +0xaa fp=0xc000055fe0 sp=0xc000055f58 pc=0x55d5c348f82a 
runtime.goexit()
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000055fe8 sp=0xc000055fe0 pc=0x55d5c34d1431
created by runtime.createfing
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/mfinal.go:156 +0x63

goroutine 5 [syscall]:
runtime.notetsleepg(0x55d5c5464ce0, 0x129ff58bd, 0x0)
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/lock_futex.go:227 +0x38 fp=0xc000054760 sp=0xc000054730 pc=0x55d5c3481e48
runtime.timerproc(0x55d5c5464cc0)
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/time.go:311 +0x2ee fp=0xc0000547d8 sp=0xc000054760 pc=0x55d5c34c276e  
runtime.goexit()
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0000547e0 sp=0xc0000547d8 pc=0x55d5c34d1431
created by runtime.(*timersBucket).addtimerLocked
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/time.go:169 +0x110

goroutine 25 [chan receive]:
runtime.gopark(0x55d5c4a3e658, 0xc000076a18, 0x7f242b95170d, 0x3)
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/proc.go:301 +0xf5 fp=0xc000050ed0 sp=0xc000050eb0 pc=0x55d5c34a6025   
runtime.goparkunlock(...)
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/proc.go:307
runtime.chanrecv(0xc0000769c0, 0xc000050fb0, 0x55d5c545ef01, 0x55d5c545efb8)
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/chan.go:524 +0x2ee fp=0xc000050f60 sp=0xc000050ed0 pc=0x55d5c347d29e  
runtime.chanrecv2(0xc0000769c0, 0xc000050fb0, 0x55d5c3b4da01)
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/chan.go:411 +0x2b fp=0xc000050f90 sp=0xc000050f60 pc=0x55d5c347cf9b   
k8s.io/klog.(*loggingT).flushDaemon(0x55d5c545efa0)
        /builddir/build/BUILD/buildah-9513cb8c7bec0f7789c696aee4d252ebf85194cc/src/k8s.io/klog/klog.go:990 +0x8d fp=0xc000050fd8 sp=0xc000050f90 pc=0x55d5c3c3de1d
runtime.goexit()
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000050fe0 sp=0xc000050fd8 pc=0x55d5c34d1431
created by k8s.io/klog.init.0
        /builddir/build/BUILD/buildah-9513cb8c7bec0f7789c696aee4d252ebf85194cc/src/k8s.io/klog/klog.go:404 +0x6e

goroutine 23 [GC worker (idle)]:
runtime.gopark(0x55d5c4a3e4f0, 0xc000470cc0, 0x1417, 0x0)
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/proc.go:301 +0xf5 fp=0xc000051760 sp=0xc000051740 pc=0x55d5c34a6025   
runtime.gcBgMarkWorker(0xc000042000)
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/mgc.go:1836 +0x105 fp=0xc0000517d8 sp=0xc000051760 pc=0x55d5c3493345  
runtime.goexit()
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0000517e0 sp=0xc0000517d8 pc=0x55d5c34d1431
created by runtime.gcBgMarkStartWorkers
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/mgc.go:1784 +0x79

goroutine 21 [syscall, 1 minutes]:
runtime.notetsleepg(0x55d5c547e520, 0xffffffffffffffff, 0x0)
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/lock_futex.go:227 +0x38 fp=0xc000051f98 sp=0xc000051f68 pc=0x55d5c3481e48
os/signal.signal_recv(0x0)
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/sigqueue.go:139 +0x9e fp=0xc000051fc0 sp=0xc000051f98 pc=0x55d5c34b9ebe
os/signal.loop()
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/os/signal/signal_unix.go:23 +0x24 fp=0xc000051fe0 sp=0xc000051fc0 pc=0x55d5c3a918a4
runtime.goexit()
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000051fe8 sp=0xc000051fe0 pc=0x55d5c34d1431
created by os/signal.init.0
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/os/signal/signal_unix.go:29 +0x43
ERRO signal: aborted (core dumped)
ERRO (unable to determine exit status)
Failed to read /etc/containers/storage.conf open /etc/containers/storage.conf: too many open files in system
WARN[0000] Failed to parse cgroup information: failed to parse cgroup information: open /proc/self/mountinfo: too many open files in system 
WARN[0000] Failed to parse cgroup information: failed to parse cgroup information: open /proc/self/mountinfo: too many open files in system
Failed to read /home/me/.config/containers/storage.conf open /home/me/.config/containers/storage.conf: too many open files in system      
WARN[0000] The cgroups manager is set to systemd but there is no systemd user session available
WARN[0000] For using systemd, you may need to login using an user session
WARN[0000] Alternatively, you can enable lingering with: `loginctl enable-linger 1000` (possibly as root)
WARN[0000] Falling back to --cgroup-manager=cgroupfs and --events-backend=file
WARN[0000] Conmon at /usr/bin/conmon invalid: open /dev/null: too many open files in system
WARN[0000] Conmon at /usr/bin/conmon is invalid: open /dev/null: too many open files in system
ERRO[0000] could not get runtime: please update to v2.0.1 or later: outdated conmon version
/opt/retool/podman_launcher.sh: line 11: /usr/bin/podman: Too many open files in system
/opt/retool/podman_launcher.sh: line 12: /usr/bin/podman: Too many open files in system
/opt/retool/podman_launcher.sh: line 13: /usr/bin/podman: Too many open files in system
/opt/retool/podman_launcher.sh: line 14: /usr/bin/podman: Too many open files in system
/opt/retool/podman_launcher.sh: line 15: /usr/bin/podman: Too many open files in system
/opt/retool/podman_launcher.sh: line 16: /usr/bin/podman: Too many open files in system
```

**Describe the results you expected:**

To get to the next step so that I can troubleshoot the other issue(s). 😄 

**Output of `podman version`:**

```
Version:            1.6.4
RemoteAPI Version:  1
Go Version:         go1.12.12
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.12
  podman version: 1.6.4
host:
  BuildahVersion: 1.12.0-dev
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.15-1.el7_8.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.15, commit: 372b4a12f1c2df4f70c280d41173b60acd3f1260'
  Distribution:
    distribution: '"rhel"'
    version: "7.9"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 10000
      size: 65535
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 10000
      size: 65535
  MemFree: 835645440
  MemTotal: 2078490624
  OCIRuntime:
    name: runc
    package: runc-1.0.0-67.rc10.el7_8.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 1073737728
  SwapTotal: 1073737728
  arch: amd64
  cpus: 1
  eventlogger: file
  hostname: localhost.localdomain
  kernel: 3.10.0-1136.el7.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.3-4.el7_8.x86_64
    Version: |-
      slirp4netns version 0.4.3
      commit: 2244b9b6461afeccad1678fac3d6e478c28b4ad6
  uptime: 19m 2.46s
registries:
  blocked: null
  insecure: null
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  ConfigFile: /home/me/.config/containers/storage.conf
  ContainerStore:
    number: 3
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.2-6.el7_8.x86_64
      Version: |-
        fuse-overlayfs: version 0.7.2
        FUSE library version 3.6.1
        using FUSE kernel interface version 7.29
  GraphRoot: /home/me/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 2
  RunRoot: /run/user/1000/containers
  VolumePath: /home/me/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.6.4-18.el7_8.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

* vmware virtual host

**Comment by mheon** [comment]
Podman v1.6.4 is getting very long in the tooth - can you try with a more recent version and see if things are working there? We've done quite a bit with limits in the v2.0 releases.

**Comment by burhan** [comment]
How do I upgrade? I don't see anything when I check for upgrades on RHEL 7.9 (unfortunately can't upgrade to RHEL 8).

```
sudo yum upgrade -y
Loaded plugins: langpacks, product-id, search-disabled-repos, subscription-manager
No packages marked for update
```

**Comment by mheon** [comment]
You can install the latest versions for RHEL/Cent 7 from OBS here: https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/podman

Note that these are not officially supported on the RHEL side. Cent/RHEL 7 official packages are not receiving further rebases of Podman and will only get security-related fixes.

**Comment by rhatdan** [comment]
Translation, time to upgrade to RHEL8/Centos 8 if you want to use newer stuff.

**Comment by burhan** [comment]
So I upgraded to RHEL 8, and the new AppStream version of container tools. I ran into another set of issues there, but I'll close this an investigate further.
