### ISSUE TITLE
Pulling image with digest sha via podman API doesn't work

### ISSUE THREAD

**Issue by rcerven** [containers/podman#7925]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

pulling image with digest sha via podman API doesn't work

**Steps to reproduce the issue:**

using python-docker via podman API

```
>>> import docker
>>> client = docker.APIClient(base_url='unix:///run/podman/podman.sock')
>>> client.pull('quay.io/containers/podman', tag='latest')
'{"status":"pulling image () from quay.io/containers/podman:latest","error":"","progress":"","progressDetail":{},"id":"730feef61d4d927260b0dc54986c14513c5f2ea1f26e1e2fae341086c8801698"}\n'

>>> client.pull('quay.io/containers/podman', tag='sha256:c6b14f4fcd9694459770fb05de0309338b40f4788bf05e132bdce8d3e90793c3')
Traceback (most recent call last):
  File "/home/rcerven/build_env/virtenvs/py38env/lib/python3.8/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/home/rcerven/build_env/virtenvs/py38env/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.35/images/create?tag=sha256%3Ac6b14f4fcd9694459770fb05de0309338b40f4788bf05e132bdce8d3e90793c3&fromImage=quay.io%2Fcontainers%2Fpodman

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rcerven/build_env/virtenvs/py38env/lib/python3.8/site-packages/docker/api/image.py", line 415, in pull
    self._raise_for_status(response)
  File "/home/rcerven/build_env/virtenvs/py38env/lib/python3.8/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/rcerven/build_env/virtenvs/py38env/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("unable to pull quay.io/containers/podman:sha256:c6b14f4fcd9694459770fb05de0309338b40f4788bf05e132bdce8d3e90793c3: error getting default registries to try: invalid reference format"
```

using python-docker via docker API works

```
>>> import docker
>>> client = docker.APIClient()
>>> client.pull('quay.io/containers/podman', tag='latest')
'{"status":"Pulling from containers/podman","id":"latest"}\r\n{"status":"Pull complete","progressDetail":{},"id":"2e10564e2007"}\r\n{"status":"Digest: sha256:c6b14f4fcd9694459770fb05de0309338b40f4788bf05e132bdce8d3e90793c3"}\r\n{"status":"Status: Downloaded newer image for quay.io/containers/podman:latest"}\r\n'

>>> client.pull('quay.io/containers/podman', tag='sha256:c6b14f4fcd9694459770fb05de0309338b40f4788bf05e132bdce8d3e90793c3')
'{"status":"Pulling from containers/podman","id":"sha256:c6b14f4fcd9694459770fb05de0309338b40f4788bf05e132bdce8d3e90793c3"}\r\n{"status":"Digest: sha256:c6b14f4fcd9694459770fb05de0309338b40f4788bf05e132bdce8d3e90793c3"}\r\n{"status":"Status: Image is up to date for quay.io/containers/podman@sha256:c6b14f4fcd9694459770fb05de0309338b40f4788bf05e132bdce8d3e90793c3"}\r\n'
```

curl podman API

```
$ curl -XPOST --unix-socket /run/podman/podman.sock -v 'http://localhost/images/create?fromImage=quay.io%2Fcontainers%2Fpodman&tag=latest'                                                                                                                
*   Trying /run/podman/podman.sock:0...
* Connected to localhost (/run/podman/podman.sock) port 80 (#0)
> POST /images/create?fromImage=quay.io%2Fcontainers%2Fpodman&tag=latest HTTP/1.1
> Host: localhost
> User-Agent: curl/7.69.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Mon, 05 Oct 2020 15:52:01 GMT
< Content-Length: 185
< 
{"status":"pulling image () from quay.io/containers/podman:latest","error":"","progress":"","progressDetail":{},"id":"730feef61d4d927260b0dc54986c14513c5f2ea1f26e1e2fae341086c8801698"}
* Connection #0 to host localhost left intact


$ curl -XPOST --unix-socket /run/podman/podman.sock -v 'http://localhost/images/create?fromImage=quay.io%2Fcontainers%2Fpodman&tag=sha256%3A730feef61d4d927260b0dc54986c14513c5f2ea1f26e1e2fae341086c8801698'
*   Trying /run/podman/podman.sock:0...
* Connected to localhost (/run/podman/podman.sock) port 80 (#0)
> POST /images/create?fromImage=quay.io%2Fcontainers%2Fpodman&tag=sha256%3A730feef61d4d927260b0dc54986c14513c5f2ea1f26e1e2fae341086c8801698 HTTP/1.1
> Host: localhost
> User-Agent: curl/7.69.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Content-Type: application/json
< Date: Mon, 05 Oct 2020 15:53:54 GMT
< Content-Length: 244
<
{"cause":"invalid reference format","message":"unable to pull quay.io/containers/podman:sha256:730feef61d4d927260b0dc54986c14513c5f2ea1f26e1e2fae341086c8801698: error getting default registries to try: invalid reference format","response":500}
* Connection #0 to host localhost left intact
```

**Describe the results you received:**

API is appending sha as tag, and fails to pull image when image is specified with digest

**Describe the results you expected:**

image will be pulled with pullspec with sha

**Output of `podman version`:**

```
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.14.9
Built:        Wed Sep 30 21:31:11 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.16.1
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.19-1.fc32.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.19, commit: 5dce9767526ed27f177a8fa3f281889ad509fea7'
  cpus: 8
  distribution:
    distribution: fedora
    version: "32"
  eventLogger: journald
  hostname: dhcp-0-143.brq.redhat.com
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.8.9-200.fc32.x86_64
  linkmode: dynamic
  memFree: 417521664
  memTotal: 16178266112
  ociRuntime:
    name: crun
    package: crun-0.15-5.fc32.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.15
      commit: 56ca95e61639510c7dbd39ff512f80f626404969
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 8085303296
  swapTotal: 8120168448
  uptime: 4h 37m 45.58s (Approximately 0.17 days)
registries:
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    .mountopt: nodev
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 1
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 1601494271
  BuiltTime: Wed Sep 30 21:31:11 2020
  GitCommit: ""
  GoVersion: go1.14.9
  OsArch: linux/amd64
  Version: 2.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.1.1-7.fc32.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical with virtenv

**Comment by rhatdan** [comment]
@mtrmac PTAL

**Comment by zhangguanzhang** [comment]
I think this has been fix by https://github.com/containers/podman/pull/7901/files, may be need a new release
