### ISSUE TITLE
panic when removing remote network 

### ISSUE THREAD

**Issue by trusch** [containers/podman#8014]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I'm able to create a client side panic when I try to remove a network using `--remote` when accessing a rootless podman server.

**Steps to reproduce the issue:**

1. Enable rootless podman socket on the server
2. Create network `foo` on the server
3. Connect from client to server (add connection)
3. Try to delete the network `podman --remote network rm foo`

**Describe the results you received:**
```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/containers/podman/v2/pkg/domain/infra/tunnel.(*ContainerEngine).NetworkRm(0xc00012e690, 0x557dd47a1800, 0xc0005e5800, 0xc0002ffe40, 0x1, 0x2, 0xc000322b01, 0xc0005f7c80, 0x557dd3637619, 0xc00052d400, ...)
	pkg/domain/infra/tunnel/network.go:31 +0x28c
github.com/containers/podman/v2/cmd/podman/networks.networkRm(0x557dd5130d00, 0xc0002ffe40, 0x1, 0x2, 0x0, 0x0)
	cmd/podman/networks/rm.go:48 +0xb0
github.com/spf13/cobra.(*Command).execute(0x557dd5130d00, 0xc00003c1c0, 0x2, 0x2, 0x557dd5130d00, 0xc00003c1c0)
	vendor/github.com/spf13/cobra/command.go:838 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0x557dd5138b00, 0xc0000460f0, 0x557dd4521a60, 0x557dd51e7510)
	vendor/github.com/spf13/cobra/command.go:943 +0x336
github.com/spf13/cobra.(*Command).Execute(...)
	vendor/github.com/spf13/cobra/command.go:883
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	vendor/github.com/spf13/cobra/command.go:876
main.Execute()
	cmd/podman/root.go:86 +0xee
main.main()
	cmd/podman/main.go:77 +0x195
```

**Describe the results you expected:**
The network should be deleted.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(client) ➜ ~ podman --version
podman version 2.1.1
(client) ➜ ~ ssh server podman --version
podman version 2.1.1
```

**Output of `podman info --debug`:**
Server:
```
(server) ➜ ~ podman info --debug
host:
  arch: amd64
  buildahVersion: 1.16.1
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: Unknown
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: 35a2fa83022e56e18af7e6a865ba5d7165fa2a4a'
  cpus: 8
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  hostname: beast
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.8.14-arch1-1
  linkmode: dynamic
  memFree: 22635057152
  memTotal: 33390354432
  ociRuntime:
    name: runc
    package: Unknown
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc92
      commit: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
      spec: 1.0.2-dev
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: Unknown
    version: |-
      slirp4netns version 1.1.4
      commit: b66ffa8e262507e37fca689822d23430f3357fe8
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
  swapFree: 0
  swapTotal: 0
  uptime: 21h 0m 40.81s (Approximately 0.88 days)
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  configFile: /home/tino/.config/containers/storage.conf
  containerStore:
    number: 27
    paused: 0
    running: 17
    stopped: 10
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: Unknown
      Version: |-
        fusermount3 version: 3.10.0
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.10.0
        using FUSE kernel interface version 7.31
  graphRoot: /home/tino/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 164
  runRoot: /run/user/1000/containers
  volumePath: /home/tino/.local/share/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 1601135437
  BuiltTime: Sat Sep 26 17:50:37 2020
  GitCommit: 9f6d6ba0b314d86521b66183c9ce48eaa2da1de2
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 2.1.1
```

Client:
```
(client) ➜ ~ podman info --debug
host:
  arch: amd64
  buildahVersion: 1.16.1
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: Unknown
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: 35a2fa83022e56e18af7e6a865ba5d7165fa2a4a'
  cpus: 4
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  hostname: carbon
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65535
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65535
  kernel: 5.8.14-arch1-1
  linkmode: dynamic
  memFree: 2492698624
  memTotal: 8216784896
  ociRuntime:
    name: crun
    package: Unknown
    path: /usr/bin/crun
    version: |-
      crun version 0.15
      commit: 56ca95e61639510c7dbd39ff512f80f626404969
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: Unknown
    version: |-
      slirp4netns version 1.1.4
      commit: b66ffa8e262507e37fca689822d23430f3357fe8
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
  swapFree: 0
  swapTotal: 0
  uptime: 21h 0m 38.79s (Approximately 0.88 days)
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  configFile: /home/tino/.config/containers/storage.conf
  containerStore:
    number: 33
    paused: 0
    running: 0
    stopped: 33
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: Unknown
      Version: |-
        fusermount3 version: 3.10.0
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.10.0
        using FUSE kernel interface version 7.31
  graphRoot: /home/tino/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 91
  runRoot: /run/user/1000/containers
  volumePath: /home/tino/.local/share/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 1601135437
  BuiltTime: Sat Sep 26 17:50:37 2020
  GitCommit: 9f6d6ba0b314d86521b66183c9ce48eaa2da1de2
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 2.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(client) ➜ ~ pacman -Q podman
podman 2.1.1-1
(server) ➜ ~ pacman -Q podman
podman 2.1.1-1
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Server and client are two local laptops.

**Comment by zhangguanzhang** [comment]
@mheon 
need merge this
https://github.com/containers/podman/commit/343a10e25fb12685f18ed3600c567397c01a7cc8#diff-825f21ad71e23c991f90a0d19d60799b95ca802c280ce3fdb8c9d794f4f89b6e

**Comment by rhatdan** [comment]
@zhangguanzhang Is that already merged into the main branch?

**Comment by Luap99** [comment]
@rhatdan Yes

**Comment by rhatdan** [comment]
Fixed in Main.  Might be backported to podman 2.1.2
