### ISSUE TITLE
Debug hanging server in container

### ISSUE THREAD

**Issue by abitrolly** [containers/podman#8257]
/kind bug

**Description**

Running a server with auto-reload hangs in container. I use podman to run Flask with all dependencies in debug mode. This mode shows errors and provides auto-reload. And it hangs on start.

**Steps to reproduce the issue:**

```
git clone https://github.com/chubin/cheat.sh.git
cd cheat.sh
git checkout -b hanging 0df9db4

strace podman-compose -f docker-compose.yml -f docker-compose.debug.yml up
```
Try to open http://127.0.0.1:8002/

**Describe the results you received:**

That's `strace` output, and that FUTEX messages at the end are repeating.
```
mmap(NULL, 8392704, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7f2d1b7ff000
mprotect(0x7f2d1b800000, 8388608, PROT_READ|PROT_WRITE) = 0
rt_sigprocmask(SIG_BLOCK, ~[], [], 8)   = 0
clone(child_stack=0x7f2d1bffeef0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tid=[36043], tls=0x7f2d1bfff640, child_tidptr=0x7f2d1bfff910) = 36043
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
futex(0x7f2d2f118f6c, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7f2d2f118f70, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x55bc501d95e0, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, FUTEX_BITSET_MATCH_ANY) = 0
futex(0x7f2d2f118f68, FUTEX_WAIT_BITSET_PRIVATE, 0, {tv_sec=41885, tv_nsec=920461432}, FUTEX_BITSET_MATCH_ANYpodman start -a chtsh
) = 0
futex(0x7f2d2f118f70, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7f2d2f118f6c, FUTEX_WAIT_BITSET_PRIVATE, 0, {tv_sec=41885, tv_nsec=920519224}, FUTEX_BITSET_MATCH_ANY) = 0
futex(0x7f2d2f118f70, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7f2d2f118f68, FUTEX_WAIT_BITSET_PRIVATE, 0, {tv_sec=41885, tv_nsec=920676669}, FUTEX_BITSET_MATCH_ANY) = 0
futex(0x7f2d2f118f70, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7f2d2f118f6c, FUTEX_WAIT_BITSET_PRIVATE, 0, {tv_sec=41885, tv_nsec=921257149}, FUTEX_BITSET_MATCH_ANY) = 0
futex(0x7f2d2f118f70, FUTEX_WAKE_PRIVATE, 1) = 0
select(0, NULL, NULL, NULL, {tv_sec=1, tv_usec=0} * Serving Flask app "bin/srv.py" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://0.0.0.0:8002/ (Press CTRL+C to quit)
 * Restarting with stat
) = 0 (Timeout)
futex(0x7f2d1c000b60, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {tv_sec=1604639129, tv_nsec=874338000}, FUTEX_BITSET_MATCH_ANY * Debugger is active!
 * Debugger PIN: 279-004-436
) = -1 ETIMEDOUT (Connection timed out)
futex(0x7f2d14000b60, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {tv_sec=1604639130, tv_nsec=874587000}, FUTEX_BITSET_MATCH_ANY) = -1 ETIMEDOUT (Connection timed out)
futex(0x7f2d1c000b60, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {tv_sec=1604639131, tv_nsec=874747000}, FUTEX_BITSET_MATCH_ANY) = -1 ETIMEDOUT (Connection timed out)
futex(0x7f2d14000b60, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {tv_sec=1604639132, tv_nsec=874906000}, FUTEX_BITSET_MATCH_ANY) = -1 ETIMEDOUT (Connection timed out)
futex(0x7f2d1c000b60, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {tv_sec=1604639133, tv_nsec=875073000}, FUTEX_BITSET_MATCH_ANY) = -1 ETIMEDOUT (Connection timed out)
futex(0x7f2d14000b60, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {tv_sec=1604639134, tv_nsec=875224000}, FUTEX_BITSET_MATCH_ANY) = -1 ETIMEDOUT (Connection timed out)
futex(0x7f2d1c000b60, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {tv_sec=1604639135, tv_nsec=875366000}, FUTEX_BITSET_MATCH_ANY) = -1 ETIMEDOUT (Connection timed out)
```

**Describe the results you expected:**

Serving a request with GET status 200.

**Output of `podman version`:**

```
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.15.2
Built:        Wed Oct  7 19:21:20 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.16.1
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.21-3.fc33.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: 0f53fb68333bdead5fe4dc5175703e22cf9882ab'
  cpus: 4
  distribution:
    distribution: fedora
    version: "33"
  eventLogger: journald
  hostname: blackred
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.8.17-300.fc33.x86_64
  linkmode: dynamic
  memFree: 781443072
  memTotal: 8031588352
  ociRuntime:
    name: crun
    package: crun-0.15-5.fc33.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.15
      commit: 56ca95e61639510c7dbd39ff512f80f626404969
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.4-4.dev.giteecccdb.fc33.x86_64
    version: |-
      slirp4netns version 1.1.4+dev
      commit: eecccdb96f587b11d7764556ffacfeaffe4b6e11
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 8136916992
  swapTotal: 8196714496
  uptime: 16h 26m 39.85s (Approximately 0.67 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/anatoli/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.2.0-1.fc33.x86_64
      Version: |-
        fusermount3 version: 3.9.3
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.9.3
        using FUSE kernel interface version 7.31
  graphRoot: /home/anatoli/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 11
  runRoot: /run/user/1000
  volumePath: /home/anatoli/.local/share/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 1602087680
  BuiltTime: Wed Oct  7 19:21:20 2020
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 2.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.1.1-12.fc33.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Fedora 33.

**Comment by rhatdan** [comment]
Can you get a simpler repeater that does not use podman-compose?

**Comment by abitrolly** [comment]
@rhatdan 

1. `podman run -p 8002 yakshaveinc/linux:podman-8257` 
2, try to open http://127.0.0.1:8002/

**Comment by rhatdan** [comment]
This is what I see in the container.
```
 * Serving Flask app "bin/srv.py" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://0.0.0.0:8002/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 475-112-999
```

**Comment by rhatdan** [comment]
I would figure your application is having an issue running within the container.  Have you tried this with a rootfull container?

**Comment by abitrolly** [comment]
@rhatdan do you mean `sudo podman run ...`? That hangs too.

The application contains a reloader. If I turn off reloader, it starts to work.
```
$ podman run -p 8002 -e FLASK_RUN_RELOAD=False yakshaveinc/linux:podman-8257
 * Serving Flask app "bin/srv.py"
 * Environment: development
 * Debug mode: on
^CKeyboardInterrupt
2020-11-13T00:23:47Z
```

**Comment by rhatdan** [comment]
Does it work if you run it --privileged?

**Comment by abitrolly** [comment]
This hangs too.
```
$ podman run --privileged -p 8002 yakshaveinc/linux:podman-8257
```

**Comment by rhatdan** [comment]
Then the issue is your process is having a hard time running inside of a container.

If the process inside of the container does not work in --privilege mode, then you can figure it is having a problem with container namespaces.  You can start disabling some of these also.

podman run --net=host --ipc=host --upc=host --pid=host ...

These will cause your container process to not use some of the namespaces.

Have you tried running your container as root also?

**Comment by abitrolly** [comment]
@rhatdan using `sudo` + `--privileged` works..
```
sudo podman run --privileged -p 8002 -it yakshaveinc/linux:podman-8257
```
These didn't work.
```
podman run  -p 8002 -it yakshaveinc/linux:podman-8257
sudo podman run  -p 8002 -it yakshaveinc/linux:podman-8257
podman run --privileged -p 8002 -it yakshaveinc/linux:podman-8257
```

> podman run --net=host --ipc=host --upc=host --pid=host ...
```
Error: unknown flag: --upc
➜  ~ podman run --help | grep -i Names
      --cgroupns string                          cgroup namespace to use
      --gidmap strings                           GID map to use for the user namespace
      --ipc string                               IPC namespace to use
      --pid string                               PID namespace to use
      --subgidname string                        Name of range listed in /etc/subgid for use in user namespace
      --subuidname string                        Name of range listed in /etc/subuid for use in user namespace
      --uidmap strings                           UID map to use for the user namespace
      --userns string                            User namespace to use
      --uts string                               UTS namespace to use
```

Setting `--uts host` helped. Although I have no idea why.
```
➜  ~ podman run --uts=host -p 8009:8002 -it yakshaveinc/linux:podman-8257
 * Serving Flask app "bin/srv.py" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://0.0.0.0:8002/ (Press CTRL+C to quit)
 * Restarting with stat
/app/bin/srv.py:27: MonkeyPatchWarning: Monkey-patching outside the main native thread. Some APIs will not be available. Expect a KeyError to be printed at shutdown.
  patch_all()
/app/bin/srv.py:27: MonkeyPatchWarning: Monkey-patching not on the main thread; threading.main_thread().join() will hang from a greenlet
  patch_all()
 * Debugger is active!
 * Debugger PIN: 128-090-104
/app/bin/srv.py:27: MonkeyPatchWarning: Monkey-patching outside the main native thread. Some APIs will not be available. Expect a KeyError to be printed at shutdown.
  patch_all()
/app/bin/srv.py:27: MonkeyPatchWarning: Monkey-patching not on the main thread; threading.main_thread().join() will hang from a greenlet
  patch_all()
127.0.0.1 - - [17/Nov/2020 02:34:05] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    
  File "<frozen importlib._bootstrap>", line 152, in __exit__
    
  File "<frozen importlib._bootstrap>", line 107, in release
    
RuntimeError: cannot release un-acquired lock
127.0.0.1 - - [17/Nov/2020 02:34:05] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [17/Nov/2020 02:34:05] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [17/Nov/2020 02:34:05] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
...
```

**Comment by abitrolly** [comment]
On the second try it didn't.
```
➜  ~ podman run --uts=host -p 8020:8002 -it yakshaveinc/linux:podman-8257
 * Serving Flask app "bin/srv.py" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://0.0.0.0:8002/ (Press CTRL+C to quit)
 * Restarting with stat
/app/bin/srv.py:27: MonkeyPatchWarning: Monkey-patching outside the main native thread. Some APIs will not be available. Expect a KeyError to be printed at shutdown.
  patch_all()
/app/bin/srv.py:27: MonkeyPatchWarning: Monkey-patching not on the main thread; threading.main_thread().join() will hang from a greenlet
  patch_all()
 * Debugger is active!
 * Debugger PIN: 412-679-934
/app/bin/srv.py:27: MonkeyPatchWarning: Monkey-patching outside the main native thread. Some APIs will not be available. Expect a KeyError to be printed at shutdown.
  patch_all()
/app/bin/srv.py:27: MonkeyPatchWarning: Monkey-patching not on the main thread; threading.main_thread().join() will hang from a greenlet
  patch_all()
```

**Comment by abitrolly** [comment]
There are a plenty of bugs. Firefox hangs more often that `curl`. Maybe because FF sends keep-alive by default. I don't know.
```
    
  File "src/gevent/libev/corecext.pyx", line 1209, in gevent.libev.corecext.child.__cinit__
    
TypeError: child watchers are only available on the default loop
```

**Comment by abitrolly** [comment]
This might be a Firefox issue.. Another "interesting" log excerpt.
```
...
init__
    
TypeError: child watchers are only available on the default loop
10.88.0.1 - - [17/Nov/2020 03:16:58] code 400, message Bad request version ('í¬ñ\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À')
10.88.0.1 - - [17/Nov/2020 03:16:58] "üVÅ¯
                                          KÈ#Å|Ö>�@Õ¿I'ÁÔjÕ6Nq6²Æày¹M½~R¼§Ý|" HTTPStatus.BAD_REQUEST -
10.88.0.1 - - [17/Nov/2020 03:16:58] code 400, message Bad request version ('\x81\x17eZ¥\x7f¡1µ\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À')
10.88.0.1 - - [17/Nov/2020 03:16:58] "üý¯¯ýkç].Wßßñ�ùaNõKÚ"
' eZ¥¡1µ"À+À/Ì©Ì¨À,À0À" HTTPStatus.BAD_REQUEST -            Wµ²=Í_Ê]DRShÅóJÛº
10.88.0.1 - - [17/Nov/2020 03:16:58] "GET / HTTP/1.1" 500 -
10.88.0.1 - - [17/Nov/2020 03:16:58] "GET / HTTP/1.1" 500 -
```

**Comment by rhatdan** [comment]
Ok I will blame this on firefox. closing.

**Comment by abitrolly** [comment]
Firefox and `curl` are treated differently in app. The cause is most likely some deadlock happening between watcher event loop and `gevent` patches event loop. I thought that maybe `podman` employs some best practices in debugging those issues, like `strace` flags etc.

As a workaround I switched Flask app to use `flask run` server with reload watcher instead of `gevent`.
