### ISSUE TITLE
After fresh `podman info` some 'podman' process left hung in pause()

### ISSUE THREAD

**Issue by fillest** [containers/podman#8273]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. freshly install podman

2. `podman info`

3. `ps -aux | grep [p]odman`

**Describe the results you received:**

'podman' process exists

**Describe the results you expected:**

No podman processes left

**Additional information you deem important (e.g. issue happens only occasionally):**

```
$ strace -p  11462
	strace: Process 11462 attached
	pause(
```
```
$ sudo gdb -batch -ex "thread apply all backtrace" -p 11462
	[Thread debugging using libthread_db enabled]
	Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
	0x00007fe91c492eb1 in __libc_pause () at ../sysdeps/unix/sysv/linux/pause.c:30
	30	../sysdeps/unix/sysv/linux/pause.c: No such file or directory.

	Thread 1 (Thread 0x7fe91c8b6740 (LWP 11462)):
	#0  0x00007fe91c492eb1 in __libc_pause () at ../sysdeps/unix/sysv/linux/pause.c:30
	#1  0x0000000000408cd5 in ?? ()
	#2  0x00000000004093fc in ?? ()
	#3  0x000000000170ef7d in __libc_csu_init ()
	#4  0x00007fe91b812b28 in __libc_start_main (main=0x474a20 <main>, argc=1, argv=0x7ffdef2f9348, init=0x170ef30 <__libc_csu_init>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffdef2f9338) at ../csu/libc-start.c:266
	#5  0x00000000004094da in _start ()
```

Somehow it prevents an ssh session to close after I exited it.
```
$ loginctl session-status 18
         Service: sshd; type tty; class user
           State: closing
            Unit: session-18.scope
                  └─11462 podman
```

Didn't try to reproduce.

**Output of `podman version`:**

```
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.15.2
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.16.1
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.20, commit: '
  cpus: 16
  distribution:
    distribution: ubuntu
    version: "18.04"
  eventLogger: journald
  hostname: foo
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  kernel: 4.15.0-1011-aws
  linkmode: dynamic
  memFree: 29803122688
  memTotal: 32655642624
  ociRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 2h 41m 6.35s (Approximately 0.08 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/qwe/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/qwe/.local/share/containers/storage
  graphStatus: {}
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers
  volumePath: /home/qwe/.local/share/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 2.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unknown,now 2.1.1~2 amd64 [installed]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS

**Comment by mheon** [comment]
I presume you're running rootless? If so, is expected that Podman leaves a
pause process behind to hold open the rootless user namespace. The process
can be safely killed if all containers are stopped and nothing is using
Podman (we can't do this automatically because of potential race conditions
if another Podman is starting at the same time).

**Comment by fillest** [comment]
Oh, I see.
