### ISSUE TITLE
Podman doesn't play well with terminal sizing

### ISSUE THREAD

**Issue by millerthegorilla** [containers/podman#9201]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)*
/kind bug

**Description**

**Steps to reproduce the issue:**

1. enter a container

2. run the django dev server and/or shell.  After four or five minutes or an unknown and possibly random amount of commands, the command line # disappears, and then using the command line history becomes difficult with at best a garbled prompt, which I can clear temporarily by using clear.   Usually I reset the issue by exiting and re-entering the container. 

3.  ---

**Describe the results you received:**
garbled or disappeared text on command prompt

**Describe the results you expected:**
normal terminal usage

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.15.5
Built:        Tue Dec  8 14:37:50 2020
OS/Arch:      linux/amd64

```

**Output of `podman info --debug`:**

```
podman info --debug
host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.21-3.fc33.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: 0f53fb68333bdead5fe4dc5175703e22cf9882ab'
  cpus: 2
  distribution:
    distribution: fedora
    version: "33"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  kernel: 5.10.11-200.fc33.x86_64
  linkmode: dynamic
  memFree: 3975086080
  memTotal: 8215330816
  ociRuntime:
    name: crun
    package: crun-0.17-1.fc33.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1001/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-1.fc33.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 4107268096
  swapTotal: 4107268096
  uptime: 1h 35m 52.52s (Approximately 0.04 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /var/home/dev/.config/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 3
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.4.0-1.fc33.x86_64
      Version: |-
        fusermount3 version: 3.9.3
        fuse-overlayfs: version 1.4
        FUSE library version 3.9.3
        using FUSE kernel interface version 7.31
  graphRoot: /var/home/dev/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 29
  runRoot: /run/user/1001/containers
  volumePath: /var/home/dev/.local/share/containers/storage/volumes
version:
  APIVersion: 2.1.0
  Built: 1607438270
  BuiltTime: Tue Dec  8 14:37:50 2020
  GitCommit: ""
  GoVersion: go1.15.5
  OsArch: linux/amd64
  Version: 2.2.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.2.1-1.fc33.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Not sure.  Silverblue's unwriteable directory structure makes it difficult to test different versions, I think, and I have read the issue tracker FAQs and it is not listed there.  It would be helpful if you could place the url of the 'Podman Troubleshooting Guide' in this template.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
my ostree is standard with the exception of terminology, firewall-config, and google-chrome, but it was happening on Workstation before I reinstalled.

**Comment by vrothberg** [comment]
Thanks for reaching out, @millerthegorilla!

Can you elaborate on the "terminal sizing"? Is the Django terminal resized before the symptoms occur?

**Comment by millerthegorilla** [comment]
No, the terminal is sized as normal, in the case of gnome terminal (I haven't used terminology for a while).
I don't resize it, the issue just happens normally.

**Comment by millerthegorilla** [comment]
When using bpython as a shell for django, inside the container, I get the following error, which I think might be related:
```
 File "/usr/local/lib/python3.9/site-packages/bpython/curtsiesfrontend/replpainter.py", line 33, in display_linize
    display_lines = list(msg.width_aware_splitlines(columns))
  File "/usr/local/lib/python3.9/site-packages/curtsies/formatstring.py", line 654, in width_aware_splitlines
    raise ValueError("Column width %s is too narrow." % columns)
ValueError: Column width 0 is too narrow.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/django_forum/django_forum/./manage.py", line 22, in <module>
    main()
  File "/opt/django_forum/django_forum/./manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/shell.py", line 100, in handle
    return getattr(self, shell)(options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/shell.py", line 40, in bpython
    bpython.embed()
  File "/usr/local/lib/python3.9/site-packages/bpython/__init__.py", line 42, in embed
    return main(args, locals_, banner)
  File "/usr/local/lib/python3.9/site-packages/bpython/curtsies.py", line 221, in main
    exit_value = repl.mainloop(True, paste)
  File "/usr/local/lib/python3.9/site-packages/bpython/curtsies.py", line 125, in mainloop
    self.process_event_and_paint(None)
  File "/usr/local/lib/python3.9/site-packages/bpython/curtsies.py", line 107, in process_event_and_paint
    array, cursor_pos = self.paint()
  File "/usr/local/lib/python3.9/site-packages/bpython/curtsiesfrontend/repl.py", line 1515, in paint
    current_line = paint.paint_current_line(
  File "/usr/local/lib/python3.9/site-packages/bpython/curtsiesfrontend/replpainter.py", line 57, in paint_current_line
    lines = display_linize(current_display_line, columns, True)
  File "/usr/local/lib/python3.9/site-packages/bpython/curtsiesfrontend/replpainter.py", line 39, in display_linize
    range(0, len(msg), columns),
ValueError: range() arg 3 must not be zero
root@pod_forum:/opt/django_forum/django_forum# ./manage.py shell
/static/ /static/

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/bpython/curtsiesfrontend/replpainter.py", line 33, in display_linize
    display_lines = list(msg.width_aware_splitlines(columns))
  File "/usr/local/lib/python3.9/site-packages/curtsies/formatstring.py", line 654, in width_aware_splitlines
    raise ValueError("Column width %s is too narrow." % columns)
ValueError: Column width 0 is too narrow.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/django_forum/django_forum/./manage.py", line 22, in <module>
    main()
  File "/opt/django_forum/django_forum/./manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/shell.py", line 100, in handle
    return getattr(self, shell)(options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/shell.py", line 40, in bpython
    bpython.embed()
  File "/usr/local/lib/python3.9/site-packages/bpython/__init__.py", line 42, in embed
    return main(args, locals_, banner)
  File "/usr/local/lib/python3.9/site-packages/bpython/curtsies.py", line 221, in main
    exit_value = repl.mainloop(True, paste)
  File "/usr/local/lib/python3.9/site-packages/bpython/curtsies.py", line 125, in mainloop
    self.process_event_and_paint(None)
  File "/usr/local/lib/python3.9/site-packages/bpython/curtsies.py", line 107, in process_event_and_paint
    array, cursor_pos = self.paint()
  File "/usr/local/lib/python3.9/site-packages/bpython/curtsiesfrontend/repl.py", line 1515, in paint
    current_line = paint.paint_current_line(
  File "/usr/local/lib/python3.9/site-packages/bpython/curtsiesfrontend/replpainter.py", line 57, in paint_current_line
    lines = display_linize(current_display_line, columns, True)
  File "/usr/local/lib/python3.9/site-packages/bpython/curtsiesfrontend/replpainter.py", line 39, in display_linize
    range(0, len(msg), columns),
ValueError: range() arg 3 must not be zero
```
It might be something completely different, but I thought I'd mention it since it seems to have issues with painting to the terminal.
Is it possible that the value for columns should be set but itsn't?
I'm afraid I don't know a great deal about the terminal setup and how podman containers might interact with it.
Are there any useful commands I can run to report what the shell can see of the terminal itself?

**Comment by rhatdan** [comment]
COLUMNS seems to come from bash, not available via sh

**Comment by mheon** [comment]
Can you try forcing a resize by sending Podman a SIGWINCH?

**Comment by giuseppe** [comment]
there was no feedback since February.  Please reopen if you've more data
