### ISSUE TITLE
Podman 3.0.1 with docker-compose segfaults when files with wildcard don't exist

### ISSUE THREAD

**Issue by sshnaidm** [containers/podman#9594]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. Run docker-compose build on attached docker-compose.yaml file

```
version: '3.6'

services:
  container:
    build: .
    container_name: sidecar

```

and Dockerfile:

```
FROM python:3.6

COPY *.json some_file /usr/local/bin/
CMD bash
```
where `some_file` **does** exist, but no `*.json` files in the folder.

**Describe the results you received:**

```
Building container
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
STEP 1: FROM python:3.6
STEP 2: COPY some_file /usr/local/bin/
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x5614104c64f5]
 
goroutine 1 [running]:
panic(0x561410cc4d00, 0x561411cfdce0)
        /usr/lib/golang/src/runtime/panic.go:1064 +0x471 fp=0xc0002fb410 sp=0xc0002fb358 pc=0x56140f2d9ea1
runtime.panicmem(...)
        /usr/lib/golang/src/runtime/panic.go:212
runtime.sigpanic()
        /usr/lib/golang/src/runtime/signal_unix.go:717 +0x3de fp=0xc0002fb440 sp=0xc0002fb410 pc=0x56140f2f12fe
github.com/containers/podman/cmd/podman/images.build(0x561411d21820, 0xc000144050, 0x1, 0x5, 0x0, 0x0)
        /home/abuild/rpmbuild/BUILD/podman-3.0.1/_build/src/github.com/containers/podman/cmd/podman/images/build.go:274 +0x4e5 fp=0xc0002fbd20 sp=0xc0002fb440 pc=0x5614104c64f5
github.com/containers/podman/vendor/github.com/spf13/cobra.(*Command).execute(0x561411d21820, 0xc000134020, 0x5, 0x5, 0x561411d21820, 0xc000134020)
        /home/abuild/rpmbuild/BUILD/podman-3.0.1/_build/src/github.com/containers/podman/vendor/github.com/spf13/cobra/command.go:850 +0x455 fp=0xc0002fbdf8 sp=0xc0002fbd20 pc=0x56140f8f32f5
github.com/containers/podman/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x561411d2cfe0, 0xc00012e020, 0x561410cc1ac0, 0x561411dd5f68)
        /home/abuild/rpmbuild/BUILD/podman-3.0.1/_build/src/github.com/containers/podman/vendor/github.com/spf13/cobra/command.go:958 +0x34b fp=0xc0002fbed0 sp=0xc0002fbdf8 pc=0x56140f8f3e2b
github.com/containers/podman/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /home/abuild/rpmbuild/BUILD/podman-3.0.1/_build/src/github.com/containers/podman/vendor/github.com/spf13/cobra/command.go:895
github.com/containers/podman/vendor/github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /home/abuild/rpmbuild/BUILD/podman-3.0.1/_build/src/github.com/containers/podman/vendor/github.com/spf13/cobra/command.go:888
main.Execute()
        /home/abuild/rpmbuild/BUILD/podman-3.0.1/_build/src/github.com/containers/podman/cmd/podman/root.go:92 +0xee fp=0xc0002fbf40 sp=0xc0002fbed0 pc=0x5614105cf9ce
main.main()
        /home/abuild/rpmbuild/BUILD/podman-3.0.1/_build/src/github.com/containers/podman/cmd/podman/main.go:36 +0x98 fp=0xc0002fbf88 sp=0xc0002fbf40 pc=0x5614105cf258
runtime.main()
        /usr/lib/golang/src/runtime/proc.go:203 +0x202 fp=0xc0002fbfe0 sp=0xc0002fbf88 pc=0x56140f2dc922
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0002fbfe8 sp=0xc0002fbfe0 pc=0x56140f30bc31
 
goroutine 2 [force gc (idle)]:
runtime.gopark(0x561410ef2730, 0x561411da3fa0, 0x1411, 0x1)
        /usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc00005afb0 sp=0xc00005af90 pc=0x56140f2dccf6
runtime.goparkunlock(...)
        /usr/lib/golang/src/runtime/proc.go:310
runtime.forcegchelper()
        /usr/lib/golang/src/runtime/proc.go:253 +0xbb fp=0xc00005afe0 sp=0xc00005afb0 pc=0x56140f2dcb9b
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00005afe8 sp=0xc00005afe0 pc=0x56140f30bc31
created by runtime.init.7
        /usr/lib/golang/src/runtime/proc.go:242 +0x37
 
goroutine 3 [GC sweep wait]:
runtime.gopark(0x561410ef2730, 0x561411da4a20, 0x140c, 0x1)
        /usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc00005b7a8 sp=0xc00005b788 pc=0x56140f2dccf6
runtime.goparkunlock(...)
        /usr/lib/golang/src/runtime/proc.go:310
runtime.bgsweep(0xc00007a000)
        /usr/lib/golang/src/runtime/mgcsweep.go:89 +0x135 fp=0xc00005b7d8 sp=0xc00005b7a8 pc=0x56140f2c8fc5
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00005b7e0 sp=0xc00005b7d8 pc=0x56140f30bc31
created by runtime.gcenable
        /usr/lib/golang/src/runtime/mgc.go:214 +0x5e
 
goroutine 4 [GC scavenge wait]:
runtime.gopark(0x561410ef2730, 0x561411da49e0, 0x140d, 0x1)
        /usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc00005bf78 sp=0xc00005bf58 pc=0x56140f2dccf6
runtime.goparkunlock(...)
        /usr/lib/golang/src/runtime/proc.go:310
runtime.bgscavenge(0xc00007a000)
        /usr/lib/golang/src/runtime/mgcscavenge.go:285 +0x294 fp=0xc00005bfd8 sp=0xc00005bf78 pc=0x56140f2c7644
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00005bfe0 sp=0xc00005bfd8 pc=0x56140f30bc31
created by runtime.gcenable
        /usr/lib/golang/src/runtime/mgc.go:215 +0x80
 
goroutine 18 [finalizer wait]:
runtime.gopark(0x561410ef2730, 0x561411dd5eb0, 0xc0005c1410, 0x1)
        /usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc00005a758 sp=0xc00005a738 pc=0x56140f2dccf6
runtime.goparkunlock(...)
        /usr/lib/golang/src/runtime/proc.go:310
runtime.runfinq()
        /usr/lib/golang/src/runtime/mfinal.go:175 +0xa7 fp=0xc00005a7e0 sp=0xc00005a758 pc=0x56140f2bea37
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00005a7e8 sp=0xc00005a7e0 pc=0x56140f30bc31
created by runtime.createfing
        /usr/lib/golang/src/runtime/mfinal.go:156 +0x63
 
goroutine 11 [syscall]:
runtime.notetsleepg(0x561411dd6a40, 0xffffffffffffffff, 0xc0000567c8)
        /usr/lib/golang/src/runtime/lock_futex.go:227 +0x38 fp=0xc000056798 sp=0xc000056768 pc=0x56140f2b1348
os/signal.signal_recv(0x0)
        /usr/lib/golang/src/runtime/sigqueue.go:147 +0x9e fp=0xc0000567c0 sp=0xc000056798 pc=0x56140f2f215e
os/signal.loop()
        /usr/lib/golang/src/os/signal/signal_unix.go:23 +0x24 fp=0xc0000567e0 sp=0xc0000567c0 pc=0x56140fadc9c4
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0000567e8 sp=0xc0000567e0 pc=0x56140f30bc31
created by os/signal.Notify.func1
        /usr/lib/golang/src/os/signal/signal.go:127 +0x46
 
goroutine 34 [GC worker (idle)]:
runtime.gopark(0x561410ef25b8, 0xc000512000, 0x1418, 0x0)
        /usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc00050e760 sp=0xc00050e740 pc=0x56140f2dccf6
runtime.gcBgMarkWorker(0xc00004c000)
        /usr/lib/golang/src/runtime/mgc.go:1873 +0x105 fp=0xc00050e7d8 sp=0xc00050e760 pc=0x56140f2c2435
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00050e7e0 sp=0xc00050e7d8 pc=0x56140f30bc31
created by runtime.gcBgMarkStartWorkers
        /usr/lib/golang/src/runtime/mgc.go:1821 +0x79
 
goroutine 35 [GC worker (idle)]:
runtime.gopark(0x561410ef25b8, 0xc0004b8770, 0x1418, 0x0)
        /usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc00050ef60 sp=0xc00050ef40 pc=0x56140f2dccf6
runtime.gcBgMarkWorker(0xc00004e800)
        /usr/lib/golang/src/runtime/mgc.go:1873 +0x105 fp=0xc00050efd8 sp=0xc00050ef60 pc=0x56140f2c2435
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00050efe0 sp=0xc00050efd8 pc=0x56140f30bc31
created by runtime.gcBgMarkStartWorkers
        /usr/lib/golang/src/runtime/mgc.go:1821 +0x79
 
goroutine 20 [GC worker (idle)]:
runtime.gopark(0x561410ef25b8, 0xc0004b8780, 0x1418, 0x0)
        /usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc000056f60 sp=0xc000056f40 pc=0x56140f2dccf6
runtime.gcBgMarkWorker(0xc000051000)
        /usr/lib/golang/src/runtime/mgc.go:1873 +0x105 fp=0xc000056fd8 sp=0xc000056f60 pc=0x56140f2c2435
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000056fe0 sp=0xc000056fd8 pc=0x56140f30bc31
created by runtime.gcBgMarkStartWorkers
        /usr/lib/golang/src/runtime/mgc.go:1821 +0x79
 
goroutine 21 [GC worker (idle)]:
runtime.gopark(0x561410ef25b8, 0xc0000460c0, 0x1418, 0x0)
        /usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc000057760 sp=0xc000057740 pc=0x56140f2dccf6
runtime.gcBgMarkWorker(0xc000053800)
        /usr/lib/golang/src/runtime/mgc.go:1873 +0x105 fp=0xc0000577d8 sp=0xc000057760 pc=0x56140f2c2435
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0000577e0 sp=0xc0000577d8 pc=0x56140f30bc31
created by runtime.gcBgMarkStartWorkers
        /usr/lib/golang/src/runtime/mgc.go:1821 +0x79
 
goroutine 12 [select, locked to thread]:
runtime.gopark(0x561410ef2780, 0x0, 0x1809, 0x1)
        /usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc00005ce08 sp=0xc00005cde8 pc=0x56140f2dccf6
runtime.selectgo(0xc00005cf78, 0xc00005cf70, 0x2, 0x8, 0x5614105dd901)
        /usr/lib/golang/src/runtime/select.go:335 +0xc87 fp=0xc00005cf30 sp=0xc00005ce08 pc=0x56140f2ed2f7
runtime.ensureSigM.func1()
        /usr/lib/golang/src/runtime/signal_unix.go:872 +0x1da fp=0xc00005cfe0 sp=0xc00005cf30 pc=0x56140f3090da
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00005cfe8 sp=0xc00005cfe0 pc=0x56140f30bc31
created by runtime.ensureSigM
        /usr/lib/golang/src/runtime/signal_unix.go:855 +0xd7
 
goroutine 10 [chan receive]:
runtime.gopark(0x561410ef2530, 0xc00007f618, 0x170e, 0x2)
        /usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc0005bfed0 sp=0xc0005bfeb0 pc=0x56140f2dccf6
runtime.chanrecv(0xc00007f5c0, 0xc0005bffb0, 0xc0004c4001, 0xc00007f5c0)
        /usr/lib/golang/src/runtime/chan.go:535 +0x2f9 fp=0xc0005bff60 sp=0xc0005bfed0 pc=0x56140f2abcd9
runtime.chanrecv2(0xc00007f5c0, 0xc0005bffb0, 0x561410ef2610)
        /usr/lib/golang/src/runtime/chan.go:417 +0x2b fp=0xc0005bff90 sp=0xc0005bff60 pc=0x56140f2ab9cb
github.com/containers/podman/vendor/k8s.io/klog.(*loggingT).flushDaemon(0x561411da7600)
        /home/abuild/rpmbuild/BUILD/podman-3.0.1/_build/src/github.com/containers/podman/vendor/k8s.io/klog/klog.go:1010 +0x8d fp=0xc0005bffd8 sp=0xc0005bff90 pc=0x56140ff013bd
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0005bffe0 sp=0xc0005bffd8 pc=0x56140f30bc31
created by github.com/containers/podman/vendor/k8s.io/klog.init.0
        /home/abuild/rpmbuild/BUILD/podman-3.0.1/_build/src/github.com/containers/podman/vendor/k8s.io/klog/klog.go:411 +0xd8
 
goroutine 9 [chan receive]:
runtime.gopark(0x561410ef2530, 0xc00007f5b8, 0x170e, 0x2)
        /usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc00050f6d0 sp=0xc00050f6b0 pc=0x56140f2dccf6
runtime.chanrecv(0xc00007f560, 0xc00050f7b0, 0xc0004c4001, 0xc00007f560)
        /usr/lib/golang/src/runtime/chan.go:535 +0x2f9 fp=0xc00050f760 sp=0xc00050f6d0 pc=0x56140f2abcd9
runtime.chanrecv2(0xc00007f560, 0xc00050f7b0, 0x561410ef2610)
        /usr/lib/golang/src/runtime/chan.go:417 +0x2b fp=0xc00050f790 sp=0xc00050f760 pc=0x56140f2ab9cb
github.com/containers/podman/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x561411da78e0)
        /home/abuild/rpmbuild/BUILD/podman-3.0.1/_build/src/github.com/containers/podman/vendor/k8s.io/klog/v2/klog.go:1169 +0x8d fp=0xc00050f7d8 sp=0xc00050f790 pc=0x56140fefaead
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00050f7e0 sp=0xc00050f7d8 pc=0x56140f30bc31
created by github.com/containers/podman/vendor/k8s.io/klog/v2.init.0
        /home/abuild/rpmbuild/BUILD/podman-3.0.1/_build/src/github.com/containers/podman/vendor/k8s.io/klog/v2/klog.go:417 +0xdf
 
goroutine 25 [select]:
runtime.gopark(0x561410ef2780, 0x0, 0x1809, 0x1)
        /usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc000068d68 sp=0xc000068d48 pc=0x56140f2dccf6
runtime.selectgo(0xc000068f80, 0xc000068ee0, 0x2, 0x3, 0x0)
        /usr/lib/golang/src/runtime/select.go:335 +0xc87 fp=0xc000068e90 sp=0xc000068d68 pc=0x56140f2ed2f7
github.com/containers/podman/libpod/shutdown.Start.func1()
        /home/abuild/rpmbuild/BUILD/podman-3.0.1/_build/src/github.com/containers/podman/libpod/shutdown/handler.go:45 +0xcd fp=0xc000068fe0 sp=0xc000068e90 pc=0x561410212a7d
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000068fe8 sp=0xc000068fe0 pc=0x56140f30bc31
created by github.com/containers/podman/libpod/shutdown.Start
        /home/abuild/rpmbuild/BUILD/podman-3.0.1/_build/src/github.com/containers/podman/libpod/shutdown/handler.go:44 +0x116
 
goroutine 47 [select]:
runtime.gopark(0x561410ef2780, 0x0, 0x1809, 0x1)
        /usr/lib/golang/src/runtime/proc.go:304 +0xe6 fp=0xc0005bad40 sp=0xc0005bad20 pc=0x56140f2dccf6
runtime.selectgo(0xc0005baf38, 0xc0005baeb4, 0x3, 0x561410c9b4a0, 0x56140f3061c0)
        /usr/lib/golang/src/runtime/select.go:335 +0xc87 fp=0xc0005bae68 sp=0xc0005bad40 pc=0x56140f2ed2f7
github.com/containers/podman/vendor/github.com/cri-o/ocicni/pkg/ocicni.(*cniNetworkPlugin).monitorConfDir(0xc000198000, 0xc0004b8b40)
        /home/abuild/rpmbuild/BUILD/podman-3.0.1/_build/src/github.com/containers/podman/vendor/github.com/cri-o/ocicni/pkg/ocicni/ocicni.go:150 +0x19d fp=0xc0005bafd0 sp=0xc0005bae68 pc=0x56140fac90dd
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0005bafd8 sp=0xc0005bafd0 pc=0x56140f30bc31
created by github.com/containers/podman/vendor/github.com/cri-o/ocicni/pkg/ocicni.initCNI
        /home/abuild/rpmbuild/BUILD/podman-3.0.1/_build/src/github.com/containers/podman/vendor/github.com/cri-o/ocicni/pkg/ocicni/ocicni.go:250 +0x39d
 
goroutine 46 [syscall]:
syscall.Syscall6(0xe8, 0xa, 0xc00069fb74, 0x7, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/syscall/asm_linux_amd64.s:41 +0x5 fp=0xc00069faa8 sp=0xc00069faa0 pc=0x56140f360905
github.com/containers/podman/vendor/golang.org/x/sys/unix.EpollWait(0xa, 0xc00069fb74, 0x7, 0x7, 0xffffffffffffffff, 0x0, 0x0, 0x0)
        /home/abuild/rpmbuild/BUILD/podman-3.0.1/_build/src/github.com/containers/podman/vendor/golang.org/x/sys/unix/zsyscall_linux_amd64.go:76 +0x74 fp=0xc00069fb18 sp=0xc00069faa8 pc=0x56140f641da4
github.com/containers/podman/vendor/github.com/fsnotify/fsnotify.(*fdPoller).wait(0xc000378ba0, 0x0, 0x0, 0x0)
        /home/abuild/rpmbuild/BUILD/podman-3.0.1/_build/src/github.com/containers/podman/vendor/github.com/fsnotify/fsnotify/inotify_poller.go:86 +0x93 fp=0xc00069fbe0 sp=0xc00069fb18 pc=0x56140fa48493
github.com/containers/podman/vendor/github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc000568000)
        /home/abuild/rpmbuild/BUILD/podman-3.0.1/_build/src/github.com/containers/podman/vendor/github.com/fsnotify/fsnotify/inotify.go:192 +0x1fa fp=0xc0006affd8 sp=0xc00069fbe0 pc=0x56140fa4768a
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0006affe0 sp=0xc0006affd8 pc=0x56140f30bc31
created by github.com/containers/podman/vendor/github.com/fsnotify/fsnotify.NewWatcher
        /home/abuild/rpmbuild/BUILD/podman-3.0.1/_build/src/github.com/containers/podman/vendor/github.com/fsnotify/fsnotify/inotify.go:59 +0x1a7
Service 'container' failed to build
```

**Describe the results you expected:**
Container is built.
Docker with docker-compose copy existing files and doesn't fail if some of them don't exist.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.0.1
API Version:  3.0.0
Go Version:   go1.14.12
Built:        Tue Mar  2 20:31:11 2021
OS/Arch:      linux/amd64


```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.19.4
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.26-4.el8.5.2.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.26, commit: 6ce9825c91d32f9890be05932c8e5a39c6a8ae2a'
  cpus: 4
  distribution:
    distribution: '"centos"'
    version: "8"
  eventLogger: journald
  hostname: localhost
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-240.15.1.el8_3.x86_64
  linkmode: dynamic
  memFree: 190271488
  memTotal: 1906663424
  ociRuntime:
    name: crun
    package: crun-0.18-3.el8.5.2.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.18
      commit: 808420efe3dc2b44d6db9f1a3fac8361dde42a95
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    selinuxEnabled: true
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 1h 33m 49.93s (Approximately 0.04 days)
registries:
  docker.io:
    Blocked: false
    Insecure: true
    Location: docker.io
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: docker.io
  search:
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 8
    paused: 0
    running: 6
    stopped: 2
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 45
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 1614717071
  BuiltTime: Tue Mar  2 20:31:11 2021
  GitCommit: ""
  GoVersion: go1.14.12
  OsArch: linux/amd64
  Version: 3.0.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.0.1-1.fc33.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**
When trying to build Dockerfile with buildah:
```STEP 1: FROM python:3.6
STEP 2: COPY *json some_file /tmp
error building at STEP "COPY *json some_file /tmp": error adding sources [/tmp/test/*json /tmp/test/some_file]: error checking on source /tmp/test/*json under "/tmp/test": copier: stat: "/*json": no such file or directory
```
When trying to build with docker and `some_file` exists, but no `*.json` file in the folder:
```
Sending build context to Docker daemon   2.56kB
Step 1/3 : FROM python:3.6
 ---> 7c8e7e3bc7ac
Step 2/3 : COPY *json some_file /tmp
 ---> e0800293e600
Step 3/3 : CMD bash
 ---> Running in 5160f4f8fdf4
Removing intermediate container 5160f4f8fdf4
 ---> 27887b86834d
Successfully built 27887b86834d
Successfully tagged test:latest
```

**Comment by Luap99** [comment]
#9595 fixes the panic. The wildcard issue must be fixed in buildah.

**Comment by mheon** [comment]
@TomSweeneyRedHat PTAL at the Buildah part of this

**Comment by TomSweeneyRedHat** [comment]
@mheon thanks for the heads up.  I've created https://github.com/containers/buildah/issues/3087 in Buildah to handle the Buildah piece.  Feel free to close this issue when the Podman piece fo this issue is solved.
